Repository ultralytics/ultralytics, pull requests merged in 2023-07, with the labels that each got.

#3529 `ultralytics 8.0.129` add YOLOv8 Tencent NCNN export
  docs/modes/export.md
  docs/modes/val.md
  docs/tasks/classify.md
  docs/tasks/detect.md
  docs/tasks/pose.md
  docs/tasks/segment.md
  ultralytics/__init__.py
  ultralytics/nn/autobackend.py
  ultralytics/yolo/engine/exporter.py
  ultralytics/yolo/utils/benchmarks.py
  ultralytics/yolo/utils/checks.py
  ultralytics/yolo/utils/downloads.py
Labels: enhancement

#3872 Update tasks.py to allow custom RTEDTRDecoder arguments
  ultralytics/nn/tasks.py
Labels: TODO

#3924 Add tests before pushing to Docker Hub
  .github/workflows/docker.yaml
  docker/Dockerfile-python
  requirements.txt
  setup.py
  ultralytics/engine/exporter.py
  ultralytics/utils/benchmarks.py
  ultralytics/utils/torch_utils.py
Labels: TODO

#1695 Fix catastrophic accuracy degradation of TFLite static quantized integer models
  ultralytics/engine/exporter.py
  ultralytics/engine/model.py
  ultralytics/nn/autobackend.py
Labels: fixed

#4066 Bump slackapi/slack-github-action from 1.23.0 to 1.24.0
  .github/workflows/docker.yaml
  docs/datasets/detect/coco.md
  docs/datasets/pose/coco.md
  docs/datasets/segment/coco.md
Labels: dependencies
