Repository ultralytics/ultralytics, pull requests merged in 2023-12, with the labels that each got.

#6823 Fix guide formatting
  docs/en/guides/isolating-segmentation-objects.md
Labels: documentation, fixed

#6799 Discord badge
  README.md
  README.zh-CN.md
  docs/ar/index.md
  docs/de/index.md
  docs/en/index.md
  docs/es/index.md
  docs/fr/index.md
  docs/hi/index.md
  docs/ja/index.md
  docs/ko/index.md
  docs/pt/index.md
  docs/ru/index.md
  docs/zh/index.md
Labels: documentation

#7152 Fix some parameters of heatmaps in Ultralytics solution
  docs/en/guides/heatmaps.md
Labels: enhancement

#7230 Add links to Docs pages in the vertical bar, update PR #7199
  docs/en/integrations/index.md
  docs/en/integrations/weights-biases.md
  docs/mkdocs.yml
Labels: documentation, enhancement
