Repository ultralytics/ultralytics, pull requests merged in 2023-04, with the labels that each got.

#1732 Add option for plot
  docs/modes/predict.md
  docs/usage/cfg.md
  tests/test_python.py
  ultralytics/yolo/cfg/__init__.py
  ultralytics/yolo/cfg/default.yaml
  ultralytics/yolo/engine/results.py
  ultralytics/yolo/utils/__init__.py
  ultralytics/yolo/v8/detect/predict.py
  ultralytics/yolo/v8/segment/predict.py
Labels: TODO

#1698 Fix: don't globally modify matplotlib settings
  ultralytics/yolo/utils/__init__.py
  ultralytics/yolo/utils/metrics.py
  ultralytics/yolo/utils/plotting.py
Labels: TODO

#1987 added confusion matrix for classification
  ultralytics/yolo/utils/metrics.py
  ultralytics/yolo/v8/classify/val.py
Labels: enhancement

#2141 Update README.md
  README.md
Labels: documentation
