Repository ultralytics/ultralytics, pull requests merged in 2024-08, with the labels that each got.

#14877 Fix `model` in Pose, Segment datasets train FAQ sections
  docs/en/datasets/pose/coco.md
  docs/en/datasets/pose/coco8-pose.md
  docs/en/datasets/pose/tiger-pose.md
  docs/en/datasets/segment/coco.md
  docs/en/datasets/segment/coco8-seg.md
Labels: documentation, segment, pose

#14866 Fixed `box_label` docstrings
  ultralytics/utils/plotting.py
Labels: documentation

#14882 Add missing CLI `yolo` commands for `TASK` and `MODE` in Docs - Quickstart and CLI Guide
  docs/en/quickstart.md
  docs/en/usage/cli.md
  ultralytics/utils/__init__.py
Labels: documentation, OBB, pose

#14892 Increase Dockerfile build `max-parallel`
  .github/workflows/docker.yaml
Labels: enhancement, dependencies, devops

#14889 Fix incorrect CLI commands in Datasets Docs
  docs/en/datasets/classify/caltech101.md
  docs/en/datasets/classify/caltech256.md
  docs/en/datasets/classify/cifar10.md
  docs/en/datasets/classify/cifar100.md
  docs/en/datasets/classify/fashion-mnist.md
  docs/en/datasets/classify/imagenet.md
  docs/en/datasets/classify/imagenet10.md
  docs/en/datasets/classify/imagenette.md
  docs/en/datasets/classify/imagewoof.md
  docs/en/datasets/classify/mnist.md
  docs/en/datasets/obb/index.md
  docs/en/datasets/pose/coco.md
  docs/en/datasets/pose/coco8-pose.md
  docs/en/datasets/pose/index.md
  docs/en/datasets/segment/coco.md
  docs/en/datasets/segment/coco8-seg.md
  docs/en/datasets/segment/index.md
Labels: documentation

#14557 Add Segment masks to YOLO-Seg labels converter
  docs/en/reference/data/converter.md
  docs/en/usage/simple-utilities.md
  docs/mkdocs_github_authors.yaml
  ultralytics/data/converter.py
Labels: documentation, enhancement, segment

#14894 Delete Docker Cache before building Image
  .github/workflows/docker.yaml
Labels: enhancement, devops

#14932 ROS quickstart meta description
  docs/en/guides/ros-quickstart.md
Labels: documentation

#14934 Fix the docstring of xywhr2xyxyxyxy
  ultralytics/utils/ops.py
Labels: documentation, OBB

#14909 Fixed `circle_label` and `text_label` docstrings
  ultralytics/utils/plotting.py
Labels: documentation, enhancement

#14923 Fix `is_url()` and `check_disk_space()` docstrings in downloads.py
  ultralytics/utils/downloads.py
Labels: documentation, enhancement

#14901 Update MLP module for RTDETR backward compatibility
  tests/test_cli.py
  ultralytics/nn/modules/transformer.py
Labels: enhancement, track, detect

#14857 Corrects CONTRIBUTING.md relative link to CLA.md
  CONTRIBUTING.md
  docs/en/help/contributing.md
Labels: documentation

#14928 `ultralytics 8.2.72` SAM 2 multiple-`bboxes` support
  ultralytics/__init__.py
  ultralytics/models/sam2/predict.py
Labels: enhancement, segment

#14867 `ultralytics 8.2.73` Meta SAM2 Refactor
  docs/en/reference/models/sam/build.md
  docs/en/reference/models/sam/model.md
  docs/en/reference/models/sam/modules/blocks.md
  docs/en/reference/models/sam/modules/decoders.md
  docs/en/reference/models/sam/modules/encoders.md
  docs/en/reference/models/sam/modules/memory_attention.md
  docs/en/reference/models/sam/modules/sam.md
  docs/en/reference/models/sam/modules/tiny_encoder.md
  docs/en/reference/models/sam/modules/utils.md
  docs/en/reference/models/sam/predict.md
  docs/en/reference/models/sam2/build.md
  docs/en/reference/models/sam2/model.md
  docs/en/reference/models/sam2/modules/decoders.md
  docs/en/reference/models/sam2/modules/encoders.md
  docs/en/reference/models/sam2/modules/memory_attention.md
  docs/en/reference/models/sam2/modules/sam2.md
  docs/en/reference/models/sam2/modules/sam2_blocks.md
  docs/en/reference/models/sam2/modules/utils.md
  docs/en/reference/models/sam2/predict.md
  mkdocs.yml
  ultralytics/__init__.py
  ultralytics/models/__init__.py
  ultralytics/models/sam/__init__.py
  ultralytics/models/sam/amg.py
  ultralytics/models/sam/build.py
  ultralytics/models/sam/model.py
  ultralytics/models/sam/modules/blocks.py
  ultralytics/models/sam/modules/decoders.py
  ultralytics/models/sam/modules/encoders.py
  ultralytics/models/sam/modules/memory_attention.py
  ultralytics/models/sam/modules/sam.py
  ultralytics/models/sam/modules/tiny_encoder.py
  ultralytics/models/sam/modules/transformer.py
  ultralytics/models/sam/modules/utils.py
  ultralytics/models/sam/predict.py
  ultralytics/models/sam2/__init__.py
  ultralytics/models/sam2/build.py
  ultralytics/models/sam2/model.py
  ultralytics/models/sam2/modules/__init__.py
  ultralytics/models/sam2/modules/decoders.py
  ultralytics/models/sam2/modules/encoders.py
  ultralytics/models/sam2/modules/sam2.py
  ultralytics/models/sam2/modules/sam2_blocks.py
  ultralytics/models/sam2/predict.py
Labels: TODO, enhancement, segment

#14980 Ignore Vimeo 401 'unauthorized' errors
  .github/workflows/links.yml
Labels: enhancement, devops

#14970 fix example for plotting Ray Tune history
  docs/en/integrations/ray-tune.md
Labels: documentation, enhancement

#14939 Update NVIDIA Jetson Docs with JetPack 6
  docs/en/guides/nvidia-jetson.md
Labels: documentation, embedded, exports

#14918 Fix OpenVINO Export Docs
  docs/en/integrations/openvino.md
  docs/en/modes/benchmark.md
  docs/en/modes/export.md
  docs/en/tasks/classify.md
  docs/en/tasks/detect.md
  docs/en/tasks/obb.md
  docs/en/tasks/pose.md
  docs/en/tasks/segment.md
  docs/en/usage/cfg.md
  docs/en/usage/cli.md
Labels: documentation, exports

#14965 `ultralytics 8.2.74` add `fuse_score=True` BoT-SORT and ByteTrack arg
  docs/mkdocs_github_authors.yaml
  ultralytics/__init__.py
  ultralytics/cfg/trackers/botsort.yaml
  ultralytics/cfg/trackers/bytetrack.yaml
  ultralytics/trackers/bot_sort.py
  ultralytics/trackers/byte_tracker.py
Labels: enhancement, track

#14995 Fix Docker git permissions
  docker/Dockerfile
  docker/Dockerfile-arm64
  docker/Dockerfile-conda
  docker/Dockerfile-cpu
  docker/Dockerfile-jetson-jetpack4
  docker/Dockerfile-jetson-jetpack5
  docker/Dockerfile-jetson-jetpack6
  docker/Dockerfile-python
  docker/Dockerfile-runner
Labels: dependencies, devops

#14992 Dedicated Inference API Docs
  docs/en/hub/inference-api.md
  docs/en/hub/pro.md
  docs/en/modes/predict.md
Labels: documentation, HUB

#15035 Update HUB Inference API Docs
  docs/en/hub/inference-api.md
Labels: documentation, enhancement, HUB

#15037 Add `allow_background_images=True` in split_dota.py
  ultralytics/data/split_dota.py
Labels: enhancement, fixed, detect

#15050 `ultralytics 8.2.75` new Docs author profiles
  docs/mkdocs_github_authors.yaml
  docs/overrides/stylesheets/style.css
  mkdocs.yml
  pyproject.toml
  ultralytics/__init__.py
Labels: documentation, enhancement

#15062 Update Docs CSS
  docs/overrides/stylesheets/style.css
  pyproject.toml
Labels: documentation, enhancement

#14990 Use macros for Docs tables de-duplication
  .github/workflows/ci.yaml
  docs/build_docs.py
  docs/en/datasets/detect/lvis.md
  docs/en/hub/integrations.md
  docs/en/integrations/index.md
  docs/en/macros/export-args.md
  docs/en/macros/export-table.md
  docs/en/models/yolov7.md
  docs/en/models/yolov9.md
  docs/en/modes/benchmark.md
  docs/en/modes/export.md
  docs/en/tasks/classify.md
  docs/en/tasks/detect.md
  docs/en/tasks/obb.md
  docs/en/tasks/pose.md
  docs/en/tasks/segment.md
  docs/en/usage/cfg.md
  docs/en/usage/cli.md
  mkdocs.yml
  pyproject.toml
Labels: documentation, exports

#15105 Delete macros from sitemap.xml
  docs/build_docs.py
Labels: documentation, enhancement

#15107 Add https://youtu.be/EeDd5P4eS6A to docs
  docs/en/integrations/weights-biases.md
Labels: documentation, enhancement

#15183 Optimized SAHI video inference
  examples/YOLOv8-SAHI-Inference-Video/yolov8_sahi.py
Labels: enhancement, track, detect

#15176 Update `convert_segment_masks_to_yolo_seg` to support custom datasets
  docs/en/usage/simple-utilities.md
  ultralytics/data/converter.py
Labels: bug, documentation, enhancement, segment

#15185 `ultralytics 8.2.76` Autobackend TensorRT/Triton Segment metadata fix
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/nn/autobackend.py
Labels: bug, fixed, segment

#15373 Update Contributing guidelines
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  README.zh-CN.md
  docs/en/help/contributing.md
Labels: documentation, enhancement

#15392 Fixed multiscale preprocess_batch
  ultralytics/models/yolo/detect/train.py
Labels: bug, enhancement, detect

#15383 Improve trainer DDP device handling
  ultralytics/engine/trainer.py
Labels: enhancement

#15443 Update Conda CI
  .github/workflows/ci.yaml
Labels: dependencies, devops

#15469 Update Tracker docstrings
  ultralytics/cfg/__init__.py
  ultralytics/trackers/basetrack.py
  ultralytics/trackers/bot_sort.py
  ultralytics/trackers/byte_tracker.py
  ultralytics/trackers/track.py
  ultralytics/trackers/utils/gmc.py
  ultralytics/trackers/utils/kalman_filter.py
  ultralytics/trackers/utils/matching.py
  ultralytics/utils/__init__.py
  ultralytics/utils/files.py
Labels: documentation, track

#15034 `ultralytics 8.2.77` new `color_mode=instance` plot arg
  docs/en/modes/predict.md
  ultralytics/__init__.py
  ultralytics/engine/results.py
  ultralytics/utils/plotting.py
Labels: documentation, enhancement

#15470 Update yolov8_sahi.py
  examples/YOLOv8-SAHI-Inference-Video/yolov8_sahi.py
Labels: documentation, enhancement

#15599 Ultralytics Actions JSON, CSS and autolabel support
  .github/workflows/format.yml
Labels: enhancement, devops

#15582 Remove unnecessary assignments
  ultralytics/data/augment.py
Labels: enhancement

#15602 YOLO Vision 2024 updates https://ultralytics.com/events/yolovision
  README.md
  README.zh-CN.md
  docs/en/index.md
  tests/test_cli.py
Labels: documentation

#15616 `ultralytics 8.2.78` fix DDP training with pretrained weights
  examples/heatmaps.ipynb
  examples/hub.ipynb
  examples/object_counting.ipynb
  examples/object_tracking.ipynb
  ultralytics/__init__.py
  ultralytics/engine/model.py
Labels: enhancement

#15656 Split Docs action into separate workflow
  .github/workflows/ci.yaml
  .github/workflows/docs.yml
  .github/workflows/publish.yml
Labels: documentation, enhancement, devops

#15663 Add https://youtu.be/28JV4rbzklM to docs
  docs/en/datasets/detect/visdrone.md
Labels: documentation, enhancement

#15665 Fix YOLOv8 C++ Example model input size
  examples/YOLOv8-CPP-Inference/main.cpp
Labels: bug, enhancement, detect

#15675 Skip Docs push if no changes
  .github/workflows/docs.yml
Labels: documentation, enhancement, devops

#15657 Simplify publish action
  .github/workflows/publish.yml
  docs/build_docs.py
Labels: enhancement, devops

#15672 `ultralytics 8.2.79` YOLOv10 CoreML and MPS training "gather" op error fix
  ultralytics/__init__.py
  ultralytics/nn/modules/head.py
Labels: detect, devops, exports

#15703 Remove Hindi and Dutch languages
  README.md
  README.zh-CN.md
  mkdocs.yml
Labels: documentation, enhancement

#15704 Remove Hindi and Dutch languages
  examples/heatmaps.ipynb
  examples/object_counting.ipynb
  examples/object_tracking.ipynb
  examples/tutorial.ipynb
Labels: enhancement

#15686 Update publish.yml to use `gh`
  .github/workflows/docs.yml
  .github/workflows/publish.yml
  docs/en/hub/index.md
Labels: enhancement, devops

#15728 Update HUB Docs for new dataset download feature
  docs/en/hub/datasets.md
Labels: documentation, enhancement, HUB

#15726 Fix model `names` docstring type to `dict`
  ultralytics/engine/model.py
  ultralytics/utils/metrics.py
Labels: bug, enhancement

#15719 `ultralytics 8.2.80` add PIL type hints to `model()`
  ultralytics/__init__.py
  ultralytics/engine/model.py
Labels: documentation, enhancement

#15751 Add https://youtu.be/WwXnljc7ZUM to docs
  docs/en/guides/parking-management.md
Labels: documentation, detect

#15696 Improve Docs dataset layout issues
  docs/en/datasets/classify/cifar10.md
  docs/en/datasets/classify/imagewoof.md
  docs/en/datasets/detect/roboflow-100.md
  docs/en/datasets/detect/visdrone.md
  docs/en/datasets/segment/crack-seg.md
  docs/en/datasets/segment/package-seg.md
Labels: documentation

#15765 Fix `xywh` docstring
  ultralytics/engine/results.py
Labels: documentation, detect

#15759 Ensure matplotlib backend gets reset with plt_settings
  ultralytics/utils/__init__.py
Labels: bug, enhancement

#15754 `ultralytics 8.2.81` fix HUB missing 'best.pt' resumed checkpoint upload
  ultralytics/__init__.py
  ultralytics/hub/session.py
Labels: enhancement, HUB

#15789 Update robots.txt
  docs/en/datasets/explorer/explorer.ipynb
  docs/en/index.md
  docs/en/robots.txt
  examples/hub.ipynb
Labels: documentation, enhancement

#15776 Properly use cmake variable in ONNXRuntime
  examples/YOLOv8-ONNXRuntime-CPP/CMakeLists.txt
  examples/YOLOv8-ONNXRuntime-CPP/README.md
Labels: documentation, dependencies, exports

#15772 Missing best.pt resumed checkpoint upload spelling
  ultralytics/hub/session.py
Labels: documentation

#15793 Ruff Docstring formatting
  .github/workflows/docs.yml
  docs/build_docs.py
  examples/YOLOv8-Action-Recognition/action_recognition.py
  examples/YOLOv8-ONNXRuntime/main.py
  examples/YOLOv8-OpenCV-int8-tflite-Python/main.py
  examples/YOLOv8-Region-Counter/yolov8_region_counter.py
  examples/YOLOv8-Segmentation-ONNXRuntime-Python/main.py
  pyproject.toml
  tests/test_solutions.py
  ultralytics/cfg/__init__.py
  ultralytics/data/augment.py
  ultralytics/data/converter.py
  ultralytics/data/explorer/explorer.py
  ultralytics/data/loaders.py
  ultralytics/data/split_dota.py
  ultralytics/data/utils.py
  ultralytics/engine/exporter.py
  ultralytics/engine/predictor.py
  ultralytics/engine/trainer.py
  ultralytics/engine/tuner.py
  ultralytics/engine/validator.py
  ultralytics/hub/auth.py
  ultralytics/hub/session.py
  ultralytics/models/fastsam/model.py
  ultralytics/models/fastsam/utils.py
  ultralytics/models/nas/predict.py
  ultralytics/models/sam/modules/transformer.py
  ultralytics/models/utils/loss.py
  ultralytics/models/utils/ops.py
  ultralytics/models/yolo/model.py
  ultralytics/nn/autobackend.py
  ultralytics/nn/modules/block.py
  ultralytics/nn/modules/conv.py
  ultralytics/nn/modules/head.py
  ultralytics/nn/modules/transformer.py
  ultralytics/nn/modules/utils.py
  ultralytics/nn/tasks.py
  ultralytics/solutions/ai_gym.py
  ultralytics/solutions/analytics.py
  ultralytics/solutions/heatmap.py
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/queue_management.py
  ultralytics/trackers/basetrack.py
  ultralytics/trackers/utils/matching.py
  ultralytics/utils/__init__.py
  ultralytics/utils/autobatch.py
  ultralytics/utils/benchmarks.py
  ultralytics/utils/callbacks/base.py
  ultralytics/utils/callbacks/comet.py
  ultralytics/utils/callbacks/tensorboard.py
  ultralytics/utils/checks.py
  ultralytics/utils/downloads.py
  ultralytics/utils/files.py
  ultralytics/utils/instance.py
  ultralytics/utils/metrics.py
  ultralytics/utils/ops.py
  ultralytics/utils/plotting.py
  ultralytics/utils/tal.py
  ultralytics/utils/torch_utils.py
  ultralytics/utils/tuner.py
Labels: documentation

#15795 TQDM, SimpleClass, IterableSimpleNamespace docstrings
  .github/workflows/docs.yml
  ultralytics/utils/__init__.py
Labels: documentation, enhancement

#15779 Fix YOLOv8 C++ ONNXRuntime transpose op
  examples/YOLOv8-ONNXRuntime-CPP/inference.cpp
Labels: enhancement, detect, exports

#15796 `ultralytics 8.2.82` YOLOv10 CoreML, Edge TPU and TF.js export support
  docs/en/models/yolov10.md
  ultralytics/__init__.py
  ultralytics/nn/modules/head.py
  ultralytics/utils/benchmarks.py
Labels: enhancement, detect

#15801 Update merge-main-into-prs.yml
  .github/workflows/merge-main-into-prs.yml
Labels: enhancement, devops

#15803 Fix very large banner SVGs bug
  docs/overrides/main.html
Labels: bug, documentation

#15802 Rate limit auto-merge action
  .github/workflows/merge-main-into-prs.yml
Labels: enhancement, devops

#13605 Auto-label PR if above threshold for positive reactions
  .github/workflows/merge-main-into-prs.yml
Labels: TODO, enhancement, devops

#15041 Add Reddit link to documentation and templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/greetings.yml
  README.md
  README.zh-CN.md
  docs/README.md
  mkdocs.yml
Labels: documentation

#15818 Add https://www.reddit.com/r/Ultralytics/ badge
  .github/workflows/greetings.yml
  .github/workflows/merge-main-into-prs.yml
  README.md
  README.zh-CN.md
  docs/README.md
  docs/en/hub/index.md
  docs/en/index.md
  examples/hub.ipynb
  examples/tutorial.ipynb
Labels: documentation, enhancement

#15027 Add VS Code Extension
  docs/en/integrations/index.md
  docs/en/integrations/vscode.md
  docs/en/quickstart.md
  docs/en/reference/utils/__init__.md
  mkdocs.yml
  ultralytics/cfg/__init__.py
  ultralytics/utils/__init__.py
Labels: enhancement, devops

#15848 Cleanup GitHub Runner for Docker CI
  .github/workflows/docker.yaml
Labels: TODO, enhancement, devops

#15842 Fix typo in docstring in `metrics.py`
  ultralytics/utils/metrics.py
Labels: TODO, documentation

#15838 Add warning message on `distance-calculation.md` docs page
  docs/en/guides/distance-calculation.md
Labels: TODO, documentation, enhancement

#15858 Fix link in README.zh-CN.md
  README.zh-CN.md
Labels: documentation

#15863 Fix loaders.py broken YouTube example URLs
  docs/en/datasets/explorer/explorer.ipynb
  examples/heatmaps.ipynb
  examples/object_counting.ipynb
  examples/object_tracking.ipynb
  examples/tutorial.ipynb
  ultralytics/data/loaders.py
Labels: bug, documentation

#15868 Improve Docs layout issues
  docs/en/datasets/detect/xview.md
  docs/en/guides/streamlit-live-inference.md
Labels: documentation

#15870 Add https://youtu.be/WwXnljc7ZUM to docs
  .github/workflows/docs.yml
  docs/en/guides/streamlit-live-inference.md
Labels: TODO, documentation, enhancement

#15871 `ultralytics 8.2.83` fix SAM2 CLI usage
  docs/en/models/sam-2.md
  docs/en/models/sam.md
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
Labels: bug, enhancement, fixed

#15884 Add retry step to failed Conda tests
  .github/workflows/ci.yaml
Labels: enhancement, devops

#15876 Use AVIF banner images
  docs/overrides/main.html
Labels: documentation, enhancement

#15891 Remove image "?" args
  docs/en/guides/coral-edge-tpu-on-raspberry-pi.md
  docs/en/guides/preprocessing_annotated_data.md
  docs/en/integrations/ibm-watsonx.md
  docs/en/integrations/paddlepaddle.md
  docs/en/models/mobile-sam.md
  docs/en/models/sam-2.md
Labels: documentation, enhancement

#15896 fix HUB download and train
  ultralytics/engine/model.py
  ultralytics/hub/session.py
Labels: HUB, App

#15904 Run Conda tests with aligned tag/version
  .github/workflows/ci.yaml
Labels: enhancement, devops

#15916 Adding missing datasets information to docs
  docs/en/datasets/detect/index.md
  docs/en/datasets/index.md
  docs/en/datasets/segment/index.md
Labels: documentation, enhancement

#15923 Optimize docs author avatars
  .github/workflows/docs.yml
  docs/mkdocs_github_authors.yaml
  pyproject.toml
Labels: documentation, enhancement, dependencies

#15930 Explorer tests require torch>=1.13
  tests/test_explorer.py
Labels: dependencies, Explorer

#15915 Update notebooks: Fix `classes_names` argument with `names`
  examples/heatmaps.ipynb
  examples/object_counting.ipynb
Labels: bug, documentation, enhancement

#15874 Includes warning for enforced `dynamic` during INT8 exports
  ultralytics/engine/exporter.py
Labels: documentation, enhancement, exports

#15932 Update publish.yml
  .github/workflows/publish.yml
Labels: enhancement, dependencies, devops

#15933 Update publish.yml
  .github/workflows/publish.yml
Labels: devops
