Repository ultralytics/ultralytics, pull requests merged in 2024-09, with the labels that each got.

#15917 `ultralytics 8.2.85` YOLOv10 `max_det` arg fix
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/nn/modules/head.py
  ultralytics/utils/ops.py
Labels: bug, enhancement, detect

#14872 Fixed OpenVINO int8 dynamic export and other minor changes
  ultralytics/engine/exporter.py
Labels: TODO, bug, enhancement, exports

#15942 `ultralytics 8.2.86` Windows `torch==2.4.0` patch
  .github/workflows/ci.yaml
  pyproject.toml
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/utils/checks.py
  ultralytics/utils/torch_utils.py
Labels: documentation, dependencies

#15958 Continue on Conda CI error
  .github/workflows/ci.yaml
Labels: enhancement, devops

#15974 Update `test_workflow` to ONNX
  tests/test_python.py
Labels: enhancement, exports

#15978 Fix `torch.cuda.amp.GradScaler` warning
  ultralytics/engine/trainer.py
  ultralytics/utils/torch_utils.py
Labels: enhancement, dependencies

#15971 Fix queue `counts`
  ultralytics/solutions/queue_management.py
Labels: enhancement, track, solutions

#15976 `ultralytics 8.2.87` Ray `shutdown()` workers after tuning
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/utils/tuner.py
Labels: enhancement, devops

#15991 Update `mkdocs-ultralytics-plugin>=0.1.8`
  pyproject.toml
Labels: documentation, dependencies

#15987 Remove Raspberry Pi CI reboot
  .github/workflows/ci.yaml
Labels: devops

#16002 Fix 3 `Objects365.yaml` class names
  ultralytics/cfg/datasets/Objects365.yaml
Labels: documentation, detect

#16003 Skip `test_workflow` on Windows CI
  tests/test_python.py
Labels: enhancement, dependencies, devops

#16020 Update TFLite > LiteRT docs links
  docs/en/integrations/tflite.md
  docs/mkdocs_github_authors.yaml
Labels: TODO, documentation

#16047 Ultralytics Code Refactor https://ultralytics.com/actions
  ultralytics/data/converter.py
  ultralytics/hub/google/__init__.py
  ultralytics/hub/session.py
  ultralytics/models/fastsam/predict.py
  ultralytics/models/sam/modules/blocks.py
  ultralytics/models/sam/modules/decoders.py
  ultralytics/models/sam/modules/encoders.py
  ultralytics/models/sam/modules/sam.py
  ultralytics/models/yolo/classify/predict.py
  ultralytics/nn/modules/activation.py
  ultralytics/utils/__init__.py
  ultralytics/utils/checks.py
Labels: enhancement

#16019 Allows any PyTorch install except `torch==2.4.0` on Windows
  pyproject.toml
  ultralytics/utils/torch_utils.py
Labels: enhancement, dependencies, fixed

#15984 `ultralytics 8.2.88` Update `distance-calculation` to pixels
  docs/en/guides/distance-calculation.md
  ultralytics/__init__.py
  ultralytics/solutions/distance_calculation.py
  ultralytics/utils/plotting.py
Labels: documentation, enhancement, solutions

#16049 Add `not.committed.yet` mkdocs author
  docs/mkdocs_github_authors.yaml
Labels: documentation

#16063 Add https://youtu.be/wWmXKIteRLA to docs
  docs/en/guides/deepstream-nvidia-jetson.md
Labels: TODO, documentation, embedded

#16025 Pass `args` when creating validator for classification
  ultralytics/models/yolo/classify/train.py
Labels: bug, enhancement, classify

#16056 Fix `_predict_augment` and add warning
  ultralytics/nn/tasks.py
Labels: bug, enhancement

#16058 CoreML export: updated nms flag for end2end models
  ultralytics/engine/exporter.py
Labels: TODO, bug, enhancement, exports

#16071 Fix gitignore to format Docs datasets
  .gitignore
  docs/en/datasets/classify/caltech101.md
  docs/en/datasets/classify/cifar100.md
  docs/en/datasets/classify/fashion-mnist.md
  docs/en/datasets/classify/imagenet.md
  docs/en/datasets/classify/imagenette.md
  docs/en/datasets/classify/imagewoof.md
  docs/en/datasets/classify/index.md
  docs/en/datasets/classify/mnist.md
  docs/en/datasets/detect/african-wildlife.md
  docs/en/datasets/detect/argoverse.md
  docs/en/datasets/detect/brain-tumor.md
  docs/en/datasets/detect/coco.md
  docs/en/datasets/detect/coco8.md
  docs/en/datasets/detect/globalwheat2020.md
  docs/en/datasets/detect/index.md
  docs/en/datasets/detect/lvis.md
  docs/en/datasets/detect/objects365.md
  docs/en/datasets/detect/open-images-v7.md
  docs/en/datasets/detect/roboflow-100.md
  docs/en/datasets/detect/sku-110k.md
  docs/en/datasets/detect/visdrone.md
  docs/en/datasets/detect/xview.md
  docs/en/datasets/explorer/api.md
  docs/en/datasets/explorer/dashboard.md
  docs/en/datasets/explorer/explorer.ipynb
  docs/en/datasets/index.md
  docs/en/datasets/obb/dota-v2.md
  docs/en/datasets/obb/dota8.md
  docs/en/datasets/obb/index.md
  docs/en/datasets/pose/coco.md
  docs/en/datasets/pose/coco8-pose.md
  docs/en/datasets/pose/index.md
  docs/en/datasets/pose/tiger-pose.md
  docs/en/datasets/segment/carparts-seg.md
  docs/en/datasets/segment/coco.md
  docs/en/datasets/segment/coco8-seg.md
  docs/en/datasets/segment/index.md
  docs/en/datasets/segment/package-seg.md
  docs/en/datasets/track/index.md
  ultralytics/data/converter.py
Labels: documentation

#16084 Revert to ONNXSlim 0.1.32
  ultralytics/engine/exporter.py
Labels: dependencies, exports

#16078 MPS unified memory cache empty
  ultralytics/engine/trainer.py
Labels: enhancement, devops

#16061 Fix Visualization Arguments docs table
  docs/en/modes/predict.md
  docs/en/usage/cfg.md
Labels: documentation, enhancement

#16085 `ultralytics 8.2.90` Apple MPS unified memory clearing
  ultralytics/__init__.py
Labels: enhancement

#16087 Add YOLOv10 to Raspberry Pi CI
  .github/workflows/ci.yaml
Labels: TODO, detect, devops, embedded

#16156 Update NVIDIA Jetson TensorRT Benchmarks
  docs/en/guides/nvidia-jetson.md
Labels: documentation, embedded, exports

#16086 updated the amount of macros available in the macros folder
  docs/en/guides/analytics.md
  docs/en/guides/distance-calculation.md
  docs/en/guides/heatmaps.md
  docs/en/guides/object-blurring.md
  docs/en/guides/object-counting.md
  docs/en/guides/object-cropping.md
  docs/en/guides/parking-management.md
  docs/en/guides/queue-management.md
  docs/en/guides/speed-estimation.md
  docs/en/guides/workouts-monitoring.md
  docs/en/macros/augmentation-args.md
  docs/en/macros/predict-args.md
  docs/en/macros/track-args.md
  docs/en/macros/train-args.md
  docs/en/macros/validation-args.md
  docs/en/macros/visualization-args.md
  docs/en/modes/predict.md
  docs/en/modes/train.md
  docs/en/modes/val.md
  docs/en/usage/cfg.md
Labels: TODO, documentation, enhancement

#16148 `ultralytics 8.2.91` fix `v10DetectLoss` module rename for YOLOv10
  ultralytics/__init__.py
  ultralytics/nn/tasks.py
Labels: bug, enhancement, detect

#16199 Update merge-main-into-prs.yml
  .github/workflows/docs.yml
  .github/workflows/merge-main-into-prs.yml
Labels: devops

#16220 Distance calculation docs fix
  docs/en/guides/distance-calculation.md
Labels: TODO, documentation, enhancement

#16214 Add https://youtu.be/Tt_35YnQ9uk to docs
  docs/en/guides/model-deployment-practices.md
Labels: TODO, documentation, enhancement

#16161 Update TwoWayTransformer Docs.
  ultralytics/models/sam/modules/transformer.py
Labels: documentation

#16223 Fixed failing greetings CI
  .github/workflows/greetings.yml
Labels: enhancement, devops

#16073 `bbox` and `masks` coloring based on `track-ids`
  ultralytics/engine/results.py
Labels: TODO, enhancement, track, detect

#15961 Non-Deterministic Training Despite deterministic=True
  ultralytics/data/base.py
Labels: TODO, bug, enhancement

#16163 `ultralytics 8.2.92` vertical `line` counter fix
  ultralytics/__init__.py
  ultralytics/solutions/object_counter.py
Labels: enhancement, solutions

#16245 Deprecate .github/workflows/greetings.yml
  .github/workflows/format.yml
  .github/workflows/greetings.yml
Labels: enhancement, devops

#16255 Update format.yml
  .github/workflows/format.yml
Labels: documentation, enhancement, devops

#16253 Fix inaccuracies in OBB docs
  docs/en/datasets/obb/dota-v2.md
  docs/en/datasets/obb/index.md
Labels: documentation, OBB

#16262 Update Tracker Docs
  docs/en/macros/track-args.md
  docs/mkdocs_github_authors.yaml
  mkdocs.yml
Labels: documentation, track

#16264 Add https://youtu.be/GIrFEoR5PoU to docs
  docs/en/guides/model-training-tips.md
Labels: TODO, documentation, enhancement

#16254 Optimize `speed estimation` solution
  docs/en/guides/speed-estimation.md
  ultralytics/solutions/speed_estimation.py
Labels: enhancement, solutions

#16246 Optimize `queue` solution
  docs/en/guides/queue-management.md
  ultralytics/solutions/queue_management.py
Labels: enhancement, solutions

#16269 `ultralytics 8.2.93` new SafeClass and SafeUnpickler classes
  ultralytics/__init__.py
  ultralytics/nn/tasks.py
Labels: enhancement, devops

#16276 Return boxes for SAM prompts inference
  tests/test_cli.py
  ultralytics/models/sam/predict.py
Labels: enhancement, segment

#16287 Docs improvements and redirect fixes
  CONTRIBUTING.md
  README.md
  README.zh-CN.md
  docs/README.md
  docs/coming_soon_template.md
  docs/en/datasets/index.md
  docs/en/datasets/segment/coco8-seg.md
  docs/en/datasets/segment/package-seg.md
  docs/en/guides/object-blurring.md
  docs/en/guides/object-counting.md
  docs/en/guides/optimizing-openvino-latency-vs-throughput-modes.md
  docs/en/guides/raspberry-pi.md
  docs/en/guides/security-alarm-system.md
  docs/en/guides/streamlit-live-inference.md
  docs/en/guides/triton-inference-server.md
  docs/en/help/contributing.md
  docs/en/hub/datasets.md
  docs/en/hub/index.md
  docs/en/hub/inference-api.md
  docs/en/hub/integrations.md
  docs/en/hub/models.md
  docs/en/hub/quickstart.md
  docs/en/integrations/edge-tpu.md
  docs/en/modes/export.md
  docs/en/modes/index.md
  docs/en/modes/train.md
  docs/en/modes/val.md
  docs/en/tasks/classify.md
  docs/en/tasks/detect.md
  docs/en/tasks/obb.md
  docs/en/tasks/pose.md
  docs/en/tasks/segment.md
  docs/en/usage/cli.md
  docs/en/yolov5/tutorials/train_custom_data.md
  examples/README.md
  pyproject.toml
  ultralytics/cfg/models/README.md
  ultralytics/trackers/README.md
Labels: documentation

#16280 Fix `mps.empty_cache()` for macOS without MPS
  ultralytics/engine/trainer.py
Labels: bug, enhancement

#16242 Add color palette tables to docs
  ultralytics/utils/plotting.py
Labels: documentation, enhancement

#15895 Intel Core Ultra benchmarks
  docs/en/integrations/openvino.md
Labels: documentation, enhancement, exports

#16272 `ultralytics 8.2.94` Apple MPS train memory display
  .github/workflows/format.yml
  .github/workflows/publish.yml
  ultralytics/__init__.py
  ultralytics/engine/trainer.py
Labels: enhancement

#16294 Fix `IS_TMP_WRITEABLE` order of operations
  tests/__init__.py
  tests/test_python.py
Labels: enhancement, detect

#16312 Fix dependabot in mkdocs_github_authors.yaml
  docs/mkdocs_github_authors.yaml
Labels: documentation, devops

#16313 Threaded inference docs improvements
  README.md
  README.zh-CN.md
  docs/en/modes/predict.md
  docs/en/modes/track.md
  docs/en/yolov5/quickstart_tutorial.md
Labels: documentation, enhancement, track

#16314 Update track.md
  docs/en/modes/track.md
Labels: documentation, track

#16306 Disable FP16 val on AMP fail and improve AMP checks
  ultralytics/engine/validator.py
  ultralytics/utils/checks.py
Labels: bug, enhancement, devops

#16288 Optimize `parking management` solution
  docs/en/guides/parking-management.md
  ultralytics/solutions/parking_management.py
Labels: enhancement, solutions

#16326 Enable Docs auto-fixes on repo branches
  .github/workflows/docs.yml
  docs/en/reference/nn/tasks.md
Labels: enhancement, exports

#16334 Update Multi-Stream predict docs
  docs/en/modes/predict.md
Labels: documentation, enhancement

#16333 Use `trainer.amp` to determine FP16 validation
  ultralytics/engine/validator.py
Labels: enhancement

#16267 `ultralytics 8.2.96` new `results[0].to_df` Pandas, XML and CSV methods
  docs/en/hub/inference-api.md
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/engine/results.py
Labels: enhancement, detect

#16338 Docs banner for https://ultralytics.com/yolo-vision
  docs/overrides/main.html
  docs/overrides/stylesheets/style.css
Labels: documentation, enhancement

#16341 Add https://youtu.be/c5eFrt2KuzY to docs
  docs/en/integrations/paddlepaddle.md
Labels: TODO, documentation, enhancement, exports

#16347 `ultralytics 8.2.97` robust HUB model downloads
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/engine/model.py
  ultralytics/hub/session.py
Labels: enhancement, HUB

#16352 Cleanup session.py
  ultralytics/hub/session.py
Labels: enhancement

#16371 Remove pandas from exports table
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
  ultralytics/utils/benchmarks.py
Labels: enhancement, exports

#16373 New `PERSISTENT_CACHE`
  docs/en/reference/utils/__init__.md
  ultralytics/utils/__init__.py
  ultralytics/utils/torch_utils.py
Labels: enhancement

#16382 Remove extra `get_cpu_info` return
  ultralytics/utils/torch_utils.py
Labels: enhancement

#16392 Add https://youtu.be/5XYdm5CYODA to docs
  docs/en/tasks/obb.md
Labels: TODO, documentation, OBB

#16405 Remove `half` when profiling ONNX models
  ultralytics/utils/benchmarks.py
Labels: enhancement, exports

#16417 Update `simple-utilities.md`
  docs/en/usage/simple-utilities.md
Labels: documentation, detect

#16420 Update OpenVINO CI for Python 3.12
  tests/test_exports.py
  ultralytics/utils/benchmarks.py
Labels: devops, exports

#16421 Update TOML project URLs
  pyproject.toml
Labels: documentation, enhancement

#16423 Update pyproject.toml authors and maintainers fields
  pyproject.toml
Labels: documentation

#16426 New `JSONDict` class
  docs/en/reference/utils/__init__.md
  ultralytics/utils/__init__.py
Labels: enhancement

#16427 `ultralytics 8.2.99` faster `JSONDict` settings
  docs/en/quickstart.md
  tests/test_integrations.py
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/data/utils.py
  ultralytics/hub/__init__.py
  ultralytics/utils/__init__.py
Labels: enhancement, devops

#16435 Default `simplify=True`
  docs/en/macros/export-args.md
  ultralytics/cfg/default.yaml
  ultralytics/utils/benchmarks.py
Labels: enhancement, exports

#16437 `ultralytics 8.2.100` new YOLOv8-OBB object counting
  ultralytics/__init__.py
  ultralytics/solutions/object_counter.py
Labels: enhancement, OBB, track, solutions

#16462 Docs: Inference API Updates
  docs/en/hub/inference-api.md
  docs/mkdocs_github_authors.yaml
Labels: documentation

#16482 Add https://youtu.be/5XYdm5CYODA to docs
  docs/en/guides/analytics.md
Labels: TODO, documentation

#16488 `ultralytics 8.2.101` allow HUB public model downloads
  pyproject.toml
  ultralytics/__init__.py
  ultralytics/engine/model.py
  ultralytics/hub/__init__.py
  ultralytics/hub/session.py
Labels: enhancement, HUB

#16493 Ultralytics Code Refactor https://ultralytics.com/actions
  docs/en/guides/data-collection-and-annotation.md
  docs/en/guides/steps-of-a-cv-project.md
  docs/en/integrations/weights-biases.md
  ultralytics/models/sam/modules/sam.py
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/parking_management.py
Labels: documentation, enhancement

#16466 Removed duplicate CUBLAS_WORKSPACE_CONFIG var
  ultralytics/utils/__init__.py
Labels: enhancement, dependencies

#16489 `ultralytics 8.2.102` new Hand-Keypoints Pose Estimation Dataset
  docs/en/datasets/index.md
  docs/en/datasets/pose/hand-keypoints.md
  docs/en/datasets/pose/index.md
  ultralytics/__init__.py
  ultralytics/cfg/datasets/hand-keypoints.yaml
Labels: documentation, enhancement, pose

#16515 Update `mkdocs.yml` with Hand Keypoints link
  mkdocs.yml
Labels: documentation, enhancement, pose

#16522 Update JSONDict for PosixPath to String
  ultralytics/utils/__init__.py
Labels: enhancement, devops

#16470 Removing cpu-info persistence for Docker images
  docker/Dockerfile
  docker/Dockerfile-arm64
  docker/Dockerfile-conda
  docker/Dockerfile-cpu
  docker/Dockerfile-jetson-jetpack4
  docker/Dockerfile-jetson-jetpack5
  docker/Dockerfile-jetson-jetpack6
  docker/Dockerfile-python
Labels: enhancement, dependencies

#16523 `ultralytics 8.2.103` Windows Benchmarks CI
  .github/workflows/ci.yaml
  ultralytics/__init__.py
  ultralytics/utils/benchmarks.py
Labels: devops

#16527 Update test_exports.py
  tests/test_exports.py
Labels: enhancement, exports

#16528 Fix `hand-keypoints.yaml` image counts
  ultralytics/cfg/datasets/hand-keypoints.yaml
Labels: documentation, pose

#16529 Update Dockerfile-python
  docker/Dockerfile-python
Labels: enhancement, dependencies, exports

#16535 Use `apt-get` in Dockerfiles
  docker/Dockerfile
  docker/Dockerfile-arm64
  docker/Dockerfile-conda
  docker/Dockerfile-cpu
  docker/Dockerfile-jetson-jetpack4
  docker/Dockerfile-jetson-jetpack5
  docker/Dockerfile-jetson-jetpack6
  docker/Dockerfile-python
Labels: enhancement, devops

#16542 Fix YOLO11 YouTube link
  README.md
  README.zh-CN.md
  docs/en/models/yolo11.md
  docs/en/models/yolov6.md
  docs/en/yolov5/environments/google_cloud_quickstart_tutorial.md
  examples/heatmaps.ipynb
  examples/hub.ipynb
  examples/object_counting.ipynb
  examples/object_tracking.ipynb
  examples/tutorial.ipynb
Labels: documentation, enhancement

#16543 Update YOLO11 Docs page
  docs/en/index.md
  docs/en/models/yolo11.md
  docs/en/quickstart.md
  pyproject.toml
Labels: documentation

#16561 Default to YOLO11 models
  ultralytics/cfg/__init__.py
Labels: segment, detect, classify

#16564 Update Docker deploy to YOLO11 benchmarks
  .github/workflows/docker.yaml
Labels: enhancement, devops, exports

#16560 `ultralytics 8.3.1` update AMP checks for YOLO11n
  ultralytics/__init__.py
  ultralytics/utils/checks.py
Labels: enhancement, devops

#16573 Enable `result.show()` for Jupyter notebooks
  ultralytics/utils/plotting.py
Labels: documentation, enhancement

#16575 Fix button text in `docs/home` to match link
  docs/en/index.md
Labels: documentation
