Repository ultralytics/ultralytics, pull requests merged in 2024-11, with the labels that each got.

#17292 Skip MNN export for Raspberry Pi and NVIDIA Jetson
  tests/test_exports.py
  ultralytics/engine/exporter.py
Labels: enhancement, embedded, exports

#17296 Benchmark graph fix
  docs/en/modes/benchmark.md
  docs/overrides/javascript/extra.js
Labels: documentation, enhancement

#17298 `ultralytics 8.3.27` HUB timed training fix
  docs/mkdocs_github_authors.yaml
  ultralytics/__init__.py
  ultralytics/engine/trainer.py
  ultralytics/utils/checks.py
Labels: dependencies, HUB

#17308 Fix MNN Raspberry Pi benchmark attempt
  ultralytics/utils/benchmarks.py
Labels: enhancement, exports

#17314 Fix mkdocs_github_authors.yaml
  docs/mkdocs_github_authors.yaml
Labels: documentation

#17320 Update mkdocs_github_authors.yaml
  docs/mkdocs_github_authors.yaml
Labels: documentation

#17317 Refactor TFLite example. Support FP32, Fp16, INT8 models
  examples/README.md
  examples/YOLOv8-OpenCV-int8-tflite-Python/README.md
  examples/YOLOv8-OpenCV-int8-tflite-Python/main.py
  examples/YOLOv8-TFLite-Python/README.md
  examples/YOLOv8-TFLite-Python/main.py
Labels: enhancement, detect, exports

#17311 [Example] YOLO-Series(v5-11) ONNXRuntime Rust
  examples/README.md
  examples/YOLO-Series-ONNXRuntime-Rust/Cargo.toml
  examples/YOLO-Series-ONNXRuntime-Rust/README.md
  examples/YOLO-Series-ONNXRuntime-Rust/src/main.rs
  examples/YOLOv8-ONNXRuntime-Rust/Cargo.toml
  examples/YOLOv8-ONNXRuntime-Rust/README.md
  examples/YOLOv8-ONNXRuntime-Rust/src/lib.rs
  examples/YOLOv8-ONNXRuntime-Rust/src/model.rs
Labels: enhancement, dependencies, exports

#17321 Fix Docker badges
  README.md
  README.zh-CN.md
  docs/en/index.md
Labels: documentation

#17318 Add ultralytics models publication notice in citations section
  docs/en/models/yolo11.md
  docs/en/models/yolov5.md
  docs/en/models/yolov8.md
Labels: documentation, enhancement

#17315 Optimize Auto-Annotation with all args
  docs/en/models/sam-2.md
  docs/en/models/sam.md
  ultralytics/data/annotator.py
Labels: documentation, enhancement, detect

#17071 New JupyterLab Dockerfile
  .github/workflows/docker.yaml
  docker/Dockerfile-jupyter
Labels: enhancement, devops

#17324 Update `overlap_mask` description.
  docs/en/macros/train-args.md
  ultralytics/cfg/default.yaml
Labels: documentation, segment

#17330 Generalized M1/M2 references to "Apple silicon" in train.md for broader inclusion
  docs/en/modes/train.md
Labels: documentation

#17297 Add Albumentations Integrations Docs Page
  docs/en/integrations/albumentations.md
  docs/en/integrations/index.md
  mkdocs.yml
Labels: TODO, documentation, enhancement

#17352 Fix error on TensorRT export with float `workspace` value
  ultralytics/engine/exporter.py
Labels: fixed, exports

#17360 Added Error for TFLite int8 end2end model export
  ultralytics/engine/exporter.py
Labels: enhancement, exports

#17332 Update kfold-cross-validation.md
  docs/en/guides/kfold-cross-validation.md
Labels: documentation

#17233 `ultralytics 8.3.28` new Solutions CLI commands
  .github/workflows/ci.yaml
  .github/workflows/docs.yml
  docs/en/guides/analytics.md
  docs/en/guides/heatmaps.md
  docs/en/guides/object-counting.md
  docs/en/guides/queue-management.md
  docs/en/guides/speed-estimation.md
  docs/en/guides/workouts-monitoring.md
  docs/en/integrations/albumentations.md
  docs/en/reference/cfg/__init__.md
  docs/en/solutions/index.md
  docs/mkdocs_github_authors.yaml
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/solutions/ai_gym.py
  ultralytics/solutions/solutions.py
  ultralytics/utils/__init__.py
Labels: enhancement, solutions

#17386 Docs and CI updates
  .github/workflows/ci.yaml
  docs/en/guides/workouts-monitoring.md
Labels: bug, documentation, fixed

#17391 Fix `model.end2end` assert
  ultralytics/engine/exporter.py
Labels: fixed, exports

#15919 Add support for the Pytorch OpenCL backend
  ultralytics/engine/trainer.py
  ultralytics/engine/validator.py
  ultralytics/utils/torch_utils.py
Labels: enhancement, dependencies

#17395 Add environment to publish.yml
  .github/workflows/docs.yml
  .github/workflows/publish.yml
Labels: enhancement, devops

#17399 Fix PyPI downloads links
  README.md
  README.zh-CN.md
  docs/README.md
  docs/en/index.md
  docs/en/models/yolo11.md
  docs/en/models/yolov5.md
  docs/en/models/yolov8.md
  docs/en/quickstart.md
  docs/overrides/javascript/extra.js
  docs/overrides/javascript/giscus.js
  examples/heatmaps.ipynb
  examples/hub.ipynb
  examples/object_counting.ipynb
  examples/object_tracking.ipynb
  examples/tutorial.ipynb
  ultralytics/engine/exporter.py
  ultralytics/engine/trainer.py
  ultralytics/solutions/solutions.py
  ultralytics/utils/callbacks/comet.py
Labels: documentation, enhancement

#17400 Jupyter Docker Image, allow connection
  docker/Dockerfile-jupyter
Labels: enhancement, devops

#17401 Fix duplicated annotations by `yolo_bbox2segment`
  ultralytics/data/converter.py
Labels: enhancement, fixed, segment

#17409 Add device selection for `yolo_bbox2segment`
  ultralytics/data/converter.py
Labels: enhancement, segment

#17411 Update validation-args.md
  docs/en/macros/validation-args.md
Labels: documentation, enhancement

#17419 Use new Ultralytics Retry action
  .github/workflows/docker.yaml
  .github/workflows/links.yml
Labels: enhancement, devops

#17402 Changed model.names return type hint from list to dict[int, str]
  ultralytics/engine/model.py
Labels: enhancement

#17424 Match Docs caption to video thumbnail text
  docs/en/guides/object-counting.md
Labels: documentation, enhancement

#17384 Fix `conf` overwrite in results.py
  ultralytics/engine/results.py
Labels: bug, enhancement

#17416 Fix Ray Tune error
  ultralytics/utils/callbacks/raytune.py
Labels: bug, enhancement

#17452 Create sony-imx500.md standalone Docs page
  docs/en/integrations/albumentations.md
  docs/en/integrations/sony-imx500.md
Labels: documentation, embedded, exports

#17466 Update bug-report-template.yml to prompt for `collect_system_info`
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: documentation

#17463 Add sony-imx500.md to mkdocs.yml
  .github/ISSUE_TEMPLATE/bug-report.yml
  mkdocs.yml
Labels: documentation

#14878 `ultralytics 8.3.29` Sony IMX500 export
  .gitignore
  docs/en/integrations/index.md
  docs/en/integrations/sony-imx500.md
  docs/en/macros/export-table.md
  docs/en/reference/utils/torch_utils.md
  docs/mkdocs_github_authors.yaml
  mkdocs.yml
  tests/test_exports.py
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
  ultralytics/nn/modules/block.py
  ultralytics/nn/modules/head.py
  ultralytics/utils/benchmarks.py
  ultralytics/utils/tal.py
  ultralytics/utils/torch_utils.py
Labels: TODO, enhancement, detect, exports

#17479 Fix Docker `jupyter` image naming
  .github/workflows/docker.yaml
Labels: TODO, devops

#17481 Include FPs for images with no labels in confusion matrix
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/models/yolo/segment/val.py
Labels: segment, detect, pose

#17493 Simplify Solutions Docs code examples
  docs/en/guides/analytics.md
  docs/en/guides/distance-calculation.md
  docs/en/guides/heatmaps.md
  docs/en/guides/object-counting.md
  docs/en/guides/queue-management.md
  docs/en/guides/speed-estimation.md
  docs/en/guides/streamlit-live-inference.md
  docs/en/guides/workouts-monitoring.md
Labels: TODO, documentation, enhancement, solutions

#17519 Fix broken Jetson doc URL
  docs/en/guides/nvidia-jetson.md
Labels: documentation

#17525 Update models.md
  docs/en/hub/models.md
Labels: documentation

#17518 Add return check for 'yolo solutions help'
  ultralytics/cfg/__init__.py
  ultralytics/solutions/analytics.py
Labels: TODO, bug, solutions

#17491 Update sony-imx500.md
  docs/en/integrations/sony-imx500.md
Labels: documentation, enhancement

#17499 Fix `file_name` in `save_crop`
  ultralytics/engine/results.py
Labels: enhancement, fixed

#17515 `ultralytics 8.3.30` run TAL on CPU if `torch.OutOfMemoryError`
  ultralytics/__init__.py
  ultralytics/utils/tal.py
Labels: enhancement, devops

#17257 Remove `verbose` arg from train docs.
  docs/en/macros/train-args.md
Labels: documentation

#17514 `ultralytics 8.3.31` add `max_num_obj` factor for `AutoBatch`
  ultralytics/__init__.py
  ultralytics/engine/trainer.py
  ultralytics/models/yolo/detect/train.py
  ultralytics/utils/autobatch.py
  ultralytics/utils/tal.py
  ultralytics/utils/torch_utils.py
Labels: enhancement

#17576 Update links.yml to 900s delay
  .github/workflows/links.yml
Labels: devops

#17544 Fix: wandb reporting error if no positive examples
  ultralytics/utils/callbacks/wb.py
Labels: bug, enhancement

#17556 `ultralytics 8.3.32` New Dog-Pose dataset
  docs/en/datasets/index.md
  docs/en/datasets/pose/dog-pose.md
  docs/en/datasets/pose/index.md
  mkdocs.yml
  ultralytics/__init__.py
  ultralytics/cfg/datasets/dog-pose.yaml
Labels: documentation, pose

#17587 Update `retina_masks` description
  docs/en/macros/predict-args.md
Labels: documentation

#17583 Enable MNN on RPi and Jetson
  ultralytics/engine/exporter.py
  ultralytics/utils/benchmarks.py
Labels: TODO, embedded, exports

#17550 Update `device` argument description for benchmark
  docs/en/modes/benchmark.md
Labels: documentation

#17607 `ultralytics 8.3.33` Solutions counter direction fix
  ultralytics/__init__.py
  ultralytics/solutions/object_counter.py
Labels: enhancement, solutions

#17630 Fix v8_transforms docstring example
  ultralytics/data/augment.py
Labels: documentation, enhancement

#17631 Update Slack usage to v2
  .github/workflows/ci.yaml
  .github/workflows/docker.yaml
  .github/workflows/publish.yml
Labels: devops

#17633 Add `fraction`, `single_cls` and `classes` to `RTDETRDataset`
  ultralytics/models/rtdetr/train.py
Labels: enhancement, detect

#17634 Heatmaps bug fix
  ultralytics/solutions/heatmap.py
  ultralytics/solutions/object_counter.py
Labels: TODO, bug, solutions

#17628 `ultralytics 8.3.34` FastSAM non-detection fix
  ultralytics/__init__.py
  ultralytics/models/fastsam/predict.py
Labels: enhancement, segment

#17635 Add RTDETRv2 in `benchmarks.md` chart 📈
  docs/en/modes/benchmark.md
  docs/overrides/javascript/extra.js
Labels: TODO, documentation, enhancement

#17665 Update extra.js
  .github/workflows/publish.yml
  .github/workflows/stale.yml
  docs/overrides/javascript/extra.js
  docs/overrides/javascript/giscus.js
Labels: documentation, dependencies

#17670 Update Dockerfile-cpu to `ubuntu:latest`
  docker/Dockerfile
  docker/Dockerfile-cpu
  docker/Dockerfile-runner
Labels: dependencies, devops

#17669 Docs Search Bar improvements
  docs/overrides/javascript/extra.js
  docs/overrides/stylesheets/style.css
  mkdocs.yml
Labels: documentation, enhancement

#17683 Add missing import to Raytune docs
  docs/en/integrations/ray-tune.md
Labels: documentation

#17687 `ultralytics 8.3.35` enable `auto` letterbox if model is `dynamic`
  ultralytics/__init__.py
  ultralytics/engine/predictor.py
Labels: enhancement

#17702 Fix `imx500` YOLO support in export table
  docs/en/macros/export-table.md
Labels: TODO, documentation

#17701 Ultralytics Refactor https://ultralytics.com/actions
  README.md
  README.zh-CN.md
  docs/en/hub/models.md
  docs/en/index.md
  docs/overrides/javascript/extra.js
  ultralytics/nn/tasks.py
  ultralytics/solutions/object_counter.py
  ultralytics/utils/torch_utils.py
Labels: enhancement

#17705 Update extra.js
  .github/workflows/docs.yml
  docs/overrides/javascript/extra.js
Labels: documentation, enhancement

#17706 Minify-html fix
  .github/workflows/docs.yml
  docs/build_docs.py
Labels: documentation, enhancement, dependencies

#17707 `extra.js` dark mode fix
  docs/overrides/javascript/extra.js
Labels: documentation, enhancement

#17700 Benchmarks graph Javascript fix
  .github/workflows/docs.yml
  docs/en/modes/benchmark.md
  docs/overrides/javascript/benchmark.js
  docs/overrides/javascript/extra.js
Labels: documentation, enhancement

#17715 Standardize default region points
  tests/test_solutions.py
  ultralytics/cfg/solutions/default.yaml
  ultralytics/solutions/solutions.py
Labels: enhancement, detect

#16600 `ultralytics 8.3.36` unpin OpenVINO ARM install version
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
Labels: TODO, enhancement, dependencies, exports

#17728 Fix labels padding for Letterbox with `center=False`
  ultralytics/data/augment.py
Labels: bug, enhancement

#17722 Add https://youtu.be/c-S5M36XWmg & https://youtu.be/fd6u1TW_AGY to docs
  docs/en/datasets/pose/hand-keypoints.md
  docs/en/usage/simple-utilities.md
Labels: TODO, documentation

#17739 Update `coco-seg.yaml` to `coco.yaml`
  README.md
  README.zh-CN.md
  docs/en/datasets/segment/coco.md
  docs/en/tasks/segment.md
Labels: documentation, segment

#17721 Standardize default region points in docs
  docs/en/guides/heatmaps.md
  docs/en/guides/object-counting.md
  docs/en/guides/queue-management.md
  docs/en/guides/region-counting.md
  docs/en/guides/speed-estimation.md
  ultralytics/cfg/__init__.py
Labels: documentation

#17754 Enable model.eval() usage for `YOLO` class
  ultralytics/engine/model.py
Labels: enhancement

#17748 `ultralytics 8.3.37` TensorRT auto-workspace size
  docs/en/integrations/tensorrt.md
  docs/en/macros/export-args.md
  ultralytics/__init__.py
  ultralytics/cfg/default.yaml
  ultralytics/engine/exporter.py
Labels: bug, documentation, enhancement, fixed, exports

#17772 Delete .github/workflows/codeql.yaml
  .github/workflows/codeql.yaml
Labels: devops

#17086 Fix `RepC3` module for RT-DETR models
  ultralytics/nn/modules/block.py
Labels: enhancement

#17770 Improve `is_jetson` to support more Jetson devices
  ultralytics/utils/__init__.py
Labels: enhancement, embedded

#17779 Fix CI.md CodeQL badges
  docs/en/help/CI.md
Labels: documentation

#17795 Convert frames to RGB before SAHI inference
  examples/YOLOv8-SAHI-Inference-Video/yolov8_sahi.py
Labels: detect

#17797 Fix parking points annotator for macOS
  ultralytics/solutions/parking_management.py
Labels: bug

#17714 Fix `forward_fuse` comment
  ultralytics/nn/modules/conv.py
Labels: enhancement

#14851 `ultralytics 8.3.38` SAM 2 video inference
  docs/en/models/sam-2.md
  docs/en/reference/models/sam/predict.md
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/data/augment.py
  ultralytics/data/loaders.py
  ultralytics/models/sam/__init__.py
  ultralytics/models/sam/model.py
  ultralytics/models/sam/modules/sam.py
  ultralytics/models/sam/predict.py
  ultralytics/trackers/basetrack.py
  ultralytics/trackers/utils/matching.py
  ultralytics/utils/loss.py
  ultralytics/utils/metrics.py
  ultralytics/utils/ops.py
  ultralytics/utils/plotting.py
Labels: TODO, enhancement, segment

#17810 Fix missing labels when all segment points are out of bounds
  ultralytics/utils/ops.py
Labels: enhancement, segment

#17742 New Solutions sweep counting annotator
  docs/en/usage/simple-utilities.md
  ultralytics/utils/plotting.py
Labels: TODO, enhancement, segment, detect

#17816 Improved Docs minify
  .github/workflows/docs.yml
  docs/build_docs.py
Labels: documentation, enhancement, dependencies

#17831 Revert Docs minify attempt
  .github/workflows/docs.yml
  docs/build_docs.py
  docs/overrides/assets/favicon.ico
  mkdocs.yml
Labels: documentation, enhancement, dependencies

#17814 Update format.yml Discord and Kaggle links
  .github/workflows/format.yml
Labels: documentation, enhancement

#17832 Update contributing.md with open-sourcing guide
  docs/en/help/contributing.md
Labels: documentation, enhancement

#17834 Fix YOLO11 usage
  docs/en/integrations/albumentations.md
  examples/YOLO-Series-ONNXRuntime-Rust/README.md
Labels: documentation

#17833 Update Tasks Banner in README.md
  README.md
  README.zh-CN.md
Labels: documentation, enhancement

#17835 Fix region-counting indents
  docs/en/guides/region-counting.md
  ultralytics/cfg/__init__.py
  ultralytics/models/yolo/detect/train.py
  ultralytics/utils/torch_utils.py
Labels: documentation, enhancement

#17843 Update Tasks banner spacing
  README.md
  README.zh-CN.md
Labels: documentation, enhancement

#17813 Add functions descriptions in `plotting.py`
  ultralytics/utils/plotting.py
Labels: documentation

#17844 Remove Docs Tasks banner linebreak
  docs/en/tasks/index.md
Labels: documentation, enhancement

#17863 Add https://youtu.be/-aYO-6VaDrw and https://youtu.be/M7xWw4Iodhg to docs
  docs/en/datasets/segment/carparts-seg.md
  docs/en/guides/model-evaluation-insights.md
  docs/en/guides/region-counting.md
  docs/en/models/sam-2.md
  docs/en/modes/benchmark.md
  docs/en/tasks/pose.md
Labels: documentation, enhancement

#17856 Add `classes` to train arguments
  docs/en/macros/train-args.md
Labels: enhancement, detect

#17864 Add BGR to RGB conversion in LibTorch example
  examples/YOLOv8-LibTorch-CPP-Inference/main.cc
Labels: enhancement, detect

#17805 `__getattr__` support to access YOLO attributes via Model class
  ultralytics/engine/model.py
Labels: enhancement

#17851 `ultralytics 8.3.39` fix classification validation loss scaling
  ultralytics/__init__.py
  ultralytics/models/yolo/classify/predict.py
  ultralytics/nn/modules/head.py
Labels: bug, fixed, classify
