Repository ultralytics/ultralytics, pull requests merged in 2024-10, with the labels that each got.

#16574 Remove `dill` package from Ultralytics
  ultralytics/engine/model.py
  ultralytics/models/sam/build.py
  ultralytics/utils/files.py
  ultralytics/utils/patches.py
  ultralytics/utils/torch_utils.py
Labels: enhancement, dependencies

#16583 `ultralytics 8.3.2` fix AMP checks with `imgsz=256`
  tests/test_cuda.py
  ultralytics/__init__.py
  ultralytics/utils/__init__.py
  ultralytics/utils/checks.py
Labels: enhancement, detect

#16588 Fix zero-mask plotting bug
  ultralytics/utils/plotting.py
Labels: bug, enhancement, segment

#16593 YOLO11 Tasks, Modes, Usage, Macros and Solutions Updates
  docs/en/datasets/classify/caltech256.md
  docs/en/datasets/classify/cifar10.md
  docs/en/datasets/classify/fashion-mnist.md
  docs/en/datasets/detect/open-images-v7.md
  docs/en/datasets/segment/carparts-seg.md
  docs/en/guides/security-alarm-system.md
  docs/en/guides/streamlit-live-inference.md
  docs/en/guides/yolo-performance-metrics.md
  docs/en/help/FAQ.md
  docs/en/help/index.md
  docs/en/index.md
  docs/en/macros/export-table.md
  docs/en/modes/benchmark.md
  docs/en/modes/export.md
  docs/en/modes/predict.md
  docs/en/modes/track.md
  docs/en/modes/train.md
  docs/en/modes/val.md
  docs/en/solutions/index.md
  docs/en/tasks/classify.md
  docs/en/tasks/detect.md
  docs/en/tasks/index.md
  docs/en/tasks/obb.md
  docs/en/tasks/pose.md
  docs/en/tasks/segment.md
  docs/en/usage/callbacks.md
  docs/en/usage/cfg.md
  docs/en/usage/cli.md
  docs/en/usage/engine.md
  docs/en/usage/python.md
  docs/en/usage/simple-utilities.md
Labels: documentation

#16604 Fix Docs links
  docs/en/datasets/pose/coco.md
  docs/en/tasks/index.md
Labels: documentation

#16608 Update YOLO11 notebooks
  examples/heatmaps.ipynb
  examples/hub.ipynb
  examples/object_counting.ipynb
  examples/object_tracking.ipynb
  examples/tutorial.ipynb
Labels: documentation, enhancement

#16609 Colab notebook update
  examples/tutorial.ipynb
Labels: documentation

#16610 Update Settings
  ultralytics/hub/utils.py
  ultralytics/utils/__init__.py
Labels: documentation, enhancement

#16598 Add YOLO11 macros tables
  docs/en/datasets/classify/imagenet.md
  docs/en/datasets/detect/coco.md
  docs/en/datasets/pose/coco.md
  docs/en/datasets/segment/coco.md
  docs/en/macros/yolo-cls-perf.md
  docs/en/macros/yolo-det-perf.md
  docs/en/macros/yolo-obb-perf.md
  docs/en/macros/yolo-pose-perf.md
  docs/en/macros/yolo-seg-perf.md
  docs/en/models/yolo11.md
  docs/en/tasks/classify.md
  docs/en/tasks/detect.md
  docs/en/tasks/obb.md
  docs/en/tasks/pose.md
  docs/en/tasks/segment.md
Labels: documentation, detect, classify

#16590 `ultralytics 8.3.3` update Streamlit app to YOLO11
  ultralytics/__init__.py
  ultralytics/solutions/streamlit_inference.py
  ultralytics/utils/plotting.py
Labels: enhancement, App

#16620 Fix Raspberry Pi CI
  .github/workflows/ci.yaml
Labels: detect, devops

#16622 Update scheduled CI to 08:00 UTC
  .github/workflows/ci.yaml
  ultralytics/utils/__init__.py
Labels: devops

#16626 Add https://youtu.be/yXQPLMrNX2s to docs
  docs/en/models/mobile-sam.md
  docs/en/models/sam-2.md
Labels: documentation, enhancement

#16627 Fix overridden train_args when close_mosaic
  ultralytics/engine/trainer.py
Labels: enhancement

#16632 Add contributor name for example: YOLOv8 OpenVINO CPP Inference
  examples/README.md
Labels: documentation, exports

#16625 Auto-correct for export formats
  ultralytics/engine/exporter.py
Labels: enhancement, exports

#16631 Empty index `[0,,1]` robust device selection
  ultralytics/utils/torch_utils.py
Labels: enhancement

#16638 Improve `scikit-learn` support for exports
  pyproject.toml
Labels: enhancement, dependencies, exports

#16637 Fixing predict docs
  docs/en/macros/predict-args.md
  ultralytics/engine/exporter.py
Labels: documentation

#16642 SAM: Fix labels not being used in predict mode.
  ultralytics/models/sam/predict.py
Labels: bug, enhancement, detect

#16646 Minor fix in docs for `python` admonition and code blocks
  docs/en/guides/isolating-segmentation-objects.md
  docs/en/hub/datasets.md
  docs/en/integrations/tensorrt.md
  docs/en/usage/python.md
Labels: documentation

#16654 Update image URLs in `mobile-sam.md` and `sam-2.md`.
  docs/en/models/mobile-sam.md
  docs/en/models/sam-2.md
Labels: documentation, enhancement

#16647 Replace YOLO11-seg table with macro
  docs/en/datasets/detect/coco.md
  docs/en/datasets/segment/coco.md
Labels: documentation, enhancement, detect

#16655 `ultralytics 8.3.4` unpin `numpy<2.0.0`
  pyproject.toml
  ultralytics/__init__.py
Labels: enhancement, dependencies

#16663 Update Docs extra.js
  docs/overrides/javascript/extra.js
  docs/overrides/stylesheets/style.css
Labels: documentation, enhancement

#16669 Add combined model plot to Docs
  docs/en/models/index.md
  docs/overrides/javascript/extra.js
Labels: documentation, enhancement

#16667 Remove unused arguments in Ultralytics `heatmaps`
  docs/en/guides/heatmaps.md
  ultralytics/solutions/heatmap.py
Labels: documentation, enhancement, solutions

#16685 Add https://youtu.be/-JXwa-WlkU8 to docs
  docs/en/models/yolo11.md
Labels: documentation, detect

#16686 Clarify `stream_buffer` argument docs
  docs/en/integrations/vscode.md
  docs/en/macros/predict-args.md
Labels: documentation

#16674 Fix `NEW` labeling for more consistency in docs
  docs/en/datasets/index.md
  docs/en/index.md
  docs/en/models/index.md
  mkdocs.yml
Labels: documentation

#16691 Update MkDocs extra.js
  docs/overrides/javascript/extra.js
Labels: documentation, enhancement

#16698 Zero mAP warning on YAML val
  ultralytics/engine/validator.py
Labels: documentation, enhancement

#16671 Introduced `BaseSolution` class for Ultralytics solutions
  docs/en/guides/object-counting.md
  docs/en/reference/solutions/solutions.md
  tests/test_solutions.py
  ultralytics/cfg/solutions/default.yaml
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/solutions.py
Labels: solutions, devops

#16697 Fix and add missing infos about available CLI `TASK` commands in docs and code comments
  docs/en/usage/cfg.md
  ultralytics/cfg/default.yaml
  ultralytics/data/utils.py
  ultralytics/utils/__init__.py
Labels: documentation, enhancement, OBB

#16699 Fix validator model=None
  ultralytics/engine/validator.py
Labels: bug, fixed

#16700 Update docker.yaml to notify on failure once
  .github/workflows/docker.yaml
Labels: devops

#16696 `ultralytics 8.3.5` add `cache=disk` space and writable checks
  ultralytics/__init__.py
  ultralytics/data/base.py
Labels: enhancement

#16709 Update PyPI to trusted publisher
  .github/workflows/publish.yml
  pyproject.toml
Labels: enhancement, dependencies, devops

#16706 Update `workouts_monitoring` solution
  docs/en/guides/object-counting.md
  docs/en/guides/workouts-monitoring.md
  tests/test_solutions.py
  ultralytics/cfg/solutions/default.yaml
  ultralytics/solutions/ai_gym.py
  ultralytics/solutions/solutions.py
  ultralytics/utils/plotting.py
Labels: enhancement, pose, solutions

#16708 Update W&B docs.
  docs/en/datasets/pose/hand-keypoints.md
  docs/en/guides/security-alarm-system.md
  docs/en/guides/steps-of-a-cv-project.md
  docs/en/integrations/weights-biases.md
  docs/mkdocs_github_authors.yaml
Labels: documentation, devops

#16720 Update `heatmaps` solution
  docs/en/guides/heatmaps.md
  tests/test_solutions.py
  ultralytics/cfg/solutions/default.yaml
  ultralytics/solutions/heatmap.py
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/solutions.py
Labels: enhancement, solutions, devops

#16722 `ultralytics 8.3.6` improve `collect_system_info`
  docs/en/reference/utils/torch_utils.md
  ultralytics/__init__.py
  ultralytics/engine/trainer.py
  ultralytics/utils/checks.py
  ultralytics/utils/torch_utils.py
Labels: enhancement, devops

#16725 FROM pytorch/pytorch:2.4.1-cuda12.1-cudnn9-runtime
  docker/Dockerfile
Labels: enhancement, dependencies

#16726 Fix absolute stylesheet CSS path
  docs/overrides/javascript/extra.js
Labels: documentation

#16742 New `create_synthetic_coco_dataset` function
  docs/en/reference/data/converter.md
  ultralytics/data/converter.py
Labels: enhancement

#16739 Added YOLO11 to Explorer models
  ultralytics/data/explorer/gui/dash.py
Labels: enhancement, Explorer

#16727 setuptools>=70.0.0 fix CVE-2024-6345⁠
  pyproject.toml
Labels: enhancement, dependencies

#16744 AutoBatch improve cache clearing
  ultralytics/utils/autobatch.py
  ultralytics/utils/torch_utils.py
Labels: enhancement, devops

#16734 `ultralytics 8.3.7` custom Predictor args fix
  ultralytics/__init__.py
  ultralytics/engine/model.py
Labels: enhancement, detect

#16770 Add package name to YOLO checks errors
  ultralytics/data/converter.py
  ultralytics/utils/checks.py
Labels: enhancement, devops

#16783 Fix `results.show()` for Jupyter notebooks
  ultralytics/utils/plotting.py
Labels: documentation, enhancement

#16751 Respect ENV value for `OMP_NUM_THREADS` if set
  ultralytics/__init__.py
Labels: enhancement, devops

#16782 `ultralytics 8.3.8` replace `contextlib` with `try` for speed
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/data/dataset.py
  ultralytics/data/utils.py
  ultralytics/nn/autobackend.py
  ultralytics/nn/tasks.py
  ultralytics/utils/__init__.py
  ultralytics/utils/callbacks/tensorboard.py
  ultralytics/utils/checks.py
  ultralytics/utils/downloads.py
  ultralytics/utils/plotting.py
  ultralytics/utils/torch_utils.py
Labels: enhancement

#16784 Rename loggers from YOLOv8 to Ultralytics
  ultralytics/utils/callbacks/clearml.py
  ultralytics/utils/callbacks/comet.py
  ultralytics/utils/callbacks/mlflow.py
  ultralytics/utils/callbacks/neptune.py
  ultralytics/utils/callbacks/wb.py
Labels: enhancement

#16785 AutoBatch larger batches on larger GPUs
  ultralytics/utils/autobatch.py
Labels: enhancement

#16801 fix autobackend.py
  ultralytics/nn/autobackend.py
Labels: enhancement, fixed

#16798 Update `speed-estimation` solution
  docs/en/guides/speed-estimation.md
  tests/test_solutions.py
  ultralytics/cfg/solutions/default.yaml
  ultralytics/solutions/speed_estimation.py
Labels: enhancement, track, solutions

#16797 Remove -e tag from CI
  .github/workflows/ci.yaml
Labels: dependencies, devops

#16790 Fix wrong parameter count while profiling
  ultralytics/nn/tasks.py
Labels: bug, fixed

#16819 Sort alphabetical integrations in docs
  docs/en/integrations/index.md
  mkdocs.yml
Labels: documentation, enhancement

#16825 Fix typos in Tasks in docs so description matches example code
  docs/en/tasks/obb.md
  docs/en/tasks/pose.md
  docs/en/tasks/segment.md
Labels: documentation

#16822 Fixed YOLO heads docstrings
  tests/test_explorer.py
  ultralytics/nn/modules/head.py
Labels: documentation, enhancement

#16836 Adding missing MNIST160 reference in Docs
  docs/en/datasets/classify/index.md
  docs/en/datasets/index.md
  docs/en/usage/python.md
Labels: documentation, classify

#16853 `ultralytics 8.3.10` Apple iPhone HEIC support
  docs/en/modes/predict.md
  ultralytics/__init__.py
  ultralytics/data/loaders.py
  ultralytics/data/utils.py
  ultralytics/engine/predictor.py
  ultralytics/utils/checks.py
Labels: enhancement, dependencies

#16855 Add HUB-SDK badges to CI Docs
  docs/en/help/CI.md
Labels: documentation, HUB

#16858 Trigger GitHub Action on successful Docker Deploy
  .github/workflows/docker.yaml
Labels: enhancement, devops

#16859 Only trigger additional Actions on new Ultralytics releases
  .github/workflows/docker.yaml
Labels: devops

#16869 Fix CI docker.yaml
  .github/workflows/docker.yaml
Labels: enhancement, devops

#16866 Add camera device to inference sources
  docs/en/modes/predict.md
Labels: documentation, enhancement

#16874 `ultralytics 8.3.11` suppress `onnx2tf` INT8-FP16 act error
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
Labels: enhancement, exports

#16823 Update `analytics` solution
  docs/en/guides/analytics.md
  ultralytics/cfg/solutions/default.yaml
  ultralytics/solutions/analytics.py
Labels: documentation, enhancement, solutions

#16842 Remove `explorer` Integration
  docs/en/datasets/explorer/api.md
  docs/en/datasets/explorer/dashboard.md
  docs/en/datasets/explorer/explorer.ipynb
  docs/en/datasets/explorer/index.md
  docs/en/guides/preprocessing_annotated_data.md
  docs/en/reference/cfg/__init__.md
  docs/en/reference/data/explorer/explorer.md
  docs/en/reference/data/explorer/gui/dash.md
  docs/en/reference/data/explorer/utils.md
  docs/en/usage/python.md
  docs/en/usage/simple-utilities.md
  mkdocs.yml
  pyproject.toml
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/data/explorer/__init__.py
  ultralytics/data/explorer/explorer.py
  ultralytics/data/explorer/gui/__init__.py
  ultralytics/data/explorer/gui/dash.py
  ultralytics/data/explorer/utils.py
Labels: enhancement, dependencies, Explorer

#16880 Reduce EdgeTPU to 3 compiler steps
  ultralytics/engine/exporter.py
Labels: enhancement, exports

#16643 `ultralytics 8.3.12` SAM and SAM2 multi-point prompts
  docs/en/models/mobile-sam.md
  docs/en/models/sam.md
  tests/test_cli.py
  tests/test_cuda.py
  ultralytics/__init__.py
  ultralytics/models/sam/predict.py
Labels: enhancement, segment

#16901 Clean up duplicated classify logging
  ultralytics/models/yolo/classify/train.py
Labels: documentation, enhancement, classify

#16881 Sleep 60s before triggering deploy actions
  .github/workflows/docker.yaml
Labels: devops

#16898 Fix results.csv plotting
  ultralytics/utils/plotting.py
Labels: documentation, enhancement

#16899 Update Raspberry Pi Guide with YOLO11
  docs/en/guides/raspberry-pi.md
Labels: documentation, embedded

#16900 Always return Precision metric regardless of `plot` arg
  ultralytics/utils/metrics.py
Labels: enhancement, detect

#16910 Use EdgeTPU export `--delegate_search_step 30`
  ultralytics/engine/exporter.py
Labels: enhancement, exports

#16907 Update `distance-calculation` solution
  docs/en/guides/distance-calculation.md
  docs/en/guides/heatmaps.md
  docs/en/guides/workouts-monitoring.md
  ultralytics/solutions/distance_calculation.py
  ultralytics/solutions/object_counter.py
  ultralytics/utils/plotting.py
Labels: documentation, enhancement, solutions

#16875 Add `YOLO11 🚀 NEW` link in docs homepage
  mkdocs.yml
Labels: TODO, documentation, enhancement

#16932 Fix link in docs guide page
  docs/en/guides/model-deployment-practices.md
Labels: documentation

#16937 Fix naming of dataset for OBB in Google Colab Tutorial
  examples/tutorial.ipynb
Labels: documentation, OBB

#16940 Ultralytics Code Refactor https://ultralytics.com/actions
  .github/workflows/cla.yml
  .github/workflows/docker.yaml
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/merge-main-into-prs.yml
  .github/workflows/publish.yml
  docs/en/integrations/weights-biases.md
  ultralytics/cfg/__init__.py
  ultralytics/data/utils.py
  ultralytics/nn/autobackend.py
  ultralytics/nn/tasks.py
  ultralytics/solutions/analytics.py
  ultralytics/solutions/heatmap.py
  ultralytics/utils/__init__.py
  ultralytics/utils/callbacks/tensorboard.py
  ultralytics/utils/checks.py
  ultralytics/utils/downloads.py
  ultralytics/utils/plotting.py
  ultralytics/utils/torch_utils.py
Labels: documentation, enhancement, devops

#16941 Comet ML Docs - Fix link, naming and formatting
  docs/en/integrations/comet.md
Labels: documentation

#16846 Improve Home "Where to Start" Layout in Docs
  docs/en/index.md
Labels: documentation, enhancement

#16946 Recommend newer Python version in conda docs
  docs/en/guides/conda-quickstart.md
Labels: documentation

#16948 Update publish.yml
  .github/workflows/publish.yml
Labels: dependencies, devops

#16945 Fix Home "Where to Start" grid card link alignment in docs
  .github/workflows/docs.yml
  docs/en/index.md
Labels: documentation

#16821 Optimize Example YOLO post-processing speed
  examples/YOLOv8-OpenCV-int8-tflite-Python/main.py
Labels: enhancement, detect

#16965 Fix `self.type` variable name in Analytics solution
  ultralytics/solutions/analytics.py
Labels: documentation, enhancement

#16953 `ultralytics 8.3.14` update TensorRT `dynamic` inference
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/nn/autobackend.py
Labels: enhancement, fixed, exports

#16967 Update publish.yml
  .github/workflows/publish.yml
Labels: enhancement, devops

#16970 Expand Docs CI table with `mkdocs`, `thop`, `actions`, `handbook`
  docs/en/help/CI.md
Labels: documentation, enhancement, devops

#16971 Fix broken Tencent AI link
  docs/en/models/yolo-world.md
Labels: documentation

#16974 Remove `onnxslim==0.1.34` pin
  ultralytics/engine/exporter.py
Labels: enhancement, dependencies, exports

#16975 Update `utralytics/solutions` docstrings to match new YOLO11
  ultralytics/solutions/ai_gym.py
  ultralytics/solutions/parking_management.py
  ultralytics/solutions/streamlit_inference.py
Labels: documentation, enhancement, solutions

#16938 Fix Triton inference without explicit metadata
  ultralytics/nn/autobackend.py
Labels: bug, enhancement

#16576 `ultralytics 8.3.15` new TPU device-selection ability
  docs/en/guides/coral-edge-tpu-on-raspberry-pi.md
  ultralytics/__init__.py
  ultralytics/nn/autobackend.py
  ultralytics/utils/torch_utils.py
Labels: TODO, enhancement

#16990 Update `parking-management` solution
  docs/en/guides/parking-management.md
  ultralytics/cfg/solutions/default.yaml
  ultralytics/solutions/parking_management.py
Labels: TODO, enhancement, solutions

#16994 Update Integrations table
  README.md
  README.zh-CN.md
Labels: documentation, enhancement

#16995 Docker tkinter fix
  ultralytics/solutions/parking_management.py
Labels: enhancement, devops

#16996 Update README links
  README.md
  README.zh-CN.md
Labels: documentation

#17012 Fixed build docs regex security
  docs/build_docs.py
Labels: documentation

#16998 `ultralytics 8.3.16` PyTorch 2.5.0 support
  .github/workflows/publish.yml
  docs/mkdocs_github_authors.yaml
  mkdocs.yml
  pyproject.toml
  tests/test_solutions.py
  ultralytics/__init__.py
  ultralytics/data/split_dota.py
  ultralytics/solutions/ai_gym.py
  ultralytics/solutions/analytics.py
  ultralytics/solutions/distance_calculation.py
  ultralytics/solutions/heatmap.py
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/parking_management.py
  ultralytics/solutions/queue_management.py
  ultralytics/solutions/solutions.py
  ultralytics/solutions/speed_estimation.py
  ultralytics/solutions/streamlit_inference.py
Labels: documentation

#17010 Backward compatibility support for legacy models
  ultralytics/nn/modules/head.py
  ultralytics/nn/tasks.py
Labels: enhancement, detect

#16641 `ultralytics 8.3.17` accept spaces in CLI args
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
Labels: enhancement

#17022 Update YOLO login
  ultralytics/cfg/__init__.py
  ultralytics/hub/__init__.py
  ultralytics/hub/auth.py
Labels: documentation, HUB

#17023 `ultralytics 8.3.18` fix `is_jupyter()` to `globals()`
  ultralytics/__init__.py
  ultralytics/utils/__init__.py
Labels: enhancement, HUB

#17032 Correct Capitalization in Docs
  docs/en/guides/coral-edge-tpu-on-raspberry-pi.md
  docs/en/guides/model-training-tips.md
  docs/en/guides/steps-of-a-cv-project.md
Labels: documentation

#17033 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
  README.md
  README.zh-CN.md
  docs/en/datasets/explorer/explorer.ipynb
  docs/en/index.md
  docs/en/integrations/kaggle.md
  docs/en/yolov5/environments/aws_quickstart_tutorial.md
  docs/en/yolov5/environments/docker_image_quickstart_tutorial.md
  docs/en/yolov5/index.md
  docs/en/yolov5/tutorials/hyperparameter_evolution.md
  docs/en/yolov5/tutorials/model_ensembling.md
  docs/en/yolov5/tutorials/model_export.md
  docs/en/yolov5/tutorials/model_pruning_and_sparsity.md
  docs/en/yolov5/tutorials/multi_gpu_training.md
  docs/en/yolov5/tutorials/pytorch_hub_model_loading.md
  docs/en/yolov5/tutorials/roboflow_datasets_integration.md
  docs/en/yolov5/tutorials/test_time_augmentation.md
  docs/en/yolov5/tutorials/train_custom_data.md
  docs/en/yolov5/tutorials/transfer_learning_with_frozen_layers.md
  examples/heatmaps.ipynb
  examples/object_counting.ipynb
  examples/object_tracking.ipynb
  examples/tutorial.ipynb
  ultralytics/cfg/datasets/coco128-seg.yaml
  ultralytics/cfg/datasets/coco128.yaml
Labels: documentation, enhancement

#17031 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
  README.md
  README.zh-CN.md
  docs/build_docs.py
  docs/en/datasets/explorer/explorer.ipynb
  docs/en/guides/coral-edge-tpu-on-raspberry-pi.md
  docs/en/guides/model-training-tips.md
  docs/en/guides/steps-of-a-cv-project.md
  docs/en/index.md
  docs/en/integrations/kaggle.md
  docs/en/yolov5/environments/aws_quickstart_tutorial.md
  docs/en/yolov5/environments/docker_image_quickstart_tutorial.md
  docs/en/yolov5/index.md
  docs/en/yolov5/tutorials/hyperparameter_evolution.md
  docs/en/yolov5/tutorials/model_ensembling.md
  docs/en/yolov5/tutorials/model_export.md
  docs/en/yolov5/tutorials/model_pruning_and_sparsity.md
  docs/en/yolov5/tutorials/multi_gpu_training.md
  docs/en/yolov5/tutorials/pytorch_hub_model_loading.md
  docs/en/yolov5/tutorials/roboflow_datasets_integration.md
  docs/en/yolov5/tutorials/test_time_augmentation.md
  docs/en/yolov5/tutorials/train_custom_data.md
  docs/en/yolov5/tutorials/transfer_learning_with_frozen_layers.md
  docs/overrides/partials/source-file.html
  examples/heatmaps.ipynb
  examples/object_counting.ipynb
  examples/object_tracking.ipynb
  examples/tutorial.ipynb
  ultralytics/cfg/datasets/coco128-seg.yaml
  ultralytics/cfg/datasets/coco128.yaml
Labels: documentation, enhancement

#17036 Fix build_docs regex for trailing URL periods
  docs/build_docs.py
Labels: documentation, enhancement

#17038 Fix MNIST link
  docs/build_docs.py
  docs/en/datasets/classify/mnist.md
Labels: documentation

#17039 Improve Docs publish.yml workflow dispatch
  .github/workflows/docs.yml
Labels: documentation, enhancement, devops

#17040 Update extra.js
  .github/workflows/docs.yml
  docs/build_docs.py
  docs/overrides/javascript/extra.js
  docs/overrides/javascript/giscus.js
  docs/overrides/partials/comments.html
  docs/overrides/stylesheets/style.css
  mkdocs.yml
Labels: enhancement

#17075 Remove YOLO11n message from AMP logs
  ultralytics/utils/checks.py
Labels: enhancement

#17065 Update notebooks
  examples/heatmaps.ipynb
  examples/object_counting.ipynb
Labels: documentation, enhancement

#17076 `ultralytics 8.3.19` TensorRT 10.5.0 support
  docker/Dockerfile
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: dependencies, exports

#17094 Dockerfile FROM pytorch/pytorch:2.5.0-cuda12.4-cudnn9-runtime
  docker/Dockerfile
Labels: enhancement, dependencies, devops

#17090 Add Open Images Dataset V7 pretrained model usage examples
  docs/en/datasets/detect/open-images-v7.md
Labels: documentation, enhancement, detect

#17088 `ultralytics 8.3.20` W&B `plots=False` logging fix
  ultralytics/__init__.py
  ultralytics/utils/callbacks/wb.py
Labels: bug, enhancement

#17097 Update YOLO11 comparison plots
  README.md
  README.zh-CN.md
  docs/en/models/index.md
  docs/en/models/yolo11.md
Labels: documentation

#17095 Add YOLO publication notice in Docs
  docs/en/models/yolo11.md
  docs/en/models/yolov5.md
  docs/en/models/yolov8.md
Labels: documentation, research

#17114 Add `project` and `name` args to docs for predict and val task
  docs/en/macros/predict-args.md
  docs/en/macros/validation-args.md
Labels: documentation, enhancement

#17099 Comet integration fix
  ultralytics/utils/callbacks/comet.py
Labels: enhancement, segment, pose

#17098 Update datasets index.md
  docs/en/datasets/index.md
  mkdocs.yml
Labels: documentation

#16449 `ultralytics 8.3.21` NVIDIA DLA export support
  docs/en/guides/nvidia-jetson.md
  docs/en/macros/export-args.md
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
Labels: enhancement, embedded, exports

#17128 Fix DLA export when device=None
  ultralytics/engine/exporter.py
Labels: exports

#17112 Enable default cfg for similar args in solutions.
  ultralytics/cfg/solutions/default.yaml
  ultralytics/solutions/parking_management.py
  ultralytics/solutions/solutions.py
  ultralytics/utils/__init__.py
Labels: TODO, enhancement, solutions

#17074 Add Binder Notebook badge
  README.md
  README.zh-CN.md
Labels: documentation, enhancement

#17131 `ultralytics 8.3.22` SAM2.1 integration
  docs/en/models/sam-2.md
  tests/test_cuda.py
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/models/sam/build.py
  ultralytics/models/sam/modules/sam.py
Labels: documentation, enhancement, segment

#17162 Fix Python warning spam
  ultralytics/utils/checks.py
Labels: enhancement

#17161 Fix inaccurate example in Export docs
  docs/en/modes/export.md
Labels: documentation, exports

#17164 Default W&B setting `False`
  ultralytics/utils/__init__.py
Labels: enhancement

#17157 `ultralytics 8.3.23` fix `bbox2segment` when no segments generated
  ultralytics/__init__.py
  ultralytics/data/converter.py
Labels: bug, enhancement, segment

#17052 Update OBB predict examples with boats.jpg
  docs/en/modes/predict.md
  docs/en/tasks/obb.md
  examples/tutorial.ipynb
  ultralytics/cfg/__init__.py
Labels: TODO, enhancement, OBB

#17179 Add explorer depreciation message in `datasets/index.md`
  docs/en/datasets/index.md
Labels: documentation, Explorer

#17194 Ultralytics Cleanup Disk action in docker.yaml
  .github/workflows/docker.yaml
Labels: enhancement, devops

#17196 Disable HUB CI temporarily
  .github/workflows/ci.yaml
Labels: HUB, devops

#17221 Pin `numpy<=2.0.0` on macOS
  pyproject.toml
  ultralytics/engine/exporter.py
Labels: dependencies, exports

#17206 Update NVIDIA Jetson Guide with YOLO11
  docs/en/guides/nvidia-jetson.md
Labels: documentation, embedded

#17183 Adds permissions for stale workflow
  .github/workflows/stale.yml
Labels: TODO, bug, fixed, devops

#17215 `ultralytics 8.3.24` SAM fix `pred_boxes` when no objects segmented
  ultralytics/__init__.py
  ultralytics/models/sam/predict.py
Labels: enhancement, fixed, segment

#17138 Fix arbitrary imgsz for TFLite
  ultralytics/engine/exporter.py
Labels: bug, enhancement, exports

#16962 Example ORT==2.0.0-rs.5 to support onnxruntime==1.19.x
  examples/YOLOv8-ONNXRuntime-Rust/Cargo.toml
  examples/YOLOv8-ONNXRuntime-Rust/README.md
  examples/YOLOv8-ONNXRuntime-Rust/src/cli.rs
  examples/YOLOv8-ONNXRuntime-Rust/src/lib.rs
  examples/YOLOv8-ONNXRuntime-Rust/src/main.rs
  examples/YOLOv8-ONNXRuntime-Rust/src/model.rs
  examples/YOLOv8-ONNXRuntime-Rust/src/ort_backend.rs
Labels: enhancement, dependencies, exports

#17184 Faster ONNX inference with bindings
  ultralytics/nn/autobackend.py
Labels: enhancement, exports

#17241 Notify only on first CI run
  .github/workflows/ci.yaml
  .github/workflows/docker.yaml
Labels: enhancement, devops

#17172 Decrease default confidence threshold to start tracking new tracks
  ultralytics/cfg/trackers/botsort.yaml
  ultralytics/cfg/trackers/bytetrack.yaml
Labels: enhancement, track
