Repository ultralytics/ultralytics, pull requests merged in 2024-05, with the labels that each got.

#10733 Add FastSAM and YOLO-World tracking docs
  docs/en/guides/parking-management.md
  docs/en/integrations/google-colab.md
  docs/en/models/fast-sam.md
  docs/en/models/yolo-world.md
Labels: documentation

#10404 Fix TFLite export for NVIDIA Jetson
  ultralytics/engine/exporter.py
Labels: TODO, enhancement, dependencies

#10280 `ultralytics 8.2.7` add Raspberry Pi Benchmarks CI
  .github/workflows/ci.yaml
  pyproject.toml
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
Labels: enhancement, devops

#10432 Fix `instance` area method format-change bug
  ultralytics/utils/instance.py
Labels: fixed

#11233 Add `windows-latest` to CI Tests
  .github/workflows/ci.yaml
  tests/test_python.py
Labels: devops

#11647 Fix bug in Annotation UI Parking Management
  ultralytics/solutions/parking_management.py
Labels: bug, solutions

#11216 Quality of life changes for Benchmarking script
  .gitignore
  ultralytics/utils/benchmarks.py
Labels: enhancement

#11653 `ultralytics 8.2.10` add Classify and OBB Tasks to `Results.summary()`
  tests/test_exports.py
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/engine/results.py
Labels: TODO

#11694 Fix single-image dataset failure mode
  tests/test_cli.py
  ultralytics/data/base.py
Labels: fixed

#11242 Optimize NVIDIA Jetson Docs
  docs/en/guides/nvidia-jetson.md
  docs/en/reference/solutions/parking_management.md
  mkdocs.yml
Labels: documentation

#10165 `ultralytics 8.2.11` new TensorRT INT8 export feature
  docs/en/hub/integrations.md
  docs/en/integrations/index.md
  docs/en/integrations/tensorrt.md
  docs/en/modes/benchmark.md
  docs/en/modes/export.md
  docs/en/tasks/classify.md
  docs/en/tasks/detect.md
  docs/en/tasks/obb.md
  docs/en/tasks/pose.md
  docs/en/tasks/segment.md
  docs/en/usage/cli.md
  examples/tutorial.ipynb
  tests/test_cuda.py
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
Labels: TODO, enhancement, dependencies

#11788 Enforce `dynamic=True` for TensorRT and OpenVINO INT8
  ultralytics/engine/exporter.py
Labels: bug, fixed

#11801 Fix classify table
  README.md
Labels: documentation

#11773 Update YOLOv8-ONNXRuntime-Rust README
  examples/README.md
  examples/YOLOv8-ONNXRuntime-Rust/README.md
Labels: documentation

#12573 `ultralytics 8.2.14` add `task` + OBB to `hub.check_dataset()`
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/data/utils.py
  ultralytics/hub/__init__.py
  ultralytics/utils/plotting.py
Labels: enhancement, HUB

#12652 `ultralytics 8.2.15` get_latest_opset() compat for `torch<1.13.0`
  ultralytics/__init__.py
  ultralytics/utils/torch_utils.py
Labels: enhancement, dependencies

#11787 `ultralytics 8.2.16` DDP `pretrained` argument fix
  examples/tutorial.ipynb
  ultralytics/__init__.py
  ultralytics/engine/trainer.py
Labels: TODO, enhancement

#12748 Add https://youtu.be/ogTBBD8McRk & https://youtu.be/Fj9TStNBVoY to docs
  docs/en/datasets/detect/brain-tumor.md
  docs/en/guides/object-counting.md
Labels: documentation, enhancement

#11779 TensorRT10 with JetPack 6.0 Docs update
  docs/en/integrations/tensorrt.md
Labels: documentation

#12977 Add Signature ✍️ dataset in docs
  docs/en/datasets/detect/index.md
  docs/en/datasets/detect/signature.md
  docs/en/datasets/index.md
  mkdocs.yml
  ultralytics/cfg/datasets/signature.yaml
Labels: documentation

#12987 Remove extraneous list brackets
  ultralytics/data/build.py
Labels: enhancement

#13006 `ultralytics 8.2.19` fix Conda CI relative import bug
  tests/conftest.py
  tests/test_cli.py
  tests/test_cuda.py
  tests/test_engine.py
  tests/test_exports.py
  tests/test_integrations.py
  tests/test_python.py
  ultralytics/__init__.py
Labels: bug, devops

#12955 `ultralytics 8.2.20` new `Analytics` class with plotting visuals
  docs/en/guides/analytics.md
  docs/en/guides/index.md
  docs/en/guides/workouts-monitoring.md
  docs/en/modes/predict.md
  mkdocs.yml
  ultralytics/__init__.py
  ultralytics/solutions/__init__.py
  ultralytics/solutions/ai_gym.py
  ultralytics/solutions/analytics.py
Labels: documentation, enhancement, solutions

#13114 Add YOLOv10 docs
  docs/en/models/yolov10.md
  mkdocs.yml
Labels: documentation

#13122 `ultralytics 8.2.22` Parking Management Solution fix
  docs/en/guides/parking-management.md
  docs/en/guides/speed-estimation.md
  docs/en/models/yolov10.md
  ultralytics/__init__.py
  ultralytics/solutions/__init__.py
  ultralytics/solutions/analytics.py
  ultralytics/solutions/parking_management.py
Labels: bug, documentation, enhancement, solutions

#13021 Add PyPI and conda-forge badges
  README.md
  README.zh-CN.md
  docs/README.md
  docs/en/guides/conda-quickstart.md
  docs/en/guides/docker-quickstart.md
  docs/en/quickstart.md
Labels: documentation

#13197 Add https://youtu.be/F7db-EHhxss to docs
  docs/en/models/fast-sam.md
Labels: documentation

#13182 Add Steps in a Computer Vision Project Docs Page and Defining Your Computer Vision Project Docs Page
  docs/en/guides/defining-project-goals.md
  docs/en/guides/index.md
  docs/en/guides/steps-of-a-cv-project.md
  mkdocs.yml
Labels: documentation, enhancement

#12645 Display Val images per class
  .github/workflows/ci.yaml
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/models/yolo/segment/val.py
Labels: TODO, enhancement

#13214 Add multiple lines graph support in `analytics` 8.2.26
  docs/en/guides/analytics.md
  ultralytics/__init__.py
  ultralytics/solutions/analytics.py
Labels: documentation

#12738 New dataset: human8
  docs/en/datasets/human/coco8-human.md
  docs/en/datasets/human/index.md
  docs/en/models/yolo-human.md
  docs/en/tasks/human.md
  docs/mkdocs_github_authors.yaml
  mkdocs.yml
  ultralytics/cfg/datasets/human8.yaml
Labels: enhancement

#13265 Add YOLOv10 model description in docs home page
  docs/en/index.md
Labels: documentation

#12989 `ultralytics 8.2.27` replace `onnxsim` with `onnxslim`
  docker/Dockerfile-arm64
  docs/en/modes/export.md
  tests/test_cuda.py
  tests/test_exports.py
  ultralytics/__init__.py
  ultralytics/cfg/default.yaml
  ultralytics/engine/exporter.py
  ultralytics/nn/modules/__init__.py
  ultralytics/utils/benchmarks.py
Labels: enhancement
