Repository ultralytics/ultralytics, pull requests merged in 2024-07, with the labels that each got.

#14059 Update NVIDIA Jetson DeepStream Guide with YOLOv8 and Jetson Orin Support
  docs/en/guides/deepstream-nvidia-jetson.md
  docs/en/guides/index.md
  docs/en/yolov5/index.md
  docs/en/yolov5/tutorials/running_on_jetson_nano.md
  mkdocs.yml
Labels: TODO

#14105 Add Model Testing Guide and Best Practices for Model Deployment Guide
  docs/en/guides/index.md
  docs/en/guides/model-deployment-practices.md
  docs/en/guides/model-testing.md
  mkdocs.yml
Labels: documentation, enhancement

#14195 Add https://youtu.be/mUybgOlSxxA to docs
  docs/en/guides/nvidia-jetson.md
Labels: documentation, enhancement

#14181 Add FAQ sections to Modes and Tasks
  docs/en/guides/model-deployment-practices.md
  docs/en/guides/model-testing.md
  docs/en/models/fast-sam.md
  docs/en/models/index.md
  docs/en/models/mobile-sam.md
  docs/en/models/rtdetr.md
  docs/en/models/sam.md
  docs/en/models/yolo-nas.md
  docs/en/models/yolo-world.md
  docs/en/models/yolov10.md
  docs/en/models/yolov3.md
  docs/en/models/yolov4.md
  docs/en/models/yolov5.md
  docs/en/models/yolov6.md
  docs/en/models/yolov7.md
  docs/en/models/yolov8.md
  docs/en/models/yolov9.md
  docs/en/modes/benchmark.md
  docs/en/modes/export.md
  docs/en/modes/index.md
  docs/en/modes/predict.md
  docs/en/modes/track.md
  docs/en/modes/train.md
  docs/en/modes/val.md
  docs/en/quickstart.md
  docs/en/tasks/classify.md
  docs/en/tasks/detect.md
  docs/en/tasks/index.md
  docs/en/tasks/obb.md
  docs/en/tasks/pose.md
  docs/en/tasks/segment.md
  docs/en/usage/callbacks.md
  docs/en/usage/cfg.md
  docs/en/usage/cli.md
  docs/en/usage/engine.md
  docs/en/usage/python.md
  docs/en/usage/simple-utilities.md
  mkdocs.yml
  ultralytics/engine/model.py
Labels: documentation

#14159 New 🌟Add Streamlit live inference application `8.2.49`
  docs/en/solutions/index.md
  docs/en/solutions/streamlit-live-inference.md
  mkdocs.yml
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/solutions/__init__.py
  ultralytics/solutions/streamlit_inference.py
  ultralytics/utils/plotting.py
Labels: documentation, enhancement, detect, solutions

#14197 Proposed fix for DDP issue for Classify task
  ultralytics/nn/tasks.py
Labels: bug, fixed

#14232 Fix Action Recognition Example with `torch>=2.0`
  examples/YOLOv8-Action-Recognition/action_recognition.py
Labels: enhancement

#14329 `ultralytics 8.2.53` Heatmaps fix for empty images
  ultralytics/__init__.py
  ultralytics/solutions/heatmap.py
Labels: bug, solutions

#14356 Add https://youtu.be/fLBbyhPbWzY to docs
  docs/en/datasets/classify/cifar10.md
Labels: documentation, enhancement, classify

#8809 Tensorflow 2.16.1 is out
  docs/en/datasets/classify/cifar10.md
Labels: wontfix, dependencies, external

#14269 `ultralytics 8.2.56` Streamlit tracking app
  examples/YOLOv8-ONNXRuntime-Rust/README.md
  ultralytics/__init__.py
  ultralytics/solutions/streamlit_inference.py
Labels: enhancement, solutions

#14417 Add https://youtu.be/gX5kSRD56Gs to docs
  docs/en/guides/queue-management.md
Labels: documentation, enhancement

#14408 `ultralytics 8.2.57` new Solutions Tests and Docs
  docs/en/guides/distance-calculation.md
  docs/en/guides/heatmaps.md
  docs/en/guides/instance-segmentation-and-tracking.md
  docs/en/guides/object-counting.md
  docs/en/guides/queue-management.md
  tests/test_solutions.py
  ultralytics/__init__.py
  ultralytics/solutions/distance_calculation.py
  ultralytics/solutions/heatmap.py
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/queue_management.py
  ultralytics/utils/plotting.py
Labels: documentation, enhancement, solutions, devops

#14484 Warn on `save_hybrid=True`
  ultralytics/models/yolo/detect/val.py
Labels: enhancement

#14498 Remove redundant assignment
  ultralytics/nn/modules/block.py
Labels: enhancement

#14499 Update `FastSAM` and `SAM` docs
  docs/en/models/fast-sam.md
  docs/en/models/sam.md
Labels: documentation

#14487 Add Kaggle Integrations Docs Page
  docs/en/integrations/index.md
  docs/en/integrations/kaggle.md
  mkdocs.yml
Labels: documentation

#14496 `ultralytics 8.2.59` use `Results.save_txt` for validation
  docs/en/integrations/kaggle.md
  docs/mkdocs_github_authors.yaml
  ultralytics/__init__.py
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/obb/val.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/models/yolo/segment/val.py
Labels: enhancement

#14474 `ultralytics 8.2.60` refactor `process_mask_upsample`
  docs/en/reference/utils/ops.md
  ultralytics/__init__.py
  ultralytics/models/yolo/segment/val.py
  ultralytics/utils/ops.py
Labels: enhancement

#14544 `ultralytics 8.2.61` fix `num_threads` for CPU training
  docs/build_docs.py
  mkdocs.yml
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/utils/torch_utils.py
Labels: fixed

#14390 Add Explorer CLI `model` and `data` args
  ultralytics/cfg/__init__.py
  ultralytics/data/explorer/gui/dash.py
Labels: enhancement, Explorer

#14563 Add Streamlit Inference Python `model` arg
  docs/en/guides/streamlit-live-inference.md
  ultralytics/solutions/streamlit_inference.py
Labels: enhancement, solutions

#14608 Update format.yml for PAT
  .github/workflows/format.yml
  docs/mkdocs_github_authors.yaml
Labels: dependencies, devops

#14609 Fix OBB Docs page commas error
  docs/en/datasets/obb/index.md
Labels: documentation, fixed, OBB

#14627 Add NAS autodownload
  ultralytics/models/nas/model.py
Labels: enhancement

#14637 Windows `torch==2.4.0` Segment `augment=True` failed test bypass
  tests/test_python.py
Labels: devops

#14632 Fix torchvision InterpolationMode warnings
  ultralytics/data/augment.py
Labels: bug, enhancement, classify

#14638 Patch `torch.load(..., weights_only=False)` to reduce warnings
  docs/en/reference/utils/patches.md
  ultralytics/utils/__init__.py
  ultralytics/utils/patches.py
Labels: bug, enhancement, dependencies

#14630 Attempt to fix NAS models inference
  ultralytics/models/nas/model.py
Labels: bug, fixed

#14621 Fix Streamlit Inference model suffix bug
  ultralytics/solutions/streamlit_inference.py
Labels: bug, enhancement, fixed

#14633 Fix `torch.amp.autocast('cuda')` warnings
  docs/en/reference/utils/torch_utils.md
  ultralytics/engine/trainer.py
  ultralytics/models/utils/ops.py
  ultralytics/utils/autobatch.py
  ultralytics/utils/checks.py
  ultralytics/utils/loss.py
  ultralytics/utils/torch_utils.py
Labels: bug, enhancement, dependencies, fixed

#14647 Fix `torch.amp` has no attribute `GradScaler`
  ultralytics/engine/trainer.py
Labels: bug, fixed

#14650 Add warning when `cache_ram` works with classify
  ultralytics/data/dataset.py
Labels: bug, enhancement, classify

#14675 Allow `agnostic_nms` option for validation
  ultralytics/models/yolo/detect/val.py
Labels: enhancement, detect

#14684 `ultralytics 8.2.65` fix YouTube throttling bug
  ultralytics/__init__.py
  ultralytics/data/loaders.py
Labels: bug, dependencies, fixed

#14690 Remove duplicate `make_divisible` function
  docs/en/reference/utils/torch_utils.md
  ultralytics/nn/tasks.py
  ultralytics/utils/torch_utils.py
Labels: enhancement, devops

#14698 Add https://youtu.be/_gRqR-miFPE to docs
  docs/en/datasets/detect/sku-110k.md
Labels: documentation, enhancement, detect, embedded

#14700 Updates `save_period` to include first epoch
  ultralytics/engine/trainer.py
Labels: enhancement

#14697 Add compatible `tensorstore` versions for `aarch64`
  docker/Dockerfile-arm64
  pyproject.toml
Labels: enhancement, dependencies, devops

#14702 `ultralytics 8.2.66` HUB model autodownload
  ultralytics/__init__.py
  ultralytics/engine/model.py
  ultralytics/engine/trainer.py
  ultralytics/hub/session.py
  ultralytics/utils/checks.py
Labels: enhancement, HUB

#14703 `SETTINGS` type and key checks
  ultralytics/utils/__init__.py
Labels: enhancement

#14750 Simplify Dockerfile `WORKDIR`
  docker/Dockerfile
  docker/Dockerfile-arm64
  docker/Dockerfile-conda
  docker/Dockerfile-cpu
  docker/Dockerfile-jetson-jetpack4
  docker/Dockerfile-jetson-jetpack5
  docker/Dockerfile-jetson-jetpack6
  docker/Dockerfile-python
Labels: enhancement, dependencies

#14753 `ultralytics 8.2.68` new HUB GCP region latency tests
  docs/en/reference/hub/google/__init__.md
  mkdocs.yml
  ultralytics/__init__.py
  ultralytics/hub/google/__init__.py
Labels: enhancement, devops

#14755 Add JupyterLab Integrations Docs Page
  docs/en/integrations/index.md
  docs/en/integrations/jupyterlab.md
  mkdocs.yml
Labels: documentation, enhancement

#14754 Update docs
  ultralytics/hub/google/__init__.py
Labels: documentation

#14773 Fixed typo and formatting OpenVINO integration
  docs/en/datasets/classify/cifar10.md
  docs/en/datasets/classify/imagenette.md
  docs/en/datasets/track/index.md
  docs/en/guides/streamlit-live-inference.md
  docs/en/integrations/dvc.md
  docs/en/integrations/jupyterlab.md
  docs/en/integrations/openvino.md
  ultralytics/hub/google/__init__.py
Labels: documentation

#14785 Add IBM Watsonx Integrations Docs Page
  docs/en/integrations/ibm-watsonx.md
  docs/en/integrations/index.md
  mkdocs.yml
Labels: documentation, enhancement

#14718 Update Ultralytics issue templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/question.yml
Labels: documentation, devops

#14745 Eliminate `set()` to avoid `set()` + `list()` op
  ultralytics/data/augment.py
Labels: bug, enhancement

#14724 `ultralytics 8.2.69` FastSAM prompt inference refactor
  docs/en/integrations/ibm-watsonx.md
  docs/en/models/fast-sam.md
  docs/en/reference/models/fastsam/prompt.md
  mkdocs.yml
  tests/test_cli.py
  ultralytics/__init__.py
  ultralytics/models/fastsam/__init__.py
  ultralytics/models/fastsam/model.py
  ultralytics/models/fastsam/predict.py
  ultralytics/models/fastsam/prompt.py
  ultralytics/utils/ops.py
Labels: enhancement, segment

#14793 Update comet from init() to login()
  docs/en/integrations/comet.md
Labels: documentation, enhancement

#14794 New Meta Segment Anything Model 2 (SAM2) Docs page
  docs/en/guides/model-monitoring-and-maintenance.md
  docs/en/hub/index.md
  docs/en/integrations/ibm-watsonx.md
  docs/en/integrations/jupyterlab.md
  docs/en/integrations/kaggle.md
  docs/en/models/index.md
  docs/en/models/sam.md
  docs/en/models/sam2.md
  mkdocs.yml
Labels: documentation, enhancement, segment

#14796 SAM2 mkdocs.yml fix
  docs/en/models/sam2.md
  mkdocs.yml
Labels: documentation

#14814 `py-cpuinfo` Exception context manager fix
  .github/workflows/publish.yml
  docs/en/models/index.md
  docs/en/models/sam-2.md
  mkdocs.yml
  ultralytics/utils/torch_utils.py
Labels: dependencies

#14817 Add https://youtu.be/_gRqR-miFPE & https://youtu.be/CfbHwPG01cE to docs
  docs/en/guides/steps-of-a-cv-project.md
  docs/en/models/yolov10.md
Labels: documentation, enhancement, detect

#14813 `ultralytics 8.2.70` Segment Anything Model 2 (SAM 2)
  docs/en/models/sam-2.md
  docs/en/reference/models/sam/modules/decoders.md
  docs/en/reference/models/sam/modules/sam.md
  docs/en/reference/models/sam2/build.md
  docs/en/reference/models/sam2/model.md
  docs/en/reference/models/sam2/modules/decoders.md
  docs/en/reference/models/sam2/modules/encoders.md
  docs/en/reference/models/sam2/modules/memory_attention.md
  docs/en/reference/models/sam2/modules/sam2.md
  docs/en/reference/models/sam2/modules/sam2_blocks.md
  docs/en/reference/models/sam2/modules/utils.md
  docs/en/reference/models/sam2/predict.md
  mkdocs.yml
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/models/__init__.py
  ultralytics/models/fastsam/predict.py
  ultralytics/models/sam/build.py
  ultralytics/models/sam/model.py
  ultralytics/models/sam/modules/decoders.py
  ultralytics/models/sam/modules/encoders.py
  ultralytics/models/sam/modules/sam.py
  ultralytics/models/sam/modules/transformer.py
  ultralytics/models/sam/predict.py
  ultralytics/models/sam2/__init__.py
  ultralytics/models/sam2/build.py
  ultralytics/models/sam2/model.py
  ultralytics/models/sam2/modules/__init__.py
  ultralytics/models/sam2/modules/decoders.py
  ultralytics/models/sam2/modules/encoders.py
  ultralytics/models/sam2/modules/memory_attention.py
  ultralytics/models/sam2/modules/sam2.py
  ultralytics/models/sam2/modules/sam2_blocks.py
  ultralytics/models/sam2/modules/utils.py
  ultralytics/models/sam2/predict.py
  ultralytics/nn/modules/transformer.py
Labels: enhancement, segment
