Repository ultralytics/ultralytics, pull requests merged in 2024-01, with the labels that each got.

#7265 fix: rename ModelPath to modelPath
  examples/YOLOv8-ONNXRuntime-CPP/inference.cpp
Labels: bug

#7325 Add `speed_estimation` and `distance_calculation` in ultralytics solutions
  docs/en/guides/distance-calculation.md
  docs/en/guides/heatmaps.md
  docs/en/guides/index.md
  docs/en/guides/region-counting.md
  docs/en/guides/speed-estimation.md
  docs/en/reference/solutions/distance_calculation.md
  docs/en/reference/solutions/speed_estimation.md
  docs/mkdocs.yml
  ultralytics/solutions/distance_calculation.py
  ultralytics/solutions/heatmap.py
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/speed_estimation.py
Labels: documentation, enhancement

#7373 Add `in_counts` and `out_counts` display functionality (User Oriented)
  docs/en/guides/object-counting.md
  ultralytics/solutions/object_counter.py
  ultralytics/utils/plotting.py
Labels: enhancement

#7380 `ultralytics 8.0.237` `cv2.CAP_PROP` fix and `in_counts` and `out_counts` displays
  .github/workflows/links.yml
  docs/en/guides/distance-calculation.md
  docs/en/guides/heatmaps.md
  docs/en/guides/instance-segmentation-and-tracking.md
  docs/en/guides/object-counting.md
  docs/en/guides/speed-estimation.md
  docs/en/guides/vision-eye.md
  docs/en/guides/workouts-monitoring.md
  examples/heatmaps.ipynb
  examples/object_counting.ipynb
  examples/object_tracking.ipynb
  ultralytics/__init__.py
  ultralytics/solutions/heatmap.py
  ultralytics/solutions/object_counter.py
  ultralytics/utils/plotting.py
Labels: bug, documentation

#7388 Add type hinting to explorer.py
  ultralytics/data/explorer/explorer.py
Labels: documentation, enhancement

#7317 YOLOv8 INT8 TFLite Inference Example
  examples/README.md
  examples/YOLOv8-OpenCV-int8-tflite-Python/README.md
  examples/YOLOv8-OpenCV-int8-tflite-Python/main.py
Labels: TODO

#7375 Explorer: Ask AI feature & plotting enhance
  docs/en/datasets/explorer/dash.md
  docs/en/datasets/explorer/explorer.ipynb
  docs/en/datasets/explorer/index.md
  docs/mkdocs.yml
  ultralytics/data/explorer/__init__.py
  ultralytics/data/explorer/explorer.py
  ultralytics/data/explorer/gui/dash.py
  ultralytics/data/explorer/utils.py
  ultralytics/utils/__init__.py
Labels: TODO

#7402 Fix object counting module in `heatmaps.py` & `instance-segmentation.md` none type bug fix
  docs/en/guides/heatmaps.md
  docs/en/guides/instance-segmentation-and-tracking.md
  ultralytics/solutions/distance_calculation.py
  ultralytics/solutions/heatmap.py
Labels: bug, enhancement

#7544 Update banner background
  docs/overrides/stylesheets/style.css
Labels: documentation

#7552 Use `pathlib` in DOTA ops
  docker/Dockerfile-cpu
  ultralytics/data/split_dota.py
  ultralytics/models/sam/modules/encoders.py
  ultralytics/utils/benchmarks.py
  ultralytics/utils/callbacks/comet.py
  ultralytics/utils/loss.py
Labels: OBB

#7558 OBB (Oriented Bounding Boxes) docs fix + notebook addition
  README.md
  README.zh-CN.md
  docs/en/tasks/obb.md
  examples/OBB_Training.ipynb
  examples/heatmaps.ipynb
  examples/object_counting.ipynb
Labels: bug, documentation, enhancement, OBB

#7598 Resize angle, count, and stage on keypoint number change
  ultralytics/solutions/ai_gym.py
Labels: track

#7596 `ultralytics 8.1.2` scope HUB-SDK imports
  pyproject.toml
  ultralytics/__init__.py
  ultralytics/engine/model.py
  ultralytics/hub/__init__.py
  ultralytics/hub/auth.py
  ultralytics/hub/session.py
  ultralytics/hub/utils.py
  ultralytics/utils/callbacks/hub.py
Labels: HUB

#7572 Bounding Box to OBB conversion
  ultralytics/data/converter.py
Labels: enhancement, OBB

#7740 Heatmap `im0` feature docs fix
  docs/en/guides/heatmaps.md
Labels: bug, documentation, enhancement
