Repository ultralytics/ultralytics, pull requests merged in 2024-03, with the labels that each got.

#8551 Add https://youtu.be/ie3vLUDNYZo and other YT videos in Docs
  docs/en/guides/distance-calculation.md
  docs/en/guides/instance-segmentation-and-tracking.md
  docs/en/hub/app/android.md
  docs/en/hub/app/ios.md
  docs/en/hub/cloud-training.md
Labels: documentation

#8539 `ultralytics 8.1.20` add YOLOv8x-World support
  docs/en/models/yolo-world.md
  ultralytics/__init__.py
Labels: documentation

#8531 Add KaTeX support + updates to YOLOv9 model page
  docs/en/models/yolov9.md
Labels: documentation, enhancement

#8580 `ultralytics 8.1.21` Add YOLOv8-World-v2 models
  .github/workflows/ci.yaml
  docs/en/models/yolo-world.md
  ultralytics/__init__.py
  ultralytics/cfg/models/v8/yolov8-world.yaml
  ultralytics/cfg/models/v8/yolov8-worldv2.yaml
  ultralytics/engine/exporter.py
  ultralytics/engine/model.py
  ultralytics/engine/trainer.py
  ultralytics/models/yolo/model.py
  ultralytics/utils/benchmarks.py
  ultralytics/utils/downloads.py
  ultralytics/utils/patches.py
Labels: enhancement

#8571 `ultralytics 8.1.23` add YOLOv9-C and E models
  docs/en/models/yolov9.md
  docs/en/reference/nn/modules/block.md
  ultralytics/__init__.py
  ultralytics/cfg/models/v9/yolov9c.yaml
  ultralytics/cfg/models/v9/yolov9e.yaml
  ultralytics/engine/exporter.py
  ultralytics/nn/modules/__init__.py
  ultralytics/nn/modules/block.py
  ultralytics/nn/tasks.py
  ultralytics/utils/downloads.py
Labels: enhancement

#8058 `ultralytics 8.1.25` OpenVINO `LATENCY` and `THROUGHPUT` modes
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: TODO

#8726 OpenVino 2024.0.0
  pyproject.toml
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: dependencies

#8819 Add docs guide terminal images
  docs/en/guides/index.md
  docs/en/guides/view-results-in-terminal.md
  mkdocs.yml
Labels: documentation

#8854 Batch inference fixes
  ultralytics/engine/predictor.py
Labels: bug, fixed

#8842 `ultralytics 8.1.27` batched tracking fixes
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/data/loaders.py
  ultralytics/engine/predictor.py
  ultralytics/trackers/track.py
Labels: fixed

#8900 Add TFLite Edge TPU Docs Integrations Page
  docs/en/integrations/edge-tpu.md
  docs/en/integrations/index.md
  docs/en/integrations/openvino.md
  mkdocs.yml
Labels: documentation, enhancement

#8861 New test for labels and crops
  tests/test_python.py
Labels: enhancement, devops

#8956 Remove unused var
  ultralytics/nn/modules/block.py
Labels: enhancement

#8970 simplify calculation, more readable
  ultralytics/utils/loss.py
Labels: enhancement

#9041 Add `brain-tumor` dataset docs page
  docs/en/datasets/detect/brain-tumor.md
  docs/mkdocs_github_authors.yaml
  mkdocs.yml
  ultralytics/cfg/datasets/brain-tumor.yaml
Labels: documentation, enhancement

#9108 Updating a typo on paddlepaddle.md
  docs/en/integrations/paddlepaddle.md
Labels: documentation

#9110 `ultralytics 8.1.30` add advanced HUB train arguments
  ultralytics/__init__.py
  ultralytics/engine/model.py
  ultralytics/hub/session.py
Labels: enhancement, HUB

#9196 fix yolo classify model loading error
  ultralytics/models/yolo/classify/train.py
Labels: enhancement

#9203 Add TF GraphDef Docs Integrations Page
  docs/en/integrations/index.md
  docs/en/integrations/tf-graphdef.md
  mkdocs.yml
Labels: documentation

#9235 `ultralytics 8.1.31` NCNN and CLIP updates
  docs/en/reference/cfg/__init__.md
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/data/build.py
  ultralytics/data/utils.py
  ultralytics/engine/results.py
  ultralytics/nn/autobackend.py
  ultralytics/nn/tasks.py
Labels: enhancement

#9102 Add https://youtu.be/aeAX6vWpfR0 to docs & `african-wildlife` dataset docs page
  docs/en/datasets/detect/african-wildlife.md
  docs/en/datasets/detect/index.md
  docs/en/datasets/index.md
  docs/en/tasks/pose.md
  mkdocs.yml
  ultralytics/cfg/datasets/african-wildlife.yaml
Labels: documentation, enhancement

#9162 Add TF SavedModel Docs Integrations Page
  docs/en/integrations/index.md
  docs/en/integrations/tf-savedmodel.md
  mkdocs.yml
Labels: documentation

#9254 Limit `ray<2.9.3` due to bug in `ray==2.10.0`
  .github/workflows/ci.yaml
  docs/en/integrations/ray-tune.md
  ultralytics/utils/tuner.py
Labels: bug, fixed

#9253 `ultralytics 8.1.32` fix CLIP backwards compatibility
  tests/test_cli.py
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/nn/tasks.py
Labels: bug, fixed

#9255 Conda cv2 ImportError libEGL.so.1 fix
  .github/workflows/ci.yaml
Labels: enhancement, dependencies

#9151 Reverse IoU threshold for NMS docs descriptions
  docs/en/modes/predict.md
  docs/en/usage/cfg.md
Labels: documentation, enhancement

#9139 Add `bgr` hyperparameter
  docs/en/modes/train.md
  docs/en/usage/cfg.md
  ultralytics/cfg/__init__.py
  ultralytics/cfg/default.yaml
  ultralytics/data/augment.py
  ultralytics/data/dataset.py
  ultralytics/engine/tuner.py
  ultralytics/utils/tuner.py
Labels: enhancement, research

#9153 `ultralytics 8.1.33` fix HUB model checks
  pyproject.toml
  ultralytics/__init__.py
  ultralytics/engine/model.py
  ultralytics/hub/__init__.py
  ultralytics/nn/autobackend.py
  ultralytics/utils/checks.py
  ultralytics/utils/downloads.py
Labels: enhancement, HUB

#9309 Specify YOLODataset task arg during INT8 calibration
  ultralytics/engine/exporter.py
Labels: enhancement

#9321 `ultralytics 8.1.35` simplify network modules
  ultralytics/__init__.py
  ultralytics/nn/modules/block.py
Labels: enhancement

#9273 Fix `is_cli` check to work even when `sys.argv` is empty.
  tests/test_engine.py
  ultralytics/engine/model.py
Labels: TODO, enhancement

#9386 Fix `None` `prevKeyPoints` for multi-object tracking
  ultralytics/trackers/utils/gmc.py
Labels: track

#9428 Update parameter explanations
  docs/en/modes/train.md
  docs/en/usage/cfg.md
  ultralytics/cfg/default.yaml
  ultralytics/data/augment.py
Labels: TODO, documentation, classify

#9405 Fix TFLite Segment mask rows 1-4 normalization
  ultralytics/nn/autobackend.py
Labels: segment

#9268 `ultralytics 8.1.39` add YOLO-World training
  docs/en/datasets/detect/index.md
  docs/en/datasets/detect/lvis.md
  docs/en/datasets/index.md
  docs/en/models/fast-sam.md
  docs/en/models/yolo-world.md
  docs/en/reference/data/augment.md
  docs/en/reference/data/build.md
  docs/en/reference/data/dataset.md
  docs/en/reference/data/utils.md
  docs/en/reference/models/yolo/world/train.md
  docs/en/reference/models/yolo/world/train_world.md
  docs/mkdocs_github_authors.yaml
  mkdocs.yml
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/cfg/datasets/lvis.yaml
  ultralytics/data/__init__.py
  ultralytics/data/augment.py
  ultralytics/data/build.py
  ultralytics/data/converter.py
  ultralytics/data/dataset.py
  ultralytics/data/utils.py
  ultralytics/engine/trainer.py
  ultralytics/models/fastsam/prompt.py
  ultralytics/models/yolo/__init__.py
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/model.py
  ultralytics/models/yolo/world/__init__.py
  ultralytics/models/yolo/world/train.py
  ultralytics/models/yolo/world/train_world.py
  ultralytics/nn/modules/block.py
  ultralytics/nn/modules/head.py
  ultralytics/nn/tasks.py
  ultralytics/utils/loss.py
Labels: TODO, enhancement

#9450 `ultralytics 8.1.40` search in Python sets `{}` for speed
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/data/augment.py
  ultralytics/data/base.py
  ultralytics/data/converter.py
  ultralytics/data/dataset.py
  ultralytics/data/loaders.py
  ultralytics/data/split_dota.py
  ultralytics/data/utils.py
  ultralytics/engine/exporter.py
  ultralytics/engine/model.py
  ultralytics/engine/results.py
  ultralytics/engine/trainer.py
  ultralytics/engine/validator.py
  ultralytics/hub/utils.py
  ultralytics/models/fastsam/model.py
  ultralytics/models/nas/model.py
  ultralytics/models/sam/model.py
  ultralytics/models/sam/modules/tiny_encoder.py
  ultralytics/models/yolo/classify/train.py
  ultralytics/models/yolo/detect/train.py
  ultralytics/models/yolo/world/train.py
  ultralytics/nn/autobackend.py
  ultralytics/nn/modules/conv.py
  ultralytics/nn/modules/head.py
  ultralytics/nn/tasks.py
  ultralytics/solutions/ai_gym.py
  ultralytics/solutions/heatmap.py
  ultralytics/trackers/byte_tracker.py
  ultralytics/trackers/track.py
  ultralytics/trackers/utils/gmc.py
  ultralytics/utils/__init__.py
  ultralytics/utils/benchmarks.py
  ultralytics/utils/callbacks/comet.py
  ultralytics/utils/callbacks/mlflow.py
  ultralytics/utils/checks.py
  ultralytics/utils/downloads.py
  ultralytics/utils/metrics.py
  ultralytics/utils/plotting.py
  ultralytics/utils/torch_utils.py
Labels: enhancement
