Repository ultralytics/ultralytics, pull requests merged in 2024-12, with the labels that each got.

#17883 GPU CI Fix wrong Ultralytics Installation
  .github/workflows/ci.yaml
Labels: dependencies, devops

#17871 Fix typo in Sony IMX500 doc
  docs/en/integrations/sony-imx500.md
Labels: TODO, documentation

#17878 Add more tracking args for solutions
  ultralytics/solutions/ai_gym.py
  ultralytics/solutions/solutions.py
Labels: enhancement, track, solutions

#17749 `uv pip install` for Benchmarks
  .github/workflows/ci.yaml
Labels: enhancement, dependencies, devops

#17910 Add `MNN` benchmarks to Raspberry Pi doc
  docs/en/guides/raspberry-pi.md
Labels: TODO, documentation, enhancement, embedded

#17920 Add arguments for solutions in `usage/cfg` docs page
  docs/en/guides/instance-segmentation-and-tracking.md
  docs/en/macros/solutions-args.md
  docs/en/usage/cfg.md
Labels: TODO, documentation, enhancement, solutions

#17918 `ultralytics 8.3.40` new `TrackZone` Solution
  docs/en/guides/trackzone.md
  docs/en/reference/solutions/trackzone.md
  docs/en/solutions/index.md
  mkdocs.yml
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/solutions/__init__.py
  ultralytics/solutions/trackzone.py
Labels: solutions

#17924 Update mkdocs.yml homepage
  mkdocs.yml
Labels: documentation

#17979 Add `batch` to list of `predict()` arguments
  docs/en/macros/predict-args.md
Labels: enhancement, detect

#17875 Add https://youtu.be/ZN3nRZT7b24 to tutorial.ipynb
  examples/tutorial.ipynb
Labels: documentation, enhancement, Notebook

#17925 Improve docs for Ultralytics version in benchmarks
  docs/en/guides/raspberry-pi.md
Labels: documentation, enhancement

#18050 Update functions description
  ultralytics/solutions/heatmap.py
  ultralytics/solutions/queue_management.py
Labels: documentation, enhancement, solutions

#18049 Fix `np.empty_like` function input type
  ultralytics/utils/ops.py
Labels: bug, enhancement

#17908 Revert `lapx` to `lap`
  ultralytics/trackers/utils/matching.py
Labels: TODO, dependencies, track

#18051 Preserve original points in `resample_segments`
  ultralytics/utils/ops.py
Labels: bug, enhancement, segment

#17977 Hardcode failing GPUs in AMP checks
  ultralytics/utils/checks.py
Labels: bug, enhancement

#18064 Set `task` for Triton inferenceTriton
  ultralytics/engine/model.py
Labels: enhancement, detect

#18059 Modified the parameter description of 'weights' in the AutoBackend class
  ultralytics/nn/autobackend.py
Labels: enhancement, devops

#18062 Fix `np.empty_like` and `torch.empty_like` input type
  docs/en/reference/utils/ops.md
  ultralytics/utils/ops.py
Labels: bug, enhancement

#17921 `ultralytics 8.3.44` improve Triton Inference Server metadata
  docs/en/guides/triton-inference-server.md
  ultralytics/__init__.py
  ultralytics/nn/autobackend.py
  ultralytics/utils/triton.py
Labels: TODO, documentation, segment, detect

#18072 Fix Docs YAML boolean
  .github/workflows/docs.yml
  ultralytics/models/sam/predict.py
Labels: documentation, devops

#18074 Eliminate duplicate bullet points in docs
  docs/en/solutions/index.md
Labels: documentation, enhancement

#18077 Mention `copy_paste` applies only when using segmentation labels
  docs/en/macros/augmentation-args.md
Labels: documentation, segment

#18085 `ultralytics 8.3.47` fix `softmax` and `Classify` head commonality
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/models/yolo/classify/predict.py
  ultralytics/models/yolo/classify/val.py
  ultralytics/nn/modules/head.py
  ultralytics/utils/loss.py
Labels: enhancement, classify

#18095 Update publish.yml with `--no-cache`
  .github/workflows/format.yml
  .github/workflows/publish.yml
Labels: dependencies, devops

#17664 Add CI cache pruning
  .github/workflows/ci.yaml
  .github/workflows/format.yml
  .github/workflows/publish.yml
Labels: TODO, enhancement, devops

#18107 OpenVINO broken link fix
  docs/en/guides/optimizing-openvino-latency-vs-throughput-modes.md
  docs/en/yolov5/tutorials/model_export.md
Labels: documentation, exports

#18111 `ultralytics 8.3.48` split PyPI publish jobs for security
  .github/workflows/publish.yml
  ultralytics/__init__.py
Labels: enhancement, devops

#18128 Update Jetson Doc with DLA info
  docs/en/guides/nvidia-jetson.md
Labels: documentation, embedded, exports

#18130 Update YOLOv5 export table links
  docs/en/yolov5/tutorials/model_export.md
Labels: documentation, exports

#18117 Update `torchvision` compatibility table
  ultralytics/utils/checks.py
Labels: enhancement, dependencies

#18140 Change index to start from 1 by default in `predictions.json`
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/obb/val.py
Labels: bug, detect

#18162 Remove Google Drive test
  tests/test_python.py
Labels: enhancement, devops

#18163 Git pull docs before updating
  .github/workflows/docs.yml
Labels: documentation, devops

#18115 `ultralytics 8.3.49` Docker images `uv pip install`
  docker/Dockerfile
  docker/Dockerfile-arm64
  docker/Dockerfile-cpu
  docker/Dockerfile-jetson-jetpack4
  docker/Dockerfile-jetson-jetpack5
  docker/Dockerfile-jetson-jetpack6
  docker/Dockerfile-python
  docker/Dockerfile-runner
  ultralytics/__init__.py
Labels: dependencies, devops

#18178 Removed duplicate IMX500 docs reference
  mkdocs.yml
Labels: documentation, embedded

#18168 Fix untrained warning when training from yaml
  ultralytics/engine/validator.py
Labels: bug, enhancement

#18174 Add YOLO11 audio podcast
  docs/en/models/yolo11.md
Labels: documentation, enhancement

#18207 Add https://youtu.be/qE-dfbB5Sis to docs
  docs/en/hub/datasets.md
  docs/en/hub/index.md
  docs/en/hub/quickstart.md
  docs/mkdocs_github_authors.yaml
Labels: documentation, enhancement, HUB

#18222 Add https://youtu.be/j0MOGKBqx7E to docs
  docs/en/guides/hyperparameter-tuning.md
Labels: documentation, enhancement

#18221 Add type for `train` arguments
  docs/en/guides/object-counting.md
  docs/en/guides/region-counting.md
  docs/en/macros/predict-args.md
  docs/en/macros/train-args.md
Labels: documentation, enhancement, detect

#18244 Fix Docs relative trailing backlash bug
  docs/build_docs.py
  docs/overrides/main.html
  mkdocs.yml
Labels: documentation, enhancement

#18212 Fix `model.save()` for model YAMLs
  ultralytics/engine/model.py
Labels: bug, fixed

#18171 `ultralytics 8.3.50` Enhanced segment resample
  ultralytics/__init__.py
  ultralytics/data/dataset.py
  ultralytics/utils/instance.py
  ultralytics/utils/ops.py
Labels: TODO, enhancement, segment

#18276 Update SAHI example from `YOLOv8` to `YOLO11`
  docs/en/guides/sahi-tiled-inference.md
  examples/YOLOv8-Region-Counter/readme.md
  examples/YOLOv8-SAHI-Inference-Video/readme.md
  examples/YOLOv8-SAHI-Inference-Video/yolov8_sahi.py
Labels: documentation, enhancement, research

#18254 Add `imx500` and `MNN` in `tutorial.ipynb` export table
  examples/tutorial.ipynb
Labels: documentation, exports

#18259 Add hyperparameter search space to Docs
  docs/en/guides/hyperparameter-tuning.md
Labels: documentation, enhancement

#18284 Use `shell=True` to run hyperparameter tuning
  ultralytics/engine/tuner.py
Labels: enhancement, detect

#18281 Add security alarm system as ultralytics solution
  docs/en/guides/security-alarm-system.md
  docs/en/macros/solutions-args.md
  docs/en/reference/solutions/security_alarm.md
  docs/en/solutions/index.md
  mkdocs.yml
  ultralytics/cfg/solutions/default.yaml
  ultralytics/solutions/__init__.py
  ultralytics/solutions/security_alarm.py
Labels: enhancement, solutions

#18283 `ultralytics 8.3.51` AutoBach logspace fit and checks
  ultralytics/__init__.py
  ultralytics/utils/autobatch.py
Labels: enhancement, devops

#18294 Revert `segment2box` and clip segments
  ultralytics/utils/ops.py
Labels: segment, detect

#18295 Update JetPack6 Dockerfile with latest JetPack6.1
  docker/Dockerfile-jetson-jetpack6
Labels: enhancement, dependencies, embedded

#18292 Add https://youtu.be/6bZeCs0xwO4 to docs
  docs/en/datasets/classify/cifar100.md
Labels: documentation, enhancement, classify

#18300 Align solutions YAML with `default.yaml`
  docs/en/solutions/index.md
  ultralytics/cfg/solutions/default.yaml
Labels: documentation, enhancement, solutions

#18303 Fix incorrect `scale` description
  docs/en/guides/model-training-tips.md
Labels: documentation, detect

#18289 Update Jetson doc with NVIDIA Jetson Orin Nano Super Developer Kit
  docs/en/guides/nvidia-jetson.md
Labels: TODO, documentation, enhancement, embedded

#18325 ROS Guide, updated YOLO version
  docs/en/guides/ros-quickstart.md
Labels: documentation, segment, detect

#18291 `ultralytics 8.3.52` AutoBatch CUDA computation improvements
  docs/en/reference/utils/torch_utils.md
  ultralytics/__init__.py
  ultralytics/utils/torch_utils.py
Labels: TODO, enhancement, devops

#18335 Fix JetPack6 Dockerfile for NVIDIA Jetson
  docker/Dockerfile-jetson-jetpack6
Labels: TODO, dependencies, devops, embedded

#18334 Improve JetPack5 Dockerfile for NVIDIA Jetson
  docker/Dockerfile-jetson-jetpack5
Labels: TODO, enhancement, dependencies, embedded

#18337 Validate arguments passed as dict to `settings.update()`
  ultralytics/utils/__init__.py
Labels: bug, enhancement

#18185 `ultralytics 8.3.53` New Export argument validation
  docs/en/reference/engine/exporter.md
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/utils/benchmarks.py
Labels: TODO, enhancement, exports

#18353 Add `dynamic` to approved OpenVINO export args
  docs/en/macros/export-table.md
  examples/tutorial.ipynb
  ultralytics/engine/exporter.py
Labels: enhancement, exports

#18360 Update `YOLOv8` to `YOLO11` in `region-counting.md`
  docs/en/guides/region-counting.md
Labels: documentation, enhancement

#18355 Min CI Python 3.9 from 3.8
  .github/workflows/ci.yaml
Labels: dependencies, devops

#18316 `ultralytics 8.3.54` New Streamlit inference Solution
  README.md
  docs/README.md
  docs/en/guides/streamlit-live-inference.md
  docs/en/reference/cfg/__init__.md
  docs/en/reference/solutions/streamlit_inference.md
  examples/RTDETR-ONNXRuntime-Python/main.py
  tests/test_solutions.py
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/solutions/__init__.py
  ultralytics/solutions/parking_management.py
  ultralytics/solutions/security_alarm.py
  ultralytics/solutions/streamlit_inference.py
Labels: documentation, enhancement, solutions

#18372 Use `Any` type-hints for `args` and `kwargs`
  docs/en/guides/streamlit-live-inference.md
  ultralytics/engine/model.py
  ultralytics/solutions/streamlit_inference.py
Labels: documentation, enhancement

#18377 Update FAQ examples in callbacks.md
  docs/en/usage/callbacks.md
Labels: documentation, enhancement

#18374 Add MobileSAM auto annotation feature 🚀
  docs/en/macros/sam-auto-annotate.md
  docs/en/models/mobile-sam.md
  docs/en/models/sam-2.md
  docs/en/models/sam.md
Labels: documentation, enhancement

#18391 Fix Docs calls to `model.benchmark()`
  docs/en/guides/nvidia-jetson.md
  docs/en/guides/raspberry-pi.md
  docs/en/integrations/openvino.md
  ultralytics/solutions/streamlit_inference.py
Labels: documentation, fixed

#18392 PyCharm Code Inspect fixes
  docs/en/datasets/obb/dota-v2.md
  docs/en/guides/coral-edge-tpu-on-raspberry-pi.md
  docs/en/guides/model-deployment-options.md
  docs/en/guides/model-testing.md
  docs/en/guides/workouts-monitoring.md
  docs/en/index.md
  docs/en/integrations/roboflow.md
  docs/en/integrations/vscode.md
  docs/en/macros/predict-args.md
  docs/en/macros/validation-args.md
  docs/en/usage/callbacks.md
  docs/en/yolov5/index.md
  docs/en/yolov5/tutorials/roboflow_datasets_integration.md
  tests/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/cfg/datasets/lvis.yaml
  ultralytics/cfg/solutions/default.yaml
  ultralytics/data/augment.py
  ultralytics/data/dataset.py
  ultralytics/data/scripts/download_weights.sh
  ultralytics/engine/exporter.py
  ultralytics/engine/model.py
  ultralytics/engine/validator.py
  ultralytics/models/sam/modules/tiny_encoder.py
  ultralytics/models/sam/predict.py
  ultralytics/nn/autobackend.py
  ultralytics/solutions/streamlit_inference.py
  ultralytics/utils/benchmarks.py
  ultralytics/utils/downloads.py
  ultralytics/utils/instance.py
  ultralytics/utils/plotting.py
Labels: documentation

#18394 Remove docs.yml fetch-depth 0
  .github/workflows/docs.yml
  docs/en/index.md
Labels: documentation, devops

#18396 Clone Docs `gh-pages` branch `--depth 1`
  .github/workflows/docs.yml
  docs/en/index.md
Labels: documentation, devops

#18395 Update image count information for COCO-Pose
  docs/en/datasets/pose/coco.md
  ultralytics/cfg/datasets/coco-pose.yaml
Labels: documentation, pose

#18393 PyCharm Code Inspect fixes for Solutions and Examples
  docs/en/guides/queue-management.md
  docs/en/guides/speed-estimation.md
  examples/YOLOv8-Region-Counter/yolov8_region_counter.py
  examples/YOLOv8-SAHI-Inference-Video/yolov8_sahi.py
  ultralytics/cfg/__init__.py
  ultralytics/solutions/analytics.py
  ultralytics/solutions/distance_calculation.py
  ultralytics/solutions/heatmap.py
  ultralytics/solutions/parking_management.py
  ultralytics/solutions/region_counter.py
  ultralytics/solutions/security_alarm.py
  ultralytics/solutions/solutions.py
  ultralytics/solutions/streamlit_inference.py
Labels: enhancement, solutions, devops

#18399 Simplify links.yml
  .github/workflows/links.yml
Labels: enhancement, devops

#18398 Code scan fixes
  docs/en/models/rtdetr.md
  docs/en/models/yolo-world.md
  docs/en/models/yolov7.md
  docs/en/models/yolov9.md
  ultralytics/solutions/security_alarm.py
Labels: documentation, enhancement

#18400 Restrict ONNX ExecutionProviders
  .github/workflows/ci.yaml
  tests/conftest.py
  tests/test_cli.py
  tests/test_python.py
  tests/test_solutions.py
  ultralytics/nn/autobackend.py
Labels: enhancement, exports

#18410 Update yolo11n-pose to yolo11n in `speed-estimation.md`
  docs/en/guides/speed-estimation.md
Labels: documentation, enhancement

#18389 `ultralytics 8.3.55` New Medical-pills dataset
  docs/en/datasets/detect/index.md
  docs/en/datasets/detect/medical-pills.md
  docs/en/datasets/index.md
  mkdocs.yml
  ultralytics/__init__.py
  ultralytics/cfg/datasets/medical-pills.yaml
Labels: documentation, enhancement, detect

#18427 Fix Path objects lacking split method
  ultralytics/cfg/__init__.py
Labels: bug, fixed

#18434 Fix Docs `depth: 1` missing authors
  .github/workflows/docs.yml
Labels: documentation, devops

#18436 Fix checkout action arg `fetch-depth`
  .github/workflows/docs.yml
Labels: documentation, devops

#18431 Align Guides headings with mkdocs
  .github/workflows/docs.yml
  docs/en/guides/index.md
Labels: documentation, enhancement

#18432 PyCharm Docs Inspect fixes
  docs/en/datasets/classify/fashion-mnist.md
  docs/en/guides/coral-edge-tpu-on-raspberry-pi.md
  docs/en/guides/model-evaluation-insights.md
  docs/en/guides/model-monitoring-and-maintenance.md
  docs/en/help/FAQ.md
  docs/en/integrations/ibm-watsonx.md
  docs/en/integrations/kaggle.md
  docs/en/integrations/ncnn.md
  docs/en/integrations/weights-biases.md
  docs/en/usage/simple-utilities.md
  examples/YOLOv8-CPP-Inference/README.md
  examples/YOLOv8-LibTorch-CPP-Inference/README.md
  examples/YOLOv8-OpenVINO-CPP-Inference/README.md
  ultralytics/models/sam/predict.py
  ultralytics/utils/plotting.py
Labels: documentation, enhancement

#18459 Replace explorer notebook with `explorer.md` docs page
  .github/workflows/docs.yml
  docs/en/datasets/explorer/explorer.ipynb
  docs/en/datasets/explorer/explorer.md
  mkdocs.yml
  pyproject.toml
Labels: documentation, enhancement

#18456 Add missing `.pt` extension to filenames
  docs/en/models/yolov9.md
Labels: documentation

#18444 Update Jetson Doc with `torch` and `torchvision` for JetPack 5.1.2
  docs/en/guides/nvidia-jetson.md
Labels: TODO, documentation, embedded

#18443 Update DeepStream Doc with YOLO11 and DeepStream 7.1
  docs/en/guides/deepstream-nvidia-jetson.md
Labels: TODO, documentation, detect, exports

#18450 Update information about YOLOv6 pretrained weights
  docs/en/models/yolov6.md
Labels: documentation, detect

#18445 Delete `clip_model` to avoid errors on export
  ultralytics/engine/exporter.py
Labels: bug, exports

#18411 Add `TrackZone` test in `test_solutions.py`
  tests/test_solutions.py
Labels: enhancement, solutions

#18460 Add note that IMX export is only supported for YOLOv8n
  docs/en/integrations/sony-imx500.md
  ultralytics/engine/exporter.py
Labels: enhancement, detect, exports

#18467 Bump maximum version for onnx2tf to 1.26.3
  ultralytics/engine/exporter.py
Labels: enhancement, dependencies, exports

#18468 `ultralytics 8.3.56` PaddlePaddle GPU Inference support
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: enhancement, exports
