Repository ultralytics/ultralytics, pull requests merged in 2024-06, with the labels that each got.

#13324 Fix Docs export table from `onnxsim` to `onnxslim`
  docs/en/modes/export.md
Labels: documentation

#13391 Add area chart in `analytics`
  docs/en/guides/analytics.md
  ultralytics/solutions/analytics.py
Labels: documentation, solutions

#13370 Clean up Docs pages
  docs/en/datasets/segment/index.md
  docs/en/guides/conda-quickstart.md
Labels: documentation

#13389 Search for model metadata with TensorFlow GraphDef
  ultralytics/nn/autobackend.py
Labels: enhancement

#13380 Add https://youtu.be/pWYiene9lYw & https://youtu.be/Unt4Lfid7aY to docs
  docs/en/hub/models.md
  docs/en/integrations/gradio.md
Labels: documentation

#13340 Feature: Fractional Auto-batch
  docs/en/modes/train.md
  docs/en/usage/cfg.md
Labels: enhancement

#13555 Add https://youtu.be/ydGdibB5Mds to docs
  docs/en/guides/object-blurring.md
  docs/en/guides/object-cropping.md
Labels: documentation, enhancement

#13504 `ultralytics 8.2.35` add YOLOv9t/s/m models
  docs/en/models/yolov9.md
  docs/en/reference/nn/modules/block.md
  tests/test_cuda.py
  ultralytics/__init__.py
  ultralytics/cfg/models/v9/yolov9m.yaml
  ultralytics/cfg/models/v9/yolov9s.yaml
  ultralytics/cfg/models/v9/yolov9t.yaml
  ultralytics/nn/modules/__init__.py
  ultralytics/nn/modules/block.py
  ultralytics/nn/tasks.py
Labels: TODO, enhancement

#13553 ROS Quickstart Guide
  CONTRIBUTING.md
  docs/en/guides/index.md
  docs/en/guides/ros-quickstart.md
  docs/en/guides/security-alarm-system.md
  docs/en/integrations/amazon-sagemaker.md
  docs/en/integrations/gradio.md
  docs/en/usage/simple-utilities.md
  docs/en/yolov5/tutorials/architecture_description.md
  docs/en/yolov5/tutorials/hyperparameter_evolution.md
  docs/mkdocs_github_authors.yaml
  mkdocs.yml
Labels: TODO, documentation

#13797 https://youtu.be/biIW5Z6GYl0 to docs
  docs/en/datasets/detect/african-wildlife.md
Labels: documentation, enhancement

#13785 Deprecate `Silence` module in favor of `nn.Identity`
  ultralytics/nn/tasks.py
Labels: fixed

#13808 `ultralytics 8.2.36` update Ultralytics color palette
  ultralytics/__init__.py
  ultralytics/utils/plotting.py
Labels: enhancement, HUB, OBB, segment, detect, pose, solutions

#13835 ROS quickstart Docs page cleanup
  README.md
  README.zh-CN.md
  docs/en/guides/ros-quickstart.md
  docs/en/integrations/tensorrt.md
  docs/en/integrations/weights-biases.md
  docs/en/models/yolov9.md
  docs/en/usage/cli.md
Labels: documentation

#13113 `ultralytics 8.2.38` official YOLOv10 support
  .github/workflows/ci.yaml
  docs/en/models/yolov10.md
  docs/en/reference/nn/modules/block.md
  docs/en/reference/nn/modules/head.md
  docs/en/reference/utils/loss.md
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/cfg/models/v10/yolov10b.yaml
  ultralytics/cfg/models/v10/yolov10l.yaml
  ultralytics/cfg/models/v10/yolov10m.yaml
  ultralytics/cfg/models/v10/yolov10n.yaml
  ultralytics/cfg/models/v10/yolov10s.yaml
  ultralytics/cfg/models/v10/yolov10x.yaml
  ultralytics/engine/exporter.py
  ultralytics/nn/modules/__init__.py
  ultralytics/nn/modules/block.py
  ultralytics/nn/modules/head.py
  ultralytics/nn/tasks.py
  ultralytics/utils/benchmarks.py
  ultralytics/utils/downloads.py
  ultralytics/utils/loss.py
  ultralytics/utils/metrics.py
  ultralytics/utils/ops.py
Labels: enhancement

#13855 ROS Quickstart, fixed code formatting
  docs/en/guides/ros-quickstart.md
Labels: documentation

#13867 Add https://youtu.be/tq3FU_QczxE to docs
  docs/en/guides/sahi-tiled-inference.md
Labels: documentation, enhancement

#13103 Fix HUB session with DDP training
  ultralytics/engine/trainer.py
  ultralytics/hub/session.py
  ultralytics/utils/callbacks/hub.py
  ultralytics/utils/dist.py
  ultralytics/utils/torch_utils.py
Labels: bug, HUB

#13940 Add CLI commands for `predict` and `train` YOLOv10 models.
  docs/en/models/yolov10.md
Labels: documentation, enhancement

#13971 `ultralytics 8.2.43` enable `classes` filter for end2end models
  ultralytics/__init__.py
  ultralytics/utils/ops.py
Labels: fixed

#14011 Add Tips for Model Training Docs Page
  docs/en/guides/index.md
  docs/en/guides/model-training-tips.md
  docs/en/models/yolov10.md
  mkdocs.yml
Labels: documentation, enhancement

#14077 Add https://youtu.be/eX5ad6udQ9Q to docs
  docs/en/datasets/classify/fashion-mnist.md
Labels: documentation, enhancement

#14074 `ultralytics 8.2.46` Results, DFL and AIGym fixes
  docs/en/guides/workouts-monitoring.md
  docs/mkdocs_github_authors.yaml
  ultralytics/cfg/default.yaml
  ultralytics/cfg/models/v10/yolov10b.yaml
  ultralytics/cfg/models/v10/yolov10l.yaml
  ultralytics/cfg/models/v10/yolov10m.yaml
  ultralytics/cfg/models/v10/yolov10n.yaml
  ultralytics/cfg/models/v10/yolov10s.yaml
  ultralytics/cfg/models/v10/yolov10x.yaml
  ultralytics/solutions/ai_gym.py
Labels: bug, solutions

#13935 `ultralytics 8.2.47` YOLOv8 zero-shot action recognition example
  examples/YOLOv8-Action-Recognition/action_recognition.py
  examples/YOLOv8-Action-Recognition/readme.md
  examples/YOLOv8-Action-Recognition/requirements.txt
  ultralytics/__init__.py
Labels: TODO, enhancement, external, track, detect
