Repository ultralytics/ultralytics, pull requests merged in 2024-04, with the labels that each got.

#9468 Fix learning rate gap on resume
  ultralytics/engine/trainer.py
  ultralytics/utils/torch_utils.py
Labels: enhancement

#9899 OBB: Fix distorted plotting
  ultralytics/data/augment.py
  ultralytics/utils/plotting.py
Labels: enhancement, OBB

#9516 `ultralytics 8.1.46` add TensorRT 10 support
  tests/test_cuda.py
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: enhancement, dependencies

#9954 `ultralytics 8.1.47` PNNX release 20240226
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: fixed

#10014 Add https://youtu.be/SArFQs6CHwk to docs
  docs/en/models/rtdetr.md
  ultralytics/data/augment.py
  ultralytics/data/base.py
  ultralytics/data/build.py
  ultralytics/data/dataset.py
  ultralytics/data/explorer/explorer.py
  ultralytics/models/fastsam/model.py
  ultralytics/models/nas/model.py
  ultralytics/models/rtdetr/train.py
  ultralytics/models/sam/build.py
  ultralytics/models/sam/model.py
  ultralytics/models/sam/predict.py
  ultralytics/models/utils/loss.py
  ultralytics/nn/modules/head.py
  ultralytics/trackers/byte_tracker.py
  ultralytics/trackers/track.py
  ultralytics/utils/callbacks/base.py
  ultralytics/utils/loss.py
  ultralytics/utils/plotting.py
Labels: documentation

#9998 Fix increment `+=2` bug in object_counter.py
  ultralytics/solutions/object_counter.py
Labels: bug, fixed

#10058 Update Docs for YOLO-World Training ✅
  docs/en/models/yolo-world.md
  ultralytics/hub/session.py
Labels: documentation

#10044 Parameterize `kpts` plotting `conf=0.25`
  ultralytics/utils/plotting.py
Labels: enhancement

#8828 Raspberry Pi 5 self-hosted CI
  .github/workflows/ci.yaml
  pyproject.toml
  tests/test_python.py
  ultralytics/nn/autobackend.py
  ultralytics/utils/benchmarks.py
Labels: enhancement, devops

#10189 Reboot RPi CI to fix an issue
  .github/workflows/ci.yaml
Labels: devops

#10192 Update train.md
  docs/en/modes/train.md
Labels: documentation

#10241 Add Paperspace Integrations Page
  docs/en/integrations/index.md
  docs/en/integrations/paperspace.md
  mkdocs.yml
Labels: documentation

#10190 Add benchmarking for RF100 datasets
  docs/en/datasets/detect/roboflow-100.md
  ultralytics/utils/benchmarks.py
Labels: documentation

#10292 Add https://youtu.be/uZ7SymQfqKI and track docs updates
  docs/en/modes/track.md
  docs/en/tasks/obb.md
Labels: documentation

#10279 Add Google Colab Integrations Docs Page
  docs/en/integrations/google-colab.md
  docs/en/integrations/index.md
  mkdocs.yml
Labels: documentation

#10358 Update predict.md to add .obb result prop
  docs/en/modes/predict.md
Labels: documentation

#10269 Add export `batch` arg to Docs
  docs/en/hub/integrations.md
  docs/en/integrations/index.md
  docs/en/modes/benchmark.md
  docs/en/modes/export.md
  docs/en/tasks/classify.md
  docs/en/tasks/detect.md
  docs/en/tasks/obb.md
  docs/en/tasks/pose.md
  docs/en/tasks/segment.md
  docs/en/usage/cli.md
Labels: documentation

#10333 `ultralytics 8.2.4` ByteTracker threshold improvements
  README.md
  README.zh-CN.md
  ultralytics/__init__.py
  ultralytics/trackers/byte_tracker.py
Labels: enhancement, track

#10385 `ultralytics 8.2.5` New 🌟 Parking Management Solution
  docs/en/datasets/detect/roboflow-100.md
  docs/en/guides/index.md
  docs/en/guides/parking-management.md
  docs/en/reference/solutions/parking_management.md
  mkdocs.yml
  ultralytics/__init__.py
  ultralytics/solutions/heatmap.py
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/parking_management.py
  ultralytics/utils/plotting.py
Labels: documentation, enhancement, solutions
