Repository ultralytics/ultralytics, pull requests merged in 2024-02, with the labels that each got.

#7944 Add https://youtu.be/96NkhsV-W1U to docs and `heatmaps` fix
  docs/en/guides/index.md
  ultralytics/solutions/heatmap.py
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/speed_estimation.py
Labels: bug, solutions

#7979 Add guide on how to use the Coral Usb Accelerator with Raspberry Pi's
  docs/en/integrations/coral-edge-tpu-on-raspberry-pi.md
  docs/en/integrations/index.md
  mkdocs.yml
Labels: documentation

#8160 Improve Coral Edge TPU guide
  docs/en/guides/coral-edge-tpu-on-raspberry-pi.md
Labels: documentation

#8054 `ultralytics 8.1.14` new YOLOv8-World models
  docs/en/models/index.md
  docs/en/models/yolo-world.md
  docs/mkdocs_github_authors.yaml
  mkdocs.yml
  ultralytics/__init__.py
  ultralytics/cfg/models/v8/yolov8-world-t2i.yaml
  ultralytics/cfg/models/v8/yolov8-world.yaml
  ultralytics/engine/exporter.py
  ultralytics/models/__init__.py
  ultralytics/models/fastsam/prompt.py
  ultralytics/models/yolo/__init__.py
  ultralytics/models/yolo/model.py
  ultralytics/nn/modules/__init__.py
  ultralytics/nn/modules/block.py
  ultralytics/nn/modules/head.py
  ultralytics/nn/tasks.py
  ultralytics/utils/__init__.py
  ultralytics/utils/downloads.py
  ultralytics/utils/plotting.py
Labels: enhancement

#8205 Add Python 3.12 compatibility
  .github/workflows/ci.yaml
  pyproject.toml
  tests/test_python.py
  ultralytics/utils/benchmarks.py
  ultralytics/utils/checks.py
Labels: enhancement

#8210 `ultralytics 8.1.15` add Python 3.12 compatibility
  .github/workflows/ci.yaml
  pyproject.toml
  tests/test_cli.py
  tests/test_integrations.py
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/engine/trainer.py
  ultralytics/utils/benchmarks.py
  ultralytics/utils/callbacks/wb.py
  ultralytics/utils/checks.py
  ultralytics/utils/ops.py
  ultralytics/utils/torch_utils.py
Labels: enhancement

#8299 `ultralytics 8.1.16` OBB ConfusionMatrix support
  .github/workflows/docker.yaml
  docker/Dockerfile
  docker/Dockerfile-cpu
  docker/Dockerfile-python
  docs/en/modes/train.md
  docs/en/usage/cfg.md
  ultralytics/__init__.py
  ultralytics/cfg/default.yaml
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/obb/val.py
  ultralytics/utils/downloads.py
  ultralytics/utils/metrics.py
Labels: enhancement, OBB

#8269 Add simple-utilities.md Docs page
  docs/README.md
  docs/en/usage/simple-utilities.md
  mkdocs.yml
Labels: documentation

#8415 Improve Docs arguments tables
  docs/en/modes/export.md
  docs/en/modes/train.md
  docs/en/modes/val.md
  docs/en/usage/cfg.md
Labels: documentation

#8477 Use `zip` or `tarfile` for `classify` task
  ultralytics/data/utils.py
Labels: bug, HUB, classify

#8501 Add TorchScript Docs Integrations Page
  docs/build_docs.py
  docs/en/integrations/index.md
  docs/en/integrations/torchscript.md
  mkdocs.yml
  ultralytics/data/explorer/gui/dash.py
  ultralytics/engine/exporter.py
  ultralytics/engine/predictor.py
  ultralytics/engine/tuner.py
  ultralytics/engine/validator.py
Labels: documentation, external

#8525 Do RTDETR file suffix check using pathlib instead of string manipulations
  ultralytics/models/rtdetr/model.py
Labels: enhancement

#8522 Add TFLite Docs Integrations Page
  docs/en/integrations/index.md
  docs/en/integrations/tflite.md
  mkdocs.yml
Labels: documentation, external

#8553 Fix undefined ‘im_array’ bug in predict.md
  docs/en/modes/predict.md
Labels: documentation
