Repository ultralytics/ultralytics, pull requests merged in 2025-04, with the labels that each got.

#19963 YOLOE: Prevent original prompts from being modified
  ultralytics/models/yolo/model.py
Labels: enhancement, detect

#19969 YOLOE: Preserve task type with refer_image
  ultralytics/models/yolo/model.py
Labels: enhancement, segment, detect

#19902 `ultralytics 8.3.100` New `paddlepaddle>=3.0.0` with `*.pdiparams`
  docker/Dockerfile
  docker/Dockerfile-cpu
  docker/Dockerfile-python
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
  ultralytics/utils/benchmarks.py
Labels: enhancement, dependencies

#19981 YOLOE: Fix visual prompt usage in docs
  docs/en/models/yoloe.md
Labels: TODO, documentation, detect

#19988 YOLOE: Fix simplify with dynamic export
  docs/mkdocs_github_authors.yaml
  ultralytics/nn/tasks.py
Labels: enhancement, exports

#19985 YOLOE: Fix Linear Probing example
  docs/en/models/yoloe.md
Labels: TODO, documentation

#19959 `ultralytics 8.3.101` YOLOE visual prompt inference fix for video sources
  docs/en/models/yoloe.md
  ultralytics/__init__.py
  ultralytics/models/yolo/model.py
Labels: enhancement, detect

#19998 Remove verbose `build_text_model` log
  ultralytics/nn/text_model.py
Labels: documentation, enhancement

#20001 Update GNU links
  CONTRIBUTING.md
  docs/en/help/contributing.md
  examples/YOLOv8-Segmentation-ONNXRuntime-Python/README.md
Labels: documentation

#19952 Add `fraction` argument support for export dataloader
  docs/en/integrations/openvino.md
  docs/en/integrations/sony-imx500.md
  docs/en/integrations/tensorrt.md
  docs/en/integrations/tflite.md
  docs/en/macros/export-args.md
  docs/en/macros/export-table.md
  examples/tutorial.ipynb
  ultralytics/engine/exporter.py
Labels: TODO, enhancement, exports

#20003 Remove MkDocs redirects
  .github/workflows/docs.yml
  mkdocs.yml
  pyproject.toml
Labels: documentation

#20006 Remove all `gh-pages` files except vercel.json
  .github/workflows/docs.yml
  docs/build_docs.py
Labels: documentation, devops

#20007 Fix docs.yml vercel.json handling
  .github/workflows/docs.yml
Labels: documentation, devops

#20011 YOLOE: Remove unused argument `max_det`
  ultralytics/nn/modules/head.py
Labels: enhancement, detect

#20012 YOLOE: Bypass source check when `source` is None
  ultralytics/models/yolo/model.py
Labels: enhancement, detect

#20017 Update `models/` docstrings
  docs/en/yolov5/environments/aws_quickstart_tutorial.md
  docs/en/yolov5/environments/azureml_quickstart_tutorial.md
  docs/en/yolov5/environments/docker_image_quickstart_tutorial.md
  docs/en/yolov5/environments/google_cloud_quickstart_tutorial.md
  docs/en/yolov5/index.md
  docs/en/yolov5/quickstart_tutorial.md
  docs/en/yolov5/tutorials/transfer_learning_with_frozen_layers.md
  tests/test_solutions.py
  ultralytics/hub/__init__.py
  ultralytics/hub/google/__init__.py
  ultralytics/models/fastsam/predict.py
  ultralytics/models/nas/predict.py
  ultralytics/models/rtdetr/val.py
  ultralytics/models/sam/amg.py
  ultralytics/models/sam/modules/encoders.py
  ultralytics/models/sam/modules/memory_attention.py
  ultralytics/models/sam/modules/utils.py
  ultralytics/models/utils/loss.py
  ultralytics/models/utils/ops.py
  ultralytics/models/yolo/classify/predict.py
  ultralytics/models/yolo/classify/train.py
  ultralytics/models/yolo/classify/val.py
  ultralytics/models/yolo/detect/predict.py
  ultralytics/models/yolo/model.py
  ultralytics/models/yolo/obb/predict.py
  ultralytics/models/yolo/obb/train.py
  ultralytics/models/yolo/obb/val.py
  ultralytics/models/yolo/pose/predict.py
  ultralytics/models/yolo/pose/train.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/models/yolo/segment/predict.py
  ultralytics/models/yolo/segment/train.py
  ultralytics/models/yolo/segment/val.py
  ultralytics/models/yolo/world/train_world.py
  ultralytics/models/yolo/yoloe/train.py
  ultralytics/nn/modules/activation.py
  ultralytics/nn/modules/utils.py
  ultralytics/nn/text_model.py
  ultralytics/utils/callbacks/base.py
  ultralytics/utils/callbacks/comet.py
  ultralytics/utils/callbacks/dvc.py
  ultralytics/utils/callbacks/neptune.py
  ultralytics/utils/callbacks/tensorboard.py
  ultralytics/utils/callbacks/wb.py
  ultralytics/utils/dist.py
  ultralytics/utils/errors.py
  ultralytics/utils/patches.py
  ultralytics/utils/triton.py
Labels: documentation

#20020 Add https://youtu.be/HMOoM2NwFIQ to docs
  docs/en/models/yoloe.md
Labels: documentation, segment

#20010 `ultralytics 8.3.102` YOLOE module refactor
  docs/en/reference/nn/modules/block.md
  docs/en/reference/nn/modules/head.md
  ultralytics/__init__.py
  ultralytics/nn/modules/block.py
  ultralytics/nn/modules/head.py
Labels: enhancement, detect

#20024 YOLOE: Add assert in `set_classes` to check prompt-free models
  docs/en/integrations/mlflow.md
  docs/en/modes/train.md
  ultralytics/nn/tasks.py
Labels: bug, enhancement

#20025 Improve `instance-segmentation` mask plotting
  docs/en/usage/simple-utilities.md
  ultralytics/solutions/instance_segmentation.py
  ultralytics/solutions/solutions.py
Labels: documentation, enhancement, segment, solutions

#20030 Truncate long Docs meta titles
  docs/build_docs.py
  docs/coming_soon_template.md
  docs/en/datasets/detect/globalwheat2020.md
  docs/en/datasets/detect/xview.md
  docs/en/datasets/explorer/api.md
  docs/en/datasets/explorer/dashboard.md
  docs/en/datasets/explorer/index.md
  docs/en/datasets/pose/coco8-pose.md
  docs/en/datasets/pose/dog-pose.md
  docs/en/datasets/segment/coco8-seg.md
  docs/en/datasets/segment/package-seg.md
  docs/en/guides/azureml-quickstart.md
  docs/en/guides/model-deployment-practices.md
  docs/en/guides/model-training-tips.md
  docs/en/guides/nvidia-jetson.md
  docs/en/guides/parking-management.md
  docs/en/guides/streamlit-live-inference.md
  docs/en/hub/api/index.md
  docs/en/hub/app/android.md
  docs/en/hub/integrations.md
  docs/en/integrations/edge-tpu.md
  docs/en/integrations/mnn.md
  docs/en/integrations/ncnn.md
  docs/en/integrations/neural-magic.md
  docs/en/integrations/paddlepaddle.md
  docs/en/integrations/paperspace.md
  docs/en/integrations/tensorrt.md
  docs/en/integrations/tf-graphdef.md
  docs/en/integrations/tf-savedmodel.md
  docs/en/integrations/tfjs.md
  docs/en/integrations/tflite.md
  docs/en/integrations/torchscript.md
  docs/en/integrations/weights-biases.md
  docs/en/models/mobile-sam.md
  docs/en/models/rtdetr.md
  docs/en/models/sam.md
  docs/en/yolov5/tutorials/clearml_logging_integration.md
  docs/en/yolov5/tutorials/test_time_augmentation.md
Labels: documentation

#20028 Fix `solutions` tests by pinning `shapely<2.1.0` and `streamlit<1.44.0`
  pyproject.toml
  ultralytics/cfg/__init__.py
  ultralytics/solutions/solutions.py
Labels: dependencies, devops

#20035 Fix inconsistent value of max F1 conf from `F1_curve.png` caused by `f` value for `smooth` function in `plot_mc_curve`
  ultralytics/utils/metrics.py
Labels: bug, enhancement

#20040 Improve FLOPs docs
  examples/YOLOv8-Action-Recognition/README.md
  examples/YOLOv8-ONNXRuntime-CPP/README.md
  examples/YOLOv8-TFLite-Python/README.md
  ultralytics/nn/autobackend.py
  ultralytics/utils/torch_utils.py
Labels: documentation, enhancement

#20041 Increase CoreML specificationVersion 5 -> 9
  ultralytics/engine/exporter.py
Labels: enhancement, exports

#20042 CoreML `minimum_deployment_target=ct.target.iOS15`
  docs/en/yolov5/tutorials/train_custom_data.md
  tests/test_exports.py
  ultralytics/engine/exporter.py
Labels: enhancement, exports

#20037 `ultralytics 8.3.103` New RayTune `resume=True` functionality
  docs/en/guides/hyperparameter-tuning.md
  docs/en/integrations/ray-tune.md
  ultralytics/__init__.py
  ultralytics/engine/tuner.py
  ultralytics/utils/tuner.py
Labels: enhancement, devops

#20050 YOLOE: Fix validation when model loading from local file
  ultralytics/models/yolo/yoloe/val.py
Labels: enhancement, detect

#19768 Add `device` argument to Sony `imx` export
  docs/en/integrations/sony-imx500.md
  docs/en/macros/export-table.md
  examples/tutorial.ipynb
  ultralytics/engine/exporter.py
Labels: TODO, enhancement, embedded, exports

#20059 Fix YOLOv8-ONNXRuntime example links
  examples/YOLOv8-MNN-CPP/README.md
  examples/YOLOv8-ONNXRuntime-CPP/README.md
  examples/YOLOv8-ONNXRuntime/README.md
Labels: documentation, exports

#20046 YOLOE explicit source `is not None` check
  ultralytics/__init__.py
  ultralytics/models/yolo/model.py
Labels: enhancement, detect

#20073 Add support to adjust text background size in `ObjectCounter` with `line_width`
  tests/test_solutions.py
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/solutions.py
Labels: enhancement, detect

#20009 Add `device` argument to all exports
  docs/en/integrations/coreml.md
  docs/en/integrations/edge-tpu.md
  docs/en/integrations/mnn.md
  docs/en/integrations/ncnn.md
  docs/en/integrations/onnx.md
  docs/en/integrations/openvino.md
  docs/en/integrations/paddlepaddle.md
  docs/en/integrations/rockchip-rknn.md
  docs/en/integrations/tensorrt.md
  docs/en/integrations/tf-graphdef.md
  docs/en/integrations/tf-savedmodel.md
  docs/en/integrations/tfjs.md
  docs/en/integrations/tflite.md
  docs/en/integrations/torchscript.md
  docs/en/macros/export-table.md
  examples/tutorial.ipynb
Labels: TODO, documentation, enhancement, exports

#20079 Remove top-level `tests` directory in package distribution
  pyproject.toml
Labels: enhancement, dependencies

#20087 Fix broken link in `albumentations.md`
  docs/en/integrations/albumentations.md
Labels: documentation

#20106 Remove `uv` from tutorial.ipynb
  examples/tutorial.ipynb
Labels: documentation, Notebook

#20100 `ultralytics 8.3.106` iOS14+ CoreML `mlmodel` and `mlpackage` joint support
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
Labels: enhancement, detect, exports

#20112 Pin `openvino<2025.0.0` to fix OpenVINO export issue on macOS
  pyproject.toml
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: dependencies, exports

#20109 Use shorter trial names for Ray Tune
  ultralytics/utils/tuner.py
Labels: enhancement, devops

#20126 Revert CI runners to macOS 14 to avoid OpenVINO bug on macOS 15.4
  .github/workflows/ci.yml
  pyproject.toml
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
  ultralytics/utils/__init__.py
Labels: devops, exports

#20110 Enable `solutions` tests for each PR
  tests/test_solutions.py
Labels: solutions, devops

#20096 Add missing batchnorm `dtype` arg
  ultralytics/utils/torch_utils.py
Labels: enhancement, dependencies

#20074 Add standalone export functions for onnx and tensorrt formats
  docs/en/reference/utils/export.md
  ultralytics/engine/exporter.py
  ultralytics/utils/export.py
Labels: enhancement, exports

#20125 `ultralytics 8.3.107` Rockchip RKNN `Autobackend` fix
  ultralytics/__init__.py
  ultralytics/nn/autobackend.py
Labels: dependencies, exports

#20127 Fix Solutions warnings
  tests/test_solutions.py
  ultralytics/data/dataset.py
  ultralytics/solutions/solutions.py
  ultralytics/solutions/speed_estimation.py
  ultralytics/utils/metrics.py
Labels: pose, solutions

#20137 Disable Solutions test
  tests/test_solutions.py
Labels: solutions, devops

#20145 Improve headers, redirects and example READMEs
  README.md
  README.zh-CN.md
  docs/README.md
  docs/en/datasets/explorer/explorer.md
  docs/en/hub/api/index.md
  docs/en/hub/index.md
  docs/en/hub/integrations.md
  docs/en/index.md
  docs/en/integrations/albumentations.md
  docs/en/integrations/vscode.md
  docs/en/yolov5/environments/aws_quickstart_tutorial.md
  docs/en/yolov5/environments/docker_image_quickstart_tutorial.md
  docs/en/yolov5/environments/google_cloud_quickstart_tutorial.md
  docs/en/yolov5/index.md
  docs/overrides/javascript/tablesort.js
  examples/YOLO-Interactive-Tracking-UI/README.md
  examples/YOLOv8-CPP-Inference/inference.cpp
  examples/YOLOv8-CPP-Inference/inference.h
  examples/YOLOv8-CPP-Inference/main.cpp
  examples/YOLOv8-MNN-CPP/README.md
  examples/YOLOv8-MNN-CPP/main.cpp
  examples/YOLOv8-MNN-CPP/main_interpreter.cpp
  examples/YOLOv8-ONNXRuntime-CPP/inference.cpp
  examples/YOLOv8-ONNXRuntime-CPP/inference.h
  examples/YOLOv8-ONNXRuntime-CPP/main.cpp
  examples/YOLOv8-OpenVINO-CPP-Inference/inference.h
  examples/YOLOv8-TFLite-Python/README.md
  pyproject.toml
  ultralytics/data/dataset.py
  ultralytics/nn/modules/head.py
  ultralytics/utils/callbacks/raytune.py
  ultralytics/utils/export.py
Labels: documentation, HUB

#20149 Add https://youtu.be/q1tXfShvbAw to docs
  docs/en/guides/defining-project-goals.md
Labels: documentation

#20146 Deprecate `crop_fraction` parameter
  docs/mkdocs_github_authors.yaml
  examples/tutorial.ipynb
  ultralytics/cfg/__init__.py
  ultralytics/cfg/default.yaml
  ultralytics/data/augment.py
  ultralytics/data/dataset.py
  ultralytics/engine/predictor.py
Labels: documentation, enhancement, classify

#20153 Fix Comet error during COCO validation
  ultralytics/utils/callbacks/comet.py
Labels: bug, enhancement

#20157 Fix `hub/pro.md` docs page indentation issues
  docs/en/hub/pro.md
Labels: documentation, HUB

#20158 Align code examples in `yolo-data-augmentation` page
  docs/en/guides/yolo-data-augmentation.md
Labels: documentation

#19946 `ultralytics 8.3.108` YOLO11 Sony IMX export
  docs/en/integrations/sony-imx500.md
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: TODO, enhancement, detect, exports

#20167 Remove unreachable CoreML Classify model logic
  ultralytics/engine/exporter.py
Labels: enhancement, classify, exports

#20173 AutoBatch: Revert polynomial fitting logic
  ultralytics/utils/autobatch.py
Labels: enhancement

#20179 Reduce trigger threshold to clear GPU memory to 50%
  ultralytics/engine/trainer.py
Labels: bug, enhancement

#20181 Update links.yml with `set -o pipefail`
  .github/workflows/links.yml
  docs/en/integrations/vscode.md
Labels: documentation, devops

#20174 Enable Solutions tests, except on `Linux (Python 3.11)` and `Raspberry PI` due to `--slow` test errors
  tests/test_solutions.py
  ultralytics/utils/checks.py
Labels: enhancement, solutions, devops

#20175 `ultralytics 8.3.109` Add `conf` filter to RT-DETR validator
  ultralytics/__init__.py
  ultralytics/models/rtdetr/val.py
Labels: enhancement, detect

#20186 Include bash scripts in installation
  pyproject.toml
Labels: enhancement, dependencies

#20184 Improve hashing speed
  ultralytics/data/utils.py
Labels: enhancement

#20197 `ultralytics 8.3.110` New dataset file access speed checks
  docs/en/help/code-of-conduct.md
  docs/en/models/yoloe.md
  docs/en/reference/data/utils.md
  docs/en/yolov5/environments/google_cloud_quickstart_tutorial.md
  docs/overrides/main.html
  ultralytics/__init__.py
  ultralytics/data/base.py
  ultralytics/data/dataset.py
  ultralytics/data/utils.py
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
  ultralytics/nn/modules/block.py
  ultralytics/nn/modules/conv.py
  ultralytics/solutions/parking_management.py
  ultralytics/utils/dist.py
  ultralytics/utils/metrics.py
Labels: enhancement, detect

#20205 Explicit shape handling for dynamic YOLO-World exports to TensorRT
  ultralytics/nn/modules/block.py
Labels: enhancement, exports

#20210 Update links.yml to ignore TIMEOUT issues
  .github/workflows/links.yml
Labels: documentation, devops

#20213 Default `tensorboard=False` for speed
  examples/tutorial.ipynb
  tests/test_integrations.py
  ultralytics/data/augment.py
  ultralytics/nn/autobackend.py
  ultralytics/utils/__init__.py
Labels: documentation, enhancement

#20193 `ultralytics 8.3.111` YOLOv10 skip `one2many` head when fused
  examples/tutorial.ipynb
  ultralytics/__init__.py
  ultralytics/nn/modules/head.py
  ultralytics/nn/tasks.py
Labels: enhancement, detect

#20219 Update MobileSAM documentation
  docs/en/models/mobile-sam.md
  ultralytics/utils/torch_utils.py
Labels: documentation, embedded

#20218 Add https://youtu.be/ENQXiK7HF5o to docs
  docs/en/usage/callbacks.md
Labels: documentation

#20221 New COCO8-Multispectral dataset
  docs/en/datasets/detect/coco8-multispectral.md
  docs/en/datasets/detect/coco8.md
  docs/en/datasets/detect/index.md
  docs/en/reference/data/converter.md
  mkdocs.yml
  ultralytics/cfg/datasets/coco8-multispectral.yaml
  ultralytics/data/converter.py
Labels: documentation, enhancement

#19672 Add Tests CI after building Arm64 Docker images
  .github/workflows/docker.yml
  tests/test_cli.py
  tests/test_python.py
  ultralytics/utils/checks.py
Labels: TODO, enhancement, devops, embedded

#20215 RTDETR: Remove unused `preprocess_batch` function
  ultralytics/models/rtdetr/train.py
Labels: enhancement, detect

#20227 Fix stale workflow
  .github/workflows/stale.yml
Labels: enhancement, devops

#20230 Update extra.js with `0.3.20/dist/embed.min.js`
  CITATION.cff
  docs/overrides/javascript/extra.js
Labels: documentation, enhancement

#20232 Allow validation with `rect` for dynamic models
  ultralytics/engine/validator.py
Labels: enhancement, detect

#20220 Scope `tensorboard.SummaryWriter` import
  tests/test_integrations.py
  ultralytics/utils/callbacks/tensorboard.py
Labels: enhancement, dependencies

#20233 Fix test_solutions.py Streamlit test
  tests/test_solutions.py
  ultralytics/utils/callbacks/tensorboard.py
Labels: enhancement, solutions

#20239 Classify results background transparency
  ultralytics/engine/results.py
  ultralytics/utils/plotting.py
Labels: enhancement, classify

#20242 Fix Annotator tuples>lists
  ultralytics/utils/checks.py
  ultralytics/utils/plotting.py
Labels: bug, enhancement

#20241 Add PIL `results.plot(save=True)` test
  tests/test_python.py
  ultralytics/engine/results.py
Labels: enhancement, detect

#20245 Refactor `autosplit` and implement `split_classify_dataset`
  docs/en/datasets/classify/caltech101.md
  docs/en/datasets/classify/caltech256.md
  docs/en/datasets/detect/xview.md
  docs/en/reference/data/split.md
  docs/en/reference/data/utils.md
  docs/en/usage/simple-utilities.md
  tests/test_python.py
  ultralytics/cfg/__init__.py
  ultralytics/data/base.py
  ultralytics/data/split.py
  ultralytics/data/utils.py
Labels: enhancement, classify

#20246 Integrate "WARNING ⚠️" and "ERROR ❌" prefixes for LOGGER
  tests/test_python.py
  ultralytics/cfg/__init__.py
  ultralytics/data/augment.py
  ultralytics/data/base.py
  ultralytics/data/converter.py
  ultralytics/data/dataset.py
  ultralytics/data/loaders.py
  ultralytics/data/utils.py
  ultralytics/engine/exporter.py
  ultralytics/engine/model.py
  ultralytics/engine/predictor.py
  ultralytics/engine/results.py
  ultralytics/engine/trainer.py
  ultralytics/engine/tuner.py
  ultralytics/engine/validator.py
  ultralytics/hub/auth.py
  ultralytics/hub/session.py
  ultralytics/models/sam/modules/sam.py
  ultralytics/models/yolo/detect/train.py
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/pose/predict.py
  ultralytics/models/yolo/pose/train.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/models/yolo/segment/val.py
  ultralytics/nn/autobackend.py
  ultralytics/nn/tasks.py
  ultralytics/solutions/instance_segmentation.py
  ultralytics/solutions/object_blurrer.py
  ultralytics/solutions/object_cropper.py
  ultralytics/solutions/parking_management.py
  ultralytics/solutions/security_alarm.py
  ultralytics/solutions/solutions.py
  ultralytics/trackers/byte_tracker.py
  ultralytics/trackers/utils/gmc.py
  ultralytics/utils/__init__.py
  ultralytics/utils/autobatch.py
  ultralytics/utils/benchmarks.py
  ultralytics/utils/callbacks/clearml.py
  ultralytics/utils/callbacks/comet.py
  ultralytics/utils/callbacks/dvc.py
  ultralytics/utils/callbacks/mlflow.py
  ultralytics/utils/callbacks/neptune.py
  ultralytics/utils/callbacks/tensorboard.py
  ultralytics/utils/checks.py
  ultralytics/utils/downloads.py
  ultralytics/utils/export.py
  ultralytics/utils/metrics.py
  ultralytics/utils/ops.py
  ultralytics/utils/plotting.py
  ultralytics/utils/tal.py
  ultralytics/utils/torch_utils.py
  ultralytics/utils/tuner.py
Labels: documentation, enhancement

#20247 Update `build_reference.py` for automatic `mkdocs.yml` updates
  .github/workflows/docs.yml
  docs/build_reference.py
  mkdocs.yml
  ultralytics/models/sam/modules/sam.py
Labels: documentation, enhancement

#20223 `ultralytics 8.3.12` New YOLO Multispectral Image Support
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/cfg/datasets/coco8-multispectral.yaml
  ultralytics/data/augment.py
  ultralytics/data/base.py
  ultralytics/data/loaders.py
  ultralytics/data/utils.py
  ultralytics/engine/exporter.py
  ultralytics/engine/predictor.py
  ultralytics/engine/validator.py
  ultralytics/models/rtdetr/train.py
  ultralytics/models/yolo/classify/train.py
  ultralytics/models/yolo/detect/train.py
  ultralytics/models/yolo/obb/train.py
  ultralytics/models/yolo/pose/train.py
  ultralytics/models/yolo/segment/train.py
  ultralytics/models/yolo/world/train.py
  ultralytics/models/yolo/world/train_world.py
  ultralytics/models/yolo/yoloe/train.py
  ultralytics/models/yolo/yoloe/train_seg.py
  ultralytics/nn/autobackend.py
  ultralytics/nn/tasks.py
  ultralytics/utils/patches.py
  ultralytics/utils/plotting.py
Labels: enhancement

#20250 Add `classes` to validation args
  docs/en/macros/validation-args.md
Labels: documentation, enhancement

#20203 Intel `device` support
  docs/en/integrations/openvino.md
  ultralytics/nn/autobackend.py
  ultralytics/utils/torch_utils.py
Labels: TODO, enhancement, dependencies, embedded

#20263 Eliminate channel resorting for multi-channel images
  ultralytics/data/augment.py
  ultralytics/data/loaders.py
  ultralytics/engine/predictor.py
Labels: bug, enhancement

#20256 Add OBB support for SAHI
  examples/YOLOv8-SAHI-Inference-Video/README.md
  examples/YOLOv8-SAHI-Inference-Video/yolov8_sahi.py
Labels: enhancement, OBB, detect

#20235 Increase region count display size and add color-based visualization
  ultralytics/solutions/region_counter.py
Labels: enhancement, track, solutions, devops

#20269 `ultralytics 8.3.113` New DOTA8-Multispectral dataset
  ultralytics/__init__.py
  ultralytics/cfg/datasets/dota8-multispectral.yaml
  ultralytics/data/converter.py
Labels: enhancement, detect

#20286 Remove href attributes from code line numbers in Docs code blocks
  docs/build_docs.py
  docs/en/guides/optimizing-openvino-latency-vs-throughput-modes.md
  docs/en/help/minimum-reproducible-example.md
  docs/en/integrations/weights-biases.md
Labels: documentation

#20288 Parse `channels` as `int` in metadata
  ultralytics/nn/autobackend.py
Labels: enhancement, exports

#20280 Restore missing f-string
  ultralytics/engine/exporter.py
Labels: bug, exports

#20290 Refactor code line number links to use <span> tags
  docs/build_docs.py
Labels: documentation, enhancement

#20272 Update `coco8-multispectral` docs
  docs/en/datasets/detect/coco8-multispectral.md
Labels: documentation

#20270 Update `dota8-multispectral.yaml`
  ultralytics/cfg/datasets/dota8-multispectral.yaml
Labels: documentation

#20192 `ultralytics 8.3.114` New tracker re-identification (ReID) of lost tracks
  docs/en/reference/trackers/bot_sort.md
  ultralytics/__init__.py
  ultralytics/cfg/trackers/botsort.yaml
  ultralytics/models/yolo/detect/predict.py
  ultralytics/trackers/bot_sort.py
  ultralytics/trackers/byte_tracker.py
  ultralytics/trackers/track.py
  ultralytics/utils/ops.py
Labels: TODO, enhancement, track, classify

#20293 Remove nested spans form Mkdocstrings HTML
  docs/build_docs.py
Labels: documentation, enhancement

#20309 Add additional Google-style docstring examples
  docs/en/help/contributing.md
Labels: documentation

#20303 Add slow disk read speed warning
  ultralytics/data/utils.py
Labels: enhancement

#20307 Fix usage in `yoloe.md` FAQ section
  docs/en/models/yoloe.md
Labels: documentation

#20312 Bug Fix: Incorrect Use of RANK in Distributed Context Manager
  ultralytics/utils/__init__.py
Labels: bug, devops

#20301 `ultralytics 8.3.115` TIFF image RGB training and prediction support
  ultralytics/__init__.py
  ultralytics/utils/patches.py
Labels: bug, enhancement

#20274 Update `Tuple` return type annotations in `docstrings`
  ultralytics/data/augment.py
  ultralytics/data/base.py
  ultralytics/data/build.py
  ultralytics/data/dataset.py
  ultralytics/data/utils.py
  ultralytics/engine/results.py
  ultralytics/models/sam/modules/utils.py
  ultralytics/models/yolo/segment/predict.py
  ultralytics/nn/modules/conv.py
  ultralytics/nn/modules/head.py
  ultralytics/utils/checks.py
Labels: documentation

#20321 Fix YOLOE usage in `model.py`
  docs/en/models/yoloe.md
  ultralytics/models/yolo/model.py
Labels: documentation, enhancement, segment

#20322 Fix `non_max_suppression` when applying `classes` argument
  tests/test_python.py
  ultralytics/utils/ops.py
Labels: bug, enhancement, track

#20313 Add `half` argument to Torchscript export allowlist
  docs/en/macros/export-table.md
  examples/tutorial.ipynb
  ultralytics/engine/exporter.py
Labels: TODO, enhancement, exports

#20282 Add `show_conf` and `show_labels` for Solutions
  docs/mkdocs_github_authors.yaml
  examples/tutorial.ipynb
  ultralytics/solutions/ai_gym.py
  ultralytics/solutions/distance_calculation.py
  ultralytics/solutions/object_blurrer.py
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/queue_management.py
  ultralytics/solutions/region_counter.py
  ultralytics/solutions/solutions.py
  ultralytics/solutions/speed_estimation.py
  ultralytics/solutions/trackzone.py
  ultralytics/solutions/vision_eye.py
Labels: enhancement, detect, solutions

#20335 FROM pytorch/pytorch:2.7.0-cuda12.6-cudnn9-runtime
  docker/Dockerfile
Labels: enhancement, dependencies

#20334 Remove redundant coordinate conversions for `nms=True`
  ultralytics/engine/exporter.py
  ultralytics/nn/modules/head.py
Labels: enhancement, detect, exports

#20336 Add workflow-level CI permissions for security
  .github/workflows/ci.yml
  .github/workflows/docker.yml
  .github/workflows/links.yml
  .github/workflows/mirror.yml
Labels: enhancement, devops

#20292 `ultralytics 8.3.116` RTDETR VarifocalLoss `gamma` and `alpha` parameterization
  ultralytics/__init__.py
  ultralytics/models/utils/loss.py
  ultralytics/utils/loss.py
Labels: enhancement, detect

#20343 Fix private local import issue
  ultralytics/cfg/__init__.py
  ultralytics/data/base.py
  ultralytics/data/dataset.py
  ultralytics/data/loaders.py
  ultralytics/engine/exporter.py
  ultralytics/engine/trainer.py
  ultralytics/hub/session.py
  ultralytics/hub/utils.py
  ultralytics/models/yolo/yoloe/val.py
  ultralytics/utils/__init__.py
  ultralytics/utils/checks.py
  ultralytics/utils/torch_utils.py
Labels: enhancement, dependencies

#20330 Fix DDP with Gloo backend on Windows
  ultralytics/engine/trainer.py
  ultralytics/utils/torch_utils.py
Labels: bug, enhancement

#20353 Fix predictions if metadata is missing
  ultralytics/models/yolo/detect/predict.py
  ultralytics/models/yolo/detect/val.py
Labels: bug, detect

#20236 Add Benchmarks CI to `Dockerfile-arm64`
  .github/workflows/docker.yml
Labels: TODO, enhancement, devops

#20357 Fix box sizes for CoreML exports
  ultralytics/engine/exporter.py
Labels: enhancement, exports

#16413 `ultralytics 8.3.117` Replace TFLite Support with JSON metadata
  .github/workflows/ci.yml
  .github/workflows/docker.yml
  docker/Dockerfile-cpu
  docker/Dockerfile-jetson-jetpack6
  docker/Dockerfile-python
  docker/Dockerfile-runner
  pyproject.toml
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
  ultralytics/utils/benchmarks.py
  ultralytics/utils/checks.py
Labels: TODO, enhancement, dependencies, Stale, devops

#20362 Remove special CoreML<>protobuf handling
  .github/workflows/ci.yml
  ultralytics/engine/exporter.py
Labels: dependencies, devops, exports

#20365 Add `tests` directory to package for Conda builds
  pyproject.toml
Labels: enhancement, dependencies

#20361 Implement 3.12-compatible Raspberry Pi CI
  .github/workflows/ci.yml
  ultralytics/nn/autobackend.py
Labels: TODO, dependencies, devops, embedded

#20367 Dockerfile export Sony IMX with YOLO11
  docker/Dockerfile-cpu
  docker/Dockerfile-python
  docs/en/help/CI.md
  ultralytics/engine/exporter.py
  ultralytics/models/yolo/detect/predict.py
  ultralytics/models/yolo/model.py
  ultralytics/models/yolo/obb/train.py
  ultralytics/models/yolo/pose/predict.py
  ultralytics/models/yolo/pose/train.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/models/yolo/segment/train.py
  ultralytics/nn/autobackend.py
  ultralytics/utils/benchmarks.py
Labels: documentation, enhancement

#20310 Add Grayscale image training support
  ultralytics/data/augment.py
  ultralytics/data/base.py
  ultralytics/data/dataset.py
Labels: TODO, enhancement

#20369 Update `onnxslim>=0.1.46`
  ultralytics/engine/exporter.py
Labels: dependencies, OBB, exports

#20376 Fix NMS box format comment from xyxy to xywh
  pyproject.toml
  ultralytics/utils/ops.py
Labels: documentation

#20383 Remove `tflite_support` and `flatbuffers` dependencies
  docs/mkdocs_github_authors.yaml
  ultralytics/engine/exporter.py
Labels: enhancement, dependencies, exports

#20384 Remove `g++` and `libusb-1.0-0` from Docker linux installs
  docker/Dockerfile
  docker/Dockerfile-arm64
  docker/Dockerfile-cpu
  docker/Dockerfile-python
  pyproject.toml
  ultralytics/engine/exporter.py
Labels: enhancement, dependencies, devops

#19870 `ultralytics 8.3.119` New CutMix image augmentation
  docs/en/guides/yolo-data-augmentation.md
  docs/en/integrations/ray-tune.md
  docs/en/macros/augmentation-args.md
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/cfg/default.yaml
  ultralytics/data/augment.py
  ultralytics/data/dataset.py
  ultralytics/engine/tuner.py
  ultralytics/models/rtdetr/val.py
  ultralytics/utils/tuner.py
Labels: TODO, enhancement, detect, classify

#20389 Remove redundant `get_indexes` functions in `augment.py`
  docs/en/reference/data/augment.md
  docs/mkdocs_github_authors.yaml
  ultralytics/data/augment.py
Labels: enhancement

#20413 YOLOE: Fix visual prompt training
  .gitignore
  docs/en/models/yoloe.md
  ultralytics/data/dataset.py
  ultralytics/models/yolo/yoloe/train.py
  ultralytics/utils/loss.py
Labels: TODO, bug, documentation, enhancement, segment

#20416 YOLOE: Clean up duplicated modules
  ultralytics/models/yolo/world/train_world.py
  ultralytics/models/yolo/yoloe/__init__.py
  ultralytics/models/yolo/yoloe/train.py
  ultralytics/models/yolo/yoloe/train_seg.py
Labels: enhancement, detect

#20393 `ultralytics 8.3.120` CutMix augmentation fix via IoU overlaps
  ultralytics/__init__.py
  ultralytics/data/augment.py
Labels: enhancement, detect

#20425 Update Cutmix augmentation docs
  docs/en/guides/yolo-data-augmentation.md
  docs/en/macros/augmentation-args.md
Labels: documentation, enhancement

#20420 Fix CutMix augmentation
  ultralytics/data/augment.py
Labels: bug, detect

#20426 Check if `curl` is installed before use
  ultralytics/utils/downloads.py
Labels: enhancement, dependencies

#20345 Use `MINMAX_CALIBRATION` algo for TensorRT int8 calibration
  ultralytics/utils/export.py
Labels: TODO, enhancement, exports

#20366 Update CI to Python 3.12
  .github/workflows/ci.yml
  ultralytics/engine/exporter.py
Labels: dependencies, devops

#20388 `ultralytics 8.3.121` Add FocalLoss multi-class support
  ultralytics/__init__.py
  ultralytics/models/utils/loss.py
  ultralytics/utils/loss.py
Labels: TODO, documentation, enhancement, classify

#20344 Improve speed estimation using `track` history and region-free calculation
  docs/en/guides/speed-estimation.md
  ultralytics/solutions/speed_estimation.py
Labels: bug, documentation, enhancement, track, solutions

#20430 Add Custom Installation Section to Quickstart Docs
  docs/en/quickstart.md
Labels: documentation, enhancement, dependencies

#20435 Add tracker and re-identification parameters to docs
  docs/en/modes/track.md
  ultralytics/cfg/trackers/botsort.yaml
  ultralytics/trackers/bot_sort.py
Labels: documentation, enhancement, track

#20437 `ultralytics 8.3.122` Native Xcode preview of YOLO CoreML Classification models
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
Labels: enhancement, classify, exports
