Repository ultralytics/ultralytics, pull requests merged in 2025-09, with the labels that each got.

#21892 Fix Autobackend string model bug
  ultralytics/models/yolo/yoloe/val.py
  ultralytics/nn/autobackend.py
  ultralytics/nn/tasks.py
Labels: bug, python

#21909 fix: 🐞 improve CSV reading performance by disabling schema inference
  ultralytics/cfg/datasets/SKU-110K.yaml
  ultralytics/engine/trainer.py
  ultralytics/utils/plotting.py
Labels: bug, python

#21915 Add warning that legacy YOLOv5 models are not compatible with Ultralytics
  docs/en/models/yolov5.md
Labels: documentation

#21929 Update docs.yml for Python 3.9 ruff format target
  .github/workflows/docs.yml
Labels: devops

#21932 Remove TQDM duplicate filesize info on completion
  ultralytics/utils/tqdm.py
Labels: enhancement, python

#21934 TQDM smart rate scaling
  ultralytics/utils/tqdm.py
Labels: enhancement, python

#21933 Consolidate checkpoint loading functions
  docs/en/reference/nn/tasks.md
  ultralytics/engine/model.py
  ultralytics/engine/trainer.py
  ultralytics/models/yolo/yoloe/val.py
  ultralytics/nn/__init__.py
  ultralytics/nn/autobackend.py
  ultralytics/nn/tasks.py
Labels: enhancement, python

#21942 Fix dataset directory structure information in docs
  docs/en/datasets/index.md
Labels: documentation

#21949 Pin `tf_keras<=2.19.0`
  ultralytics/engine/exporter.py
Labels: dependencies, exports

#21948 Support CoreML inference with NMS embedded models
  tests/test_exports.py
  ultralytics/nn/autobackend.py
Labels: enhancement, exports, python

#21947 fix: split large channel masks to handle `cv2.resize` 512 limitations
  ultralytics/utils/ops.py
Labels: bug, segment, python

#21955 Fix `SAM2DynamicInteractivePredictor` example in docs
  docs/en/models/sam-2.md
  ultralytics/models/sam/predict.py
Labels: documentation, python

#21960 Prevent long-running billed GPU CI
  .github/workflows/ci.yml
Labels: enhancement, devops

#21923 Add https://youtu.be/Gxr9SpYPLh0 to docs
  docs/en/guides/queue-management.md
Labels: documentation

#21951 `ultralytics 8.3.194` Bump `onnxslim>=0.1.67` in Exporter
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/utils/__init__.py
Labels: dependencies, exports

#21972 `ultralytics 8.3.195` Zero-dependency 30X faster CPU info
  docs/en/reference/utils/cpu.md
  mkdocs.yml
  pyproject.toml
  ultralytics/__init__.py
  ultralytics/utils/cpu.py
  ultralytics/utils/torch_utils.py
Labels: enhancement, dependencies, python

#21973 Add `@plt_settings()` decorator to `feature_visualization()`
  ultralytics/utils/plotting.py
Labels: enhancement, devops, python

#21970 Cleanup CoreML NMS pipeline code
  ultralytics/engine/exporter.py
Labels: enhancement, exports, python

#21978 Update torchvision compat matrix with 2.8 and 2.9
  ultralytics/utils/checks.py
Labels: dependencies, python

#21980 Fix overly verbose USER_CONFIG_DIR checks
  ultralytics/utils/__init__.py
Labels: enhancement, python

#21981 Fix missing Tensors on device in Trainer and Validator `preprocess_batch` methods
  ultralytics/models/yolo/detect/train.py
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/models/yolo/segment/val.py
  ultralytics/models/yolo/yoloe/train.py
  ultralytics/models/yolo/yoloe/val.py
  ultralytics/utils/loss.py
Labels: enhancement, detect, python

#21987 Fix typo in `deprecation_warn` method
  ultralytics/utils/__init__.py
Labels: python

#21975 `ultralytics 8.3.196` `torch.compile` acceleration for 30% faster training
  docs/en/macros/predict-args.md
  docs/en/macros/train-args.md
  docs/en/macros/validation-args.md
  docs/en/reference/utils/torch_utils.md
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/cfg/default.yaml
  ultralytics/data/augment.py
  ultralytics/data/build.py
  ultralytics/engine/predictor.py
  ultralytics/engine/trainer.py
  ultralytics/engine/validator.py
  ultralytics/models/yolo/classify/train.py
  ultralytics/models/yolo/detect/train.py
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/obb/train.py
  ultralytics/models/yolo/pose/train.py
  ultralytics/models/yolo/segment/train.py
  ultralytics/models/yolo/world/train.py
  ultralytics/models/yolo/world/train_world.py
  ultralytics/models/yolo/yoloe/train.py
  ultralytics/nn/modules/head.py
  ultralytics/nn/tasks.py
  ultralytics/utils/callbacks/tensorboard.py
  ultralytics/utils/loss.py
  ultralytics/utils/torch_utils.py
Labels: TODO, enhancement, python

#22004 Add COCO128-Seg dataset documentation and fix broken links
  docs/en/datasets/index.md
  docs/en/datasets/segment/coco128-seg.md
  docs/en/datasets/segment/index.md
  docs/mkdocs_github_authors.yaml
  mkdocs.yml
Labels: documentation, segment

#21976 `ultralytics 8.3.197` New Construction-PPE dataset
  docs/en/datasets/detect/construction-ppe.md
  docs/en/datasets/detect/index.md
  docs/en/datasets/index.md
  mkdocs.yml
  ultralytics/__init__.py
  ultralytics/cfg/datasets/construction-ppe.yaml
Labels: documentation, enhancement, detect

#22014 Fix `TorchNMS.nms()` early exit logic
  ultralytics/utils/nms.py
Labels: bug, detect, python

#22035 docs: 📝 remove seaborn package from manual installation dependencies list from quickstart docs
  docs/en/quickstart.md
Labels: documentation

#22029 Add business value section to Construction-PPE dataset
  docs/en/datasets/detect/construction-ppe.md
Labels: documentation

#22025 Reset labels cache when loading with incompatible `numpy` version
  ultralytics/data/dataset.py
Labels: bug, python

#22021 Faster `torch.Tensor.shape[0]` to get length for `torch.Tensor`
  ultralytics/data/augment.py
  ultralytics/models/sam/modules/decoders.py
  ultralytics/models/sam/modules/sam.py
  ultralytics/models/sam/predict.py
  ultralytics/models/yolo/classify/train.py
  ultralytics/models/yolo/classify/val.py
  ultralytics/models/yolo/detect/predict.py
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/obb/val.py
  ultralytics/models/yolo/pose/predict.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/models/yolo/segment/predict.py
  ultralytics/models/yolo/segment/val.py
  ultralytics/models/yolo/yoloe/val.py
  ultralytics/nn/modules/block.py
  ultralytics/nn/tasks.py
  ultralytics/utils/metrics.py
Labels: enhancement, python

#22026 Clean up and unify `plot_results` for `detect/segment/pose/obb/classify` tasks
  ultralytics/engine/trainer.py
  ultralytics/models/yolo/classify/train.py
  ultralytics/models/yolo/detect/train.py
  ultralytics/models/yolo/pose/train.py
  ultralytics/models/yolo/segment/train.py
  ultralytics/utils/plotting.py
Labels: enhancement, python

#22037 Fix mask shape mismatch when validating with `mask_ratio=1`
  tests/test_engine.py
  ultralytics/models/yolo/segment/val.py
Labels: bug, segment, python

#22066 Fix `KeyError` when `close_mosaic` not part of search space
  ultralytics/engine/tuner.py
Labels: bug, python

#22046 Update deepstream-nvidia-jetson.md
  docs/en/guides/deepstream-nvidia-jetson.md
Labels: documentation, embedded

#22083 Improve export error message for `pt` format
  ultralytics/engine/exporter.py
Labels: enhancement, exports, python

#22082 Update `IMX` export assert message to include `YOLO11n`
  ultralytics/utils/benchmarks.py
Labels: exports, python

#22005 `ultralytics 8.3.200` Refactor Sony IMX exports to `imx.py`
  docs/en/reference/utils/export.md
  docs/en/reference/utils/export/__init__.md
  docs/en/reference/utils/export/imx.md
  docs/en/reference/utils/torch_utils.md
  mkdocs.yml
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/nn/modules/head.py
  ultralytics/utils/export/__init__.py
  ultralytics/utils/export/imx.py
  ultralytics/utils/torch_utils.py
Labels: TODO, enhancement, exports, python

#22094 Fix CSV read error in SKU-110K.yaml download script
  ultralytics/cfg/datasets/SKU-110K.yaml
Labels: bug, dependencies, python

#22102 Display help message with `yolo -h`
  ultralytics/cfg/__init__.py
Labels: enhancement, python

#22108 Assert non-zero filesize in Exporter
  ultralytics/engine/exporter.py
Labels: enhancement, exports, python

#21900 Add "Supported Tasks" column to augmentation arguments table
  docs/en/macros/augmentation-args.md
Labels: documentation

#21830 Docs: Add comprehensive model YAML configuration guide
  docs/en/guides/index.md
  docs/en/guides/model-yaml-config.md
  mkdocs.yml
Labels: documentation

#22120 Start distributed Tuner mutation if Mongo collection exists
  ultralytics/engine/tuner.py
Labels: enhancement, python

#22133 `ultralytics 8.3.202` TFLite `per-channel` INT8 quantization fix
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
Labels: bug, exports

#22122 Fix url image inference
  tests/test_python.py
  ultralytics/data/build.py
Labels: bug, python

#22156 Require `torch>=2.1` for OpenVINO exports
  tests/test_exports.py
  ultralytics/engine/exporter.py
  ultralytics/utils/torch_utils.py
Labels: exports, python

#22158 Fix meshgrid with indexing bug on `torch==1.10`
  ultralytics/nn/modules/head.py
  ultralytics/utils/tal.py
  ultralytics/utils/torch_utils.py
Labels: bug, dependencies, python

#22160 Require `torch>=1.13` for YOLOE models
  tests/test_python.py
  ultralytics/nn/text_model.py
Labels: dependencies, python

#22157 Enable slug generation for content tab anchor links in MkDocs
  mkdocs.yml
Labels: documentation

#22161 Require `torch>=1.11` for RTDETR models
  tests/test_cli.py
  tests/test_python.py
  ultralytics/models/rtdetr/model.py
  ultralytics/nn/text_model.py
Labels: dependencies, python

#22162 Require `torch>=1.11` for CoreML exports
  tests/test_exports.py
  ultralytics/engine/exporter.py
Labels: dependencies, exports

#22169 PyTorch 1.9 FastSAM `sum(0).sum()` predictor fix
  ultralytics/models/fastsam/predict.py
  ultralytics/utils/torch_utils.py
Labels: bug, segment, python

#22184 Add Actions CI badge to Docs
  docs/en/help/CI.md
Labels: documentation, devops

#22186 Add `uv` `required-version = "==0.8.19"`
  pyproject.toml
Labels: dependencies, devops

#22189 `ultralytics 8.3.203` Restore `GradScaler` on resuming training
  ultralytics/__init__.py
  ultralytics/engine/trainer.py
Labels: TODO, bug, python

#22193 Fix --slow CUDA tests
  tests/test_cuda.py
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: devops

#22192 Verify passed dataset is a directory and not a file for classification training
  ultralytics/data/utils.py
Labels: enhancement, classify, python

#22203 Enable Python Fault Handler in CI
  .github/workflows/ci.yml
Labels: devops

#22205 Remove the compromise of criterion initialization for `torch.compile`
  tests/test_python.py
  ultralytics/engine/trainer.py
Labels: enhancement, python

#22212 Add `RKNN` model support in streamlit `live-inference` solution
  ultralytics/solutions/streamlit_inference.py
Labels: enhancement, solutions, embedded

#22258 Docs: Update YOLO11 profiling data in README
  README.md
  README.zh-CN.md
  docs/en/macros/yolo-cls-perf.md
  docs/en/macros/yolo-obb-perf.md
  docs/en/macros/yolo-pose-perf.md
  docs/en/macros/yolo-seg-perf.md
  docs/mkdocs_github_authors.yaml
Labels: documentation

#22263 Add Mengyu to mkdocs_github_authors.yaml
  docs/mkdocs_github_authors.yaml
Labels: documentation

#22254 `ultralytics 8.3.204` Scope `batch_size` check from `select_device()` to Trainer
  tests/test_cuda.py
  ultralytics/__init__.py
  ultralytics/engine/trainer.py
  ultralytics/engine/validator.py
  ultralytics/utils/torch_utils.py
Labels: enhancement, python
