Repository ultralytics/ultralytics, pull requests merged in 2025-07, with the labels that each got.

#21237 YOLOE: specify device for text embedding cache loading
  ultralytics/models/yolo/world/train.py
  ultralytics/models/yolo/yoloe/train.py
Labels: TODO, enhancement, python

#21245 Fix `is_lvis` check for open-vocabulary models evaluation
  ultralytics/models/yolo/world/train_world.py
Labels: enhancement, detect, python

#21242 Support intel XPU discovery
  docs/en/reference/utils/checks.md
  ultralytics/engine/exporter.py
  ultralytics/utils/checks.py
Labels: TODO, enhancement, exports, python

#21256 Add `DATASET_DIR` relative path compatibility for grounding datasets
  tests/conftest.py
  tests/test_python.py
  ultralytics/data/converter.py
  ultralytics/data/split_dota.py
  ultralytics/models/sam/modules/tiny_encoder.py
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/world/train_world.py
  ultralytics/solutions/solutions.py
  ultralytics/utils/metrics.py
  ultralytics/utils/plotting.py
Labels: enhancement, segment, python

#21287 Add https://youtu.be/zHxwDkYShNc to docs
  docs/en/modes/val.md
Labels: documentation, exports

#21277 YOLOE: Fix model text embedding fusing
  ultralytics/nn/tasks.py
Labels: enhancement, python

#21290 Update JetPack test matrix to run all jobs regardless of failure
  .github/workflows/ci.yml
Labels: devops, embedded

#21291 Add Jetson CI for Slack notifications on failure
  .github/workflows/ci.yml
Labels: devops, embedded

#21304 Remove `onnxslim` from `pyproject.toml` due to Jetson6 docker tests failing
  pyproject.toml
Labels: enhancement, dependencies, exports

#21310 `ultralytics 8.3.163` Add `1%` tolerance for labels normalization check
  ultralytics/__init__.py
  ultralytics/data/utils.py
Labels: enhancement, python

#21286 Fix inconsistent `max_samples` value between `GroundingDataset` and `YOLOMultiModalDataset`
  ultralytics/data/build.py
  ultralytics/data/dataset.py
  ultralytics/models/yolo/world/train_world.py
Labels: bug, python

#21320 Add max batch warning for dynamic model with NMS
  ultralytics/engine/exporter.py
  ultralytics/utils/export.py
Labels: enhancement, exports, python

#21322 Fix wrong error message in `classify_transforms`
  ultralytics/data/augment.py
Labels: bug, classify, python

#21346 Add https://youtu.be/iBk6S-PHwS0 to docs
  docs/en/guides/data-collection-and-annotation.md
Labels: documentation, enhancement

#21350 `ultralytics 8.3.164` Fix swapped mAP50 and mAP50-95 in COCOEval stats
  ultralytics/__init__.py
  ultralytics/models/yolo/detect/val.py
Labels: bug, python

#21353 `ultralytics 8.3.165` Update datasets YAML's
  ultralytics/__init__.py
  ultralytics/cfg/datasets/HomeObjects-3K.yaml
  ultralytics/cfg/datasets/african-wildlife.yaml
  ultralytics/cfg/datasets/brain-tumor.yaml
  ultralytics/cfg/datasets/carparts-seg.yaml
  ultralytics/cfg/datasets/crack-seg.yaml
  ultralytics/cfg/datasets/dog-pose.yaml
  ultralytics/cfg/datasets/hand-keypoints.yaml
  ultralytics/cfg/datasets/medical-pills.yaml
  ultralytics/cfg/datasets/package-seg.yaml
  ultralytics/cfg/datasets/signature.yaml
  ultralytics/cfg/datasets/tiger-pose.yaml
Labels: documentation, enhancement

#21356 Fix `self.names` overwriting in `ConfusionMatrix`
  ultralytics/utils/metrics.py
Labels: enhancement, python

#20196 Support `IMX` export and inference for Pose Estimation
  docs/en/integrations/sony-imx500.md
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
  ultralytics/nn/modules/head.py
Labels: enhancement, pose, exports

#21404 `ultralytics 8.3.167` Fix Sony IMX export `mct-quantizers>=1.6.0` dependency
  docs/en/integrations/ibm-watsonx.md
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
Labels: dependencies, embedded, exports

#21407 Update `Ultralytics YOLO11` docs `citation` section
  docs/en/models/yolo11.md
Labels: documentation

#21413 Add `image` inference support to `Streamlit` application
  ultralytics/solutions/streamlit_inference.py
Labels: enhancement, detect, python

#21450 Add https://youtu.be/v3iqOYoRBFQ to docs
  docs/en/datasets/detect/homeobjects-3k.md
Labels: documentation, detect, exports

#21443 Retain `predictor` args while getting model names
  ultralytics/engine/model.py
Labels: enhancement, exports, python

#21449 Fix CLI syntax in docs example
  docs/en/guides/speed-estimation.md
Labels: documentation, exports

#21482 Remove `optimization_for_gpu_delegate` flag for TF exports
  docs/mkdocs_github_authors.yaml
  ultralytics/engine/exporter.py
Labels: exports, python

#21467 Fixing `NoneType` error while reading image
  ultralytics/utils/patches.py
Labels: bug, python

#21511 Add https://youtu.be/e-TwqFtay90 to docs
  docs/en/guides/yolo-data-augmentation.md
Labels: TODO, documentation

#21508 Fix OpenVINO segment inference when `batch>1`
  tests/test_exports.py
  ultralytics/nn/autobackend.py
Labels: exports, python

#21452 `ultralytics 8.3.170` Eliminate `batch` argument for `AutoBackend` class and fix OpenVINO inference
  ultralytics/__init__.py
  ultralytics/engine/predictor.py
  ultralytics/nn/autobackend.py
Labels: TODO, enhancement, exports, python

#21531 Vertex AI Docker deployment guide for YOLO11
  docs/en/guides/index.md
  docs/en/guides/vertex-ai-deployment-with-docker.md
  mkdocs.yml
Labels: documentation, enhancement

#21537 Pin `pydantic<=2.11.7`
  docs/mkdocs_github_authors.yaml
  ultralytics/engine/exporter.py
Labels: dependencies, exports, python

#21538 Disable TQDM output at higher logging levels
  ultralytics/utils/__init__.py
Labels: enhancement, python
