Repository ultralytics/ultralytics, pull requests merged in 2025-03, with the labels that each got.

#19483 Enable `mnn` in Raspberry Pi Tests
  tests/test_exports.py
Labels: TODO, devops, embedded, exports

#19486 Fix ONNX Example letterboxing
  examples/YOLOv8-ONNXRuntime/main.py
Labels: bug, exports

#19475 Fix dataset_dir error with `open-images-v7.yaml`
  ultralytics/cfg/datasets/open-images-v7.yaml
Labels: documentation, enhancement

#19464 `ultralytics 8.3.82` ONNX `dynamic` and `half` export
  docs/en/reference/engine/exporter.md
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
Labels: enhancement, exports

#19504 Fix `batch` description for validation
  docs/en/macros/validation-args.md
Labels: documentation

#19515 `ultralytics 8.3.83` Revert saturation and value augmentation to relative shift
  ultralytics/__init__.py
  ultralytics/data/augment.py
Labels: enhancement, detect

#19532 Add https://youtu.be/ILqMBah5ZvI to docs
  docs/en/guides/sahi-tiled-inference.md
Labels: documentation

#19537 `ultralytics 8.3.84` Remove predictions with no masks
  ultralytics/__init__.py
  ultralytics/models/yolo/segment/predict.py
Labels: enhancement, segment

#19551 Cleanup and fix ONNX segment example
  examples/YOLOv8-Segmentation-ONNXRuntime-Python/main.py
Labels: enhancement, segment, exports

#19541 `ultralytics 8.3.85` TensoRT export `max_shape` fix
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
Labels: fixed, exports

#19573 Update sam-2.md
  docs/en/models/sam-2.md
Labels: documentation

#19577 Remove superfluous LOGGER import from data/converter
  ultralytics/data/converter.py
Labels: enhancement

#19565 Add https://youtu.be/ZN3nRZT7b24 to docs
  docs/en/guides/model-training-tips.md
  docs/en/index.md
  docs/en/integrations/google-colab.md
Labels: documentation

#19567 Exclude keypoint visibility from stride division
  ultralytics/utils/loss.py
Labels: enhancement, pose

#19576 Remove extra import from `cfg/__init__`
  ultralytics/cfg/__init__.py
Labels: enhancement, dependencies

#19578 Adds open encoding per PEP-597
  ultralytics/cfg/datasets/Argoverse.yaml
  ultralytics/cfg/datasets/Objects365.yaml
  ultralytics/cfg/datasets/SKU-110K.yaml
  ultralytics/cfg/datasets/VisDrone.yaml
  ultralytics/cfg/datasets/xView.yaml
  ultralytics/data/annotator.py
  ultralytics/data/base.py
  ultralytics/data/converter.py
  ultralytics/data/split_dota.py
  ultralytics/data/utils.py
  ultralytics/engine/exporter.py
  ultralytics/engine/results.py
  ultralytics/engine/trainer.py
  ultralytics/engine/tuner.py
  ultralytics/engine/validator.py
  ultralytics/models/yolo/obb/val.py
  ultralytics/utils/__init__.py
  ultralytics/utils/benchmarks.py
Labels: enhancement, dependencies

#19560 Set `dynamic` from metadata
  ultralytics/nn/autobackend.py
Labels: enhancement, devops

#19579 `ultralytics 8.3.86` Refactor dataset YAML autodownload scripts
  ultralytics/__init__.py
  ultralytics/cfg/datasets/Argoverse.yaml
  ultralytics/cfg/datasets/GlobalWheat2020.yaml
  ultralytics/cfg/datasets/ImageNet.yaml
  ultralytics/cfg/datasets/Objects365.yaml
  ultralytics/cfg/datasets/SKU-110K.yaml
  ultralytics/cfg/datasets/VOC.yaml
  ultralytics/cfg/datasets/VisDrone.yaml
  ultralytics/cfg/datasets/coco-pose.yaml
  ultralytics/cfg/datasets/coco.yaml
  ultralytics/cfg/datasets/lvis.yaml
  ultralytics/cfg/datasets/open-images-v7.yaml
  ultralytics/cfg/datasets/xView.yaml
Labels: bug, documentation, enhancement

#19596 Enable Ubuntu ARM GitHub CI runners
  .github/workflows/ci.yml
Labels: TODO, devops, embedded

#19594 Add COCO128 dataset page to docs
  docs/en/datasets/detect/coco128.md
  docs/en/datasets/index.md
  mkdocs.yml
Labels: TODO, documentation, detect

#19597 Fix BBox Out-of-Bounds Issue in MNN Example
  docs/en/integrations/mnn.md
Labels: bug, detect

#19534 Add extra step for installing `tkinter` for annotator tool
  docs/en/guides/parking-management.md
  tests/test_solutions.py
  ultralytics/solutions/parking_management.py
Labels: documentation

#19593 Update classification model FLOPs with `imgsz=224`
  README.md
  README.zh-CN.md
  docs/en/macros/yolo-cls-perf.md
  docs/en/models/yolov8.md
  ultralytics/cfg/models/11/yolo11-cls-resnet18.yaml
  ultralytics/cfg/models/11/yolo11-cls.yaml
Labels: documentation, classify

#19554 Exclude `ort.pyke.io` from link checking
  .github/workflows/links.yml
Labels: documentation, devops

#19589 Solutions init conditional import
  ultralytics/cfg/__init__.py
Labels: enhancement, solutions

#19481 Constrain OpenVINO versions to >=2024.0.0,!=2025.0.0
  pyproject.toml
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: dependencies, exports

#19297 Fix result saving issue when multi-stream detection
  ultralytics/data/loaders.py
Labels: TODO, enhancement, detect

#19618 Add Segmentation support in Comet logging
  ultralytics/utils/callbacks/comet.py
Labels: enhancement, segment, devops

#19625 Revert `shell=True` for `model.tune()`
  ultralytics/engine/tuner.py
Labels: bug, enhancement

#19624 Remove parking slots annotator from tests
  tests/test_solutions.py
Labels: TODO, solutions, devops

#19626 Update docs.yml Ruff fixes
  .github/workflows/docs.yml
  docs/en/guides/kfold-cross-validation.md
  docs/en/guides/triton-inference-server.md
  docs/en/integrations/mnn.md
  docs/en/integrations/seeedstudio-recamera.md
  ultralytics/nn/tasks.py
  ultralytics/utils/__init__.py
Labels: documentation, devops

#18949 `empty_cache()` only if GPU utilization above 90%
  ultralytics/engine/trainer.py
Labels: enhancement, devops

#19161 `ultralytics 8.3.87` New `Results.to_html` method for inference outputs
  docs/en/modes/predict.md
  ultralytics/__init__.py
  ultralytics/engine/results.py
Labels: TODO, documentation, enhancement, OBB

#19639 Fix detection box offset bug in YOLOv8 example model inference results
  examples/YOLOv8-CPP-Inference/inference.cpp
  examples/YOLOv8-CPP-Inference/inference.h
Labels: bug, detect

#19643 Docs: Update Banner
  docs/overrides/main.html
  docs/overrides/stylesheets/style.css
Labels: documentation

#19645 Improved Examples documentation
  examples/RTDETR-ONNXRuntime-Python/main.py
  examples/YOLOv8-Action-Recognition/action_recognition.py
  examples/YOLOv8-ONNXRuntime/main.py
  examples/YOLOv8-OpenCV-ONNX-Python/main.py
  examples/YOLOv8-Region-Counter/yolov8_region_counter.py
  examples/YOLOv8-SAHI-Inference-Video/yolov8_sahi.py
  examples/YOLOv8-Segmentation-ONNXRuntime-Python/main.py
  examples/YOLOv8-TFLite-Python/main.py
Labels: documentation, segment, detect

#18491 `ultralytics 8.3.88` Solutions refactor and improvements
  docs/en/guides/analytics.md
  docs/en/guides/distance-calculation.md
  docs/en/guides/heatmaps.md
  docs/en/guides/instance-segmentation-and-tracking.md
  docs/en/guides/object-blurring.md
  docs/en/guides/object-counting.md
  docs/en/guides/object-cropping.md
  docs/en/guides/parking-management.md
  docs/en/guides/queue-management.md
  docs/en/guides/region-counting.md
  docs/en/guides/security-alarm-system.md
  docs/en/guides/speed-estimation.md
  docs/en/guides/streamlit-live-inference.md
  docs/en/guides/trackzone.md
  docs/en/guides/vision-eye.md
  docs/en/guides/workouts-monitoring.md
  docs/en/macros/solutions-args.md
  docs/en/macros/track-args.md
  docs/en/macros/visualization-args.md
  docs/en/modes/predict.md
  docs/en/reference/solutions/instance_segmentation.md
  docs/en/reference/solutions/object_blurrer.md
  docs/en/reference/solutions/object_cropper.md
  docs/en/reference/solutions/solutions.md
  docs/en/reference/solutions/vision_eye.md
  docs/en/solutions/index.md
  docs/en/usage/cfg.md
  docs/en/usage/simple-utilities.md
  mkdocs.yml
  tests/test_solutions.py
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/data/augment.py
  ultralytics/solutions/__init__.py
  ultralytics/solutions/ai_gym.py
  ultralytics/solutions/analytics.py
  ultralytics/solutions/distance_calculation.py
  ultralytics/solutions/heatmap.py
  ultralytics/solutions/instance_segmentation.py
  ultralytics/solutions/object_blurrer.py
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/object_cropper.py
  ultralytics/solutions/parking_management.py
  ultralytics/solutions/queue_management.py
  ultralytics/solutions/region_counter.py
  ultralytics/solutions/security_alarm.py
  ultralytics/solutions/solutions.py
  ultralytics/solutions/speed_estimation.py
  ultralytics/solutions/streamlit_inference.py
  ultralytics/solutions/trackzone.py
  ultralytics/solutions/vision_eye.py
  ultralytics/trackers/utils/kalman_filter.py
  ultralytics/utils/instance.py
  ultralytics/utils/plotting.py
Labels: TODO, documentation, enhancement, solutions

#16563 Updated stale actions rules
  .github/workflows/stale.yml
Labels: TODO, enhancement, devops

#19496 Align code examples with Google-style
  ultralytics/data/base.py
  ultralytics/data/converter.py
  ultralytics/data/utils.py
  ultralytics/engine/model.py
  ultralytics/engine/tuner.py
  ultralytics/hub/__init__.py
  ultralytics/models/fastsam/model.py
  ultralytics/models/nas/model.py
  ultralytics/models/nas/predict.py
  ultralytics/models/nas/val.py
  ultralytics/models/rtdetr/predict.py
  ultralytics/models/rtdetr/train.py
  ultralytics/models/rtdetr/val.py
  ultralytics/models/yolo/classify/predict.py
  ultralytics/models/yolo/classify/train.py
  ultralytics/models/yolo/classify/val.py
  ultralytics/models/yolo/detect/predict.py
  ultralytics/models/yolo/detect/train.py
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/obb/predict.py
  ultralytics/models/yolo/obb/train.py
  ultralytics/models/yolo/obb/val.py
  ultralytics/models/yolo/pose/predict.py
  ultralytics/models/yolo/pose/train.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/models/yolo/segment/predict.py
  ultralytics/models/yolo/segment/train.py
  ultralytics/models/yolo/segment/val.py
  ultralytics/models/yolo/world/train.py
  ultralytics/models/yolo/world/train_world.py
  ultralytics/nn/modules/__init__.py
  ultralytics/nn/tasks.py
  ultralytics/utils/__init__.py
  ultralytics/utils/checks.py
  ultralytics/utils/downloads.py
  ultralytics/utils/instance.py
  ultralytics/utils/ops.py
  ultralytics/utils/plotting.py
  ultralytics/utils/torch_utils.py
  ultralytics/utils/tuner.py
Labels: TODO, documentation, enhancement

#19668 `ultralytics 8.3.89` TensorFlow 2.19.0 compatibility updates
  .github/workflows/ci.yml
  docker/Dockerfile-cpu
  docker/Dockerfile-jetson-jetpack4
  docker/Dockerfile-jetson-jetpack5
  docker/Dockerfile-python
  pyproject.toml
  ultralytics/__init__.py
Labels: enhancement, exports

#19665 Fix links.yml
  .github/workflows/links.yml
Labels: devops

#19663 Fix layer counts in model YAMLs
  ultralytics/cfg/models/11/yolo11-cls.yaml
  ultralytics/cfg/models/11/yolo11-obb.yaml
  ultralytics/cfg/models/11/yolo11-pose.yaml
  ultralytics/cfg/models/11/yolo11-seg.yaml
  ultralytics/cfg/models/11/yolo11.yaml
  ultralytics/cfg/models/v8/yolov8-ghost-p2.yaml
  ultralytics/cfg/models/v8/yolov8-ghost-p6.yaml
  ultralytics/cfg/models/v8/yolov8-ghost.yaml
  ultralytics/cfg/models/v8/yolov8-obb.yaml
  ultralytics/cfg/models/v8/yolov8-p6.yaml
  ultralytics/cfg/models/v8/yolov8-rtdetr.yaml
  ultralytics/cfg/models/v8/yolov8-world.yaml
  ultralytics/cfg/models/v8/yolov8-worldv2.yaml
  ultralytics/cfg/models/v8/yolov8.yaml
  ultralytics/cfg/models/v9/yolov9c-seg.yaml
  ultralytics/cfg/models/v9/yolov9c.yaml
  ultralytics/cfg/models/v9/yolov9e-seg.yaml
  ultralytics/cfg/models/v9/yolov9e.yaml
  ultralytics/cfg/models/v9/yolov9m.yaml
  ultralytics/cfg/models/v9/yolov9s.yaml
  ultralytics/cfg/models/v9/yolov9t.yaml
Labels: enhancement, segment, detect

#19651 Fix verbose for Solutions
  docs/en/solutions/index.md
  ultralytics/cfg/__init__.py
  ultralytics/solutions/solutions.py
Labels: documentation, fixed, solutions

#19653 Fix `formatToSquare` bug in YOLOv8 C++ example
  examples/YOLOv8-CPP-Inference/inference.cpp
Labels: bug, detect

#19675 Fix solutions CI
  ultralytics/cfg/__init__.py
Labels: solutions, devops

#19695 Large Python files documentation update
  docs/en/models/yolov6.md
  ultralytics/data/utils.py
  ultralytics/engine/exporter.py
  ultralytics/engine/trainer.py
  ultralytics/models/sam/modules/sam.py
  ultralytics/models/sam/modules/tiny_encoder.py
  ultralytics/models/sam/predict.py
  ultralytics/nn/autobackend.py
  ultralytics/nn/modules/block.py
  ultralytics/nn/tasks.py
  ultralytics/utils/__init__.py
  ultralytics/utils/checks.py
  ultralytics/utils/loss.py
  ultralytics/utils/metrics.py
  ultralytics/utils/ops.py
  ultralytics/utils/plotting.py
  ultralytics/utils/torch_utils.py
Labels: documentation, enhancement

#17912 Add `uv pip install` for Raspberry Pi CI Benchmarks and Tests
  .github/workflows/ci.yml
Labels: TODO, dependencies, Stale, devops, embedded

#19686 `ultralytics 8.3.90` Fix MPS `get_memory()` error
  ultralytics/__init__.py
  ultralytics/engine/trainer.py
Labels: bug, enhancement

#19700 Improved visualization of labels in classify task for better Comet integration
  ultralytics/data/utils.py
  ultralytics/utils/callbacks/comet.py
  ultralytics/utils/plotting.py
Labels: documentation, enhancement, classify

#19705 Update SAM vs YOLO benchmarks
  docs/en/models/fast-sam.md
  docs/en/models/sam-2.md
  docs/en/models/sam.md
Labels: documentation, segment

#19712 `ultralytics 8.3.91` Simplify `tensorflow` installation
  tests/test_exports.py
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
Labels: dependencies, exports

#19727 Add `ai-edge-litert>=1.2.0` to exporter.py
  ultralytics/engine/exporter.py
Labels: dependencies, exports

#19722 Fix `Autobackend` Python version check
  ultralytics/hub/session.py
  ultralytics/nn/autobackend.py
  ultralytics/utils/__init__.py
Labels: bug, embedded

#19731 Docs `/usage` updates
  docs/en/index.md
  docs/en/models/fast-sam.md
  docs/en/models/sam-2.md
  docs/en/models/sam.md
  docs/en/models/yolo-nas.md
  docs/en/models/yolov10.md
  docs/en/models/yolov8.md
  docs/en/models/yolov9.md
  docs/en/quickstart.md
  docs/en/usage/callbacks.md
  docs/en/usage/cfg.md
  docs/en/usage/cli.md
  docs/en/usage/engine.md
  docs/en/usage/python.md
  docs/en/usage/simple-utilities.md
Labels: documentation

#19734 Fix broken links in docs
  docs/en/quickstart.md
  docs/en/usage/cfg.md
  docs/en/usage/engine.md
  docs/en/usage/python.md
  docs/en/usage/simple-utilities.md
Labels: documentation

#19718 Expose `txt_color` parameter for Results plots
  ultralytics/engine/results.py
Labels: enhancement, HUB, classify

#19739 `ultralytics 8.3.92` Fix `single_cls` training cache error
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/data/dataset.py
  ultralytics/data/utils.py
Labels: bug, enhancement

#19760 Update style.css announcement bar AVIF
  docs/overrides/stylesheets/style.css
Labels: documentation

#19763 Fix Docs CSS, Javascript and HTML minifcation
  docs/build_docs.py
Labels: documentation

#19764 Update macros
  docs/en/macros/export-args.md
  docs/en/macros/predict-args.md
  docs/en/macros/sam-auto-annotate.md
  docs/en/macros/validation-args.md
  docs/en/macros/visualization-args.md
Labels: documentation, enhancement, exports

#19766 Create YOLOE Docs page
  docs/en/models/index.md
  docs/en/models/yoloe.md
  mkdocs.yml
Labels: documentation, enhancement

#19747 `ultralytics 8.3.93` Fix TorchScript Model with NMS loading error
  docs/en/models/yoloe.md
  ultralytics/__init__.py
  ultralytics/nn/autobackend.py
Labels: bug, detect, exports

#19776 Update YOLOE Docs page
  docs/en/models/yoloe.md
  ultralytics/utils/__init__.py
  ultralytics/utils/callbacks/raytune.py
Labels: documentation, detect

#19771 Use lowercase `dict/list/tuple` for type hint in docstrings
  examples/RTDETR-ONNXRuntime-Python/main.py
  examples/YOLOv8-Segmentation-ONNXRuntime-Python/main.py
  tests/conftest.py
  ultralytics/cfg/__init__.py
  ultralytics/data/augment.py
  ultralytics/data/base.py
  ultralytics/data/converter.py
  ultralytics/data/dataset.py
  ultralytics/data/split_dota.py
  ultralytics/engine/exporter.py
  ultralytics/engine/model.py
  ultralytics/engine/predictor.py
  ultralytics/engine/results.py
  ultralytics/engine/trainer.py
  ultralytics/engine/tuner.py
  ultralytics/engine/validator.py
  ultralytics/hub/session.py
  ultralytics/hub/utils.py
  ultralytics/models/fastsam/model.py
  ultralytics/models/fastsam/predict.py
  ultralytics/models/fastsam/val.py
  ultralytics/models/nas/predict.py
  ultralytics/models/rtdetr/model.py
  ultralytics/models/rtdetr/predict.py
  ultralytics/models/rtdetr/train.py
  ultralytics/models/rtdetr/val.py
  ultralytics/models/sam/model.py
  ultralytics/models/sam/modules/blocks.py
  ultralytics/models/sam/predict.py
  ultralytics/models/utils/loss.py
  ultralytics/models/utils/ops.py
  ultralytics/models/yolo/classify/predict.py
  ultralytics/models/yolo/classify/train.py
  ultralytics/models/yolo/classify/val.py
  ultralytics/models/yolo/detect/predict.py
  ultralytics/models/yolo/detect/train.py
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/obb/val.py
  ultralytics/models/yolo/pose/train.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/models/yolo/segment/predict.py
  ultralytics/models/yolo/segment/val.py
  ultralytics/models/yolo/world/train.py
  ultralytics/models/yolo/world/train_world.py
  ultralytics/nn/autobackend.py
  ultralytics/nn/modules/block.py
  ultralytics/nn/modules/transformer.py
  ultralytics/nn/tasks.py
  ultralytics/solutions/analytics.py
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/region_counter.py
  ultralytics/solutions/solutions.py
  ultralytics/solutions/streamlit_inference.py
  ultralytics/trackers/basetrack.py
  ultralytics/trackers/utils/gmc.py
  ultralytics/utils/__init__.py
  ultralytics/utils/callbacks/wb.py
  ultralytics/utils/ops.py
  ultralytics/utils/plotting.py
  ultralytics/utils/torch_utils.py
Labels: documentation

#19786 Fix JS Minification
  docs/build_docs.py
  docs/en/models/yoloe.md
Labels: documentation

#19789 Fix `tiger-pose` dataset description in docs
  docs/en/datasets/pose/index.md
Labels: documentation, pose

#19792 `ultralytics 8.3.94` Limit Segment val plots to 50 items/image for speed
  ultralytics/__init__.py
  ultralytics/models/yolo/segment/val.py
Labels: enhancement, segment

#19806 Add quotes for solutions CLI arguments
  docs/en/guides/instance-segmentation-and-tracking.md
  docs/en/guides/object-blurring.md
  docs/en/guides/object-cropping.md
  docs/en/guides/vision-eye.md
  docs/en/guides/workouts-monitoring.md
  docs/en/quickstart.md
Labels: TODO, documentation, solutions

#19813 Fix tip display in `YOLOE.md`
  docs/en/models/yoloe.md
Labels: documentation

#19817 FROM pytorch/pytorch:2.6.0-cuda12.6-cudnn9-runtime
  docker/Dockerfile
Labels: dependencies, devops

#19819 Require `coremltools>=8.0`
  .github/workflows/ci.yml
  pyproject.toml
  tests/test_exports.py
  ultralytics/engine/exporter.py
  ultralytics/utils/benchmarks.py
  ultralytics/utils/checks.py
Labels: dependencies, exports

#19820 Add https://youtu.be/EXIpyYVEjoI to docs
  docs/en/integrations/vscode.md
Labels: documentation

#19828 Update GitHub banner redirect
  README.md
  README.zh-CN.md
Labels: documentation

#19835 Fix `latest-nvidia-cuda` Docker tag
  .github/workflows/docker.yml
  docker/Dockerfile-nvidia-cuda
Labels: enhancement, devops

#19836 Docker python3 > python symbolic links
  docker/Dockerfile-arm64
  docker/Dockerfile-nvidia-cuda
Labels: dependencies, devops

#19840 Fix check_version() report with multiple constraints
  ultralytics/utils/checks.py
Labels: enhancement, fixed

#19841 Update Raspberry Pi doc with overclock information
  docs/en/guides/raspberry-pi.md
Labels: TODO, documentation, enhancement, embedded

#19842 Update Docker doc with missing Dockerfiles
  docs/en/guides/docker-quickstart.md
Labels: TODO, documentation, enhancement, embedded

#19845 `ultralytics 8.3.96` Preinstall `tensorrt` and `onnxruntime-gpu` in Dockerfile
  .github/workflows/docker.yml
  docker/Dockerfile
  docker/Dockerfile-cpu
  docker/Dockerfile-nvidia-cuda
  docker/Dockerfile-python
  ultralytics/__init__.py
Labels: enhancement, dependencies, devops

#19865 Remove /SECURITY redirect in mkdocs.yml
  mkdocs.yml
Labels: documentation

#19866 Fix Example: -> Examples:
  ultralytics/utils/__init__.py
Labels: documentation

#19876 Pin `paddlepaddle<=3.0.0` to avoid bug in latest release
  docker/Dockerfile
  docker/Dockerfile-cpu
  docker/Dockerfile-python
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: dependencies, exports

#19875 Adopt H1 headers for Docs page HTML <title>
  docs/overrides/javascript/benchmark.js
  docs/overrides/javascript/extra.js
  docs/overrides/javascript/giscus.js
  docs/overrides/javascript/tablesort.js
  docs/overrides/main.html
  docs/overrides/partials/comments.html
  docs/overrides/stylesheets/style.css
  tests/test_solutions.py
  ultralytics/data/annotator.py
  ultralytics/data/scripts/download_weights.sh
  ultralytics/data/scripts/get_coco.sh
  ultralytics/data/scripts/get_coco128.sh
  ultralytics/data/scripts/get_imagenet.sh
  ultralytics/utils/callbacks/comet.py
Labels: documentation, enhancement

#19883 Fix typo in notebooks
  examples/heatmaps.ipynb
  examples/hub.ipynb
  examples/object_counting.ipynb
  examples/object_tracking.ipynb
  examples/tutorial.ipynb
Labels: documentation, Notebook

#19765 `ultralytics 8.3.97` Update Dockerfile-cpu Sony IMX export tools
  docker/Dockerfile-cpu
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: TODO, enhancement, dependencies

#19900 Fix C++ Example letterbox
  examples/YOLOv8-LibTorch-CPP-Inference/main.cc
Labels: bug, detect

#19882 Fix NAS post-processing
  docs/en/models/yolo-nas.md
  ultralytics/models/nas/model.py
  ultralytics/models/nas/predict.py
  ultralytics/models/nas/val.py
Labels: enhancement

#19906 README enhancements
  CONTRIBUTING.md
  README.md
  README.zh-CN.md
  docs/README.md
  docs/coming_soon_template.md
  docs/en/help/contributing.md
  examples/README.md
  examples/RTDETR-ONNXRuntime-Python/README.md
  examples/YOLO-Series-ONNXRuntime-Rust/README.md
  examples/YOLOv8-Action-Recognition/README.md
  examples/YOLOv8-Action-Recognition/readme.md
  examples/YOLOv8-CPP-Inference/README.md
  examples/YOLOv8-LibTorch-CPP-Inference/README.md
  examples/YOLOv8-ONNXRuntime-CPP/README.md
  examples/YOLOv8-ONNXRuntime-Rust/README.md
  examples/YOLOv8-ONNXRuntime/README.md
  examples/YOLOv8-OpenCV-ONNX-Python/README.md
  examples/YOLOv8-OpenVINO-CPP-Inference/README.md
  examples/YOLOv8-Region-Counter/README.md
  examples/YOLOv8-Region-Counter/readme.md
  examples/YOLOv8-SAHI-Inference-Video/README.md
  examples/YOLOv8-SAHI-Inference-Video/readme.md
  examples/YOLOv8-Segmentation-ONNXRuntime-Python/README.md
  examples/YOLOv8-TFLite-Python/README.md
  ultralytics/cfg/models/README.md
  ultralytics/trackers/README.md
Labels: documentation, enhancement

#19921 Fix keypoints being clipped rather than hidden
  ultralytics/utils/instance.py
Labels: enhancement, pose

#19905 `ultralytics 8.3.98` Sony IMX Java Runtime Environment>=17
  docker/Dockerfile-cpu
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
Labels: dependencies, exports

#19925 Update Dockerfile-python with JRE
  docker/Dockerfile-python
Labels: dependencies, exports

#19861 Update object tracking examples in docs
  docs/en/modes/track.md
  ultralytics/trackers/README.md
Labels: TODO, documentation, track

#19846 New Mirror Repository GitHub Action
  .github/workflows/mirror-to-dagshub.yml
Labels: enhancement, devops

#19926 Fix Mirror Action
  .github/workflows/mirror.yml
Labels: devops

#19949 Update assets links
  docs/en/datasets/detect/open-images-v7.md
  docs/en/models/fast-sam.md
  docs/en/models/mobile-sam.md
  docs/en/models/rtdetr.md
  docs/en/models/sam.md
  docs/en/models/yolo-nas.md
  docs/en/models/yolo-world.md
  docs/en/models/yoloe.md
  docs/en/models/yolov10.md
  docs/en/models/yolov5.md
  docs/en/models/yolov8.md
  docs/en/models/yolov9.md
Labels: TODO, documentation
