Repository ultralytics/ultralytics, pull requests merged in 2025-05, with the labels that each got.

#20442 Rename 'profile' methods to avoid conflicts
  docs/en/reference/utils/torch_utils.md
  tests/test_cuda.py
  tests/test_python.py
  ultralytics/utils/autobatch.py
  ultralytics/utils/benchmarks.py
  ultralytics/utils/torch_utils.py
Labels: documentation, enhancement

#20445 Optimize Result.verbose()
  ultralytics/engine/results.py
Labels: enhancement, detect, classify

#20436 Fix TFLite GPU delegate on Android
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: enhancement, exports

#20449 Fix `IndexError` with empty predictions when using ReID
  ultralytics/models/yolo/detect/predict.py
  ultralytics/trackers/track.py
Labels: enhancement, track, detect

#20450 `ultralytics 8.3.123` Rockchip RKNN export INT8 quantization support
  docs/en/integrations/rockchip-rknn.md
  docs/en/macros/export-table.md
  examples/tutorial.ipynb
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
Labels: documentation, enhancement, exports

#20452 Update region to `640×360` image resolution for CI compatibility
  docs/mkdocs_github_authors.yaml
  ultralytics/solutions/solutions.py
  ultralytics/solutions/trackzone.py
Labels: TODO, enhancement, solutions

#20457 Scope requests, psutils, thop imports
  ultralytics/data/base.py
  ultralytics/data/loaders.py
  ultralytics/data/utils.py
  ultralytics/engine/model.py
  ultralytics/models/sam/model.py
  ultralytics/models/sam/modules/tiny_encoder.py
  ultralytics/models/sam/predict.py
  ultralytics/nn/tasks.py
  ultralytics/utils/__init__.py
  ultralytics/utils/checks.py
  ultralytics/utils/dist.py
  ultralytics/utils/downloads.py
  ultralytics/utils/torch_utils.py
Labels: enhancement, dependencies

#20462 Scope `matplotlib` imports
  ultralytics/solutions/analytics.py
  ultralytics/utils/__init__.py
  ultralytics/utils/checks.py
  ultralytics/utils/metrics.py
  ultralytics/utils/plotting.py
Labels: enhancement, dependencies

#20467 Add `show_conf` and `show_labels` in Solutions docs
  docs/en/guides/distance-calculation.md
  docs/en/guides/heatmaps.md
  docs/en/guides/instance-segmentation-and-tracking.md
  docs/en/guides/object-blurring.md
  docs/en/guides/object-counting.md
  docs/en/guides/queue-management.md
  docs/en/guides/region-counting.md
  docs/en/guides/security-alarm-system.md
  docs/en/guides/speed-estimation.md
  docs/en/guides/trackzone.md
  docs/en/guides/vision-eye.md
  docs/en/guides/workouts-monitoring.md
  docs/en/solutions/index.md
Labels: TODO, documentation, enhancement, solutions

#20464 Fix string `None` value for `workspace` config
  ultralytics/cfg/default.yaml
Labels: enhancement, exports

#20470 `ultralytics 8.3.125` Fast `YAML` class with lazy init and C-based ops
  docs/en/reference/utils/__init__.md
  examples/RTDETR-ONNXRuntime-Python/main.py
  examples/YOLOv8-ONNXRuntime/main.py
  examples/YOLOv8-OpenCV-ONNX-Python/main.py
  examples/YOLOv8-Segmentation-ONNXRuntime-Python/main.py
  examples/YOLOv8-TFLite-Python/main.py
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/cfg/__init__.py
  ultralytics/cfg/default.yaml
  ultralytics/data/utils.py
  ultralytics/engine/exporter.py
  ultralytics/engine/model.py
  ultralytics/engine/trainer.py
  ultralytics/engine/tuner.py
  ultralytics/hub/session.py
  ultralytics/models/yolo/model.py
  ultralytics/nn/autobackend.py
  ultralytics/nn/tasks.py
  ultralytics/trackers/track.py
  ultralytics/utils/__init__.py
  ultralytics/utils/benchmarks.py
  ultralytics/utils/checks.py
Labels: enhancement, dependencies

#15989 Sorted args alphabetically
  ultralytics/utils/checks.py
Labels: TODO, enhancement, Stale, devops

#20475 Fix `collections.Iterable` TQDM Warning
  ultralytics/utils/__init__.py
  ultralytics/utils/checks.py
Labels: enhancement

#20451 `ultralytics 8.3.126` CUDA idle `device` auto-assignment
  docs/en/macros/train-args.md
  docs/en/modes/train.md
  docs/en/reference/utils/autodevice.md
  mkdocs.yml
  tests/test_cuda.py
  ultralytics/__init__.py
  ultralytics/cfg/default.yaml
  ultralytics/engine/trainer.py
  ultralytics/utils/autodevice.py
  ultralytics/utils/benchmarks.py
  ultralytics/utils/checks.py
  ultralytics/utils/torch_utils.py
Labels: TODO, enhancement, dependencies

#20476 Remove duplicate `device` argument from tracker args
  ultralytics/solutions/solutions.py
Labels: TODO, enhancement, track

#20397 `ultralytics 8.3.127` New Visual Similarity Search Solution
  docs/en/guides/similarity-search.md
  docs/en/reference/solutions/similarity_search.md
  docs/en/solutions/index.md
  mkdocs.yml
  pyproject.toml
  tests/test_solutions.py
  ultralytics/__init__.py
  ultralytics/solutions/__init__.py
  ultralytics/solutions/config.py
  ultralytics/solutions/similarity_search.py
  ultralytics/solutions/solutions.py
  ultralytics/solutions/templates/similarity-search.html
Labels: documentation, enhancement, solutions

#20489 Add MINMAX_CALIBRATION info to TensorRT Doc
  docs/en/integrations/tensorrt.md
Labels: TODO, documentation, exports

#20484 Add `templates` folder in the `pyproject.toml` package-data
  pyproject.toml
Labels: TODO, enhancement, dependencies, solutions

#20494 Mkdocs language switcher
  mkdocs.yml
Labels: documentation, enhancement

#20501 Fix language switcher links
  docs/build_docs.py
Labels: documentation, enhancement

#20485 Fix Python version to downgrade `numpy` for TensorRT inference on JetPack 5
  ultralytics/nn/autobackend.py
Labels: TODO, enhancement, embedded, exports

#20504 Fix language switch HTML solution with JS
  docs/build_docs.py
  docs/mkdocs_github_authors.yaml
  docs/overrides/javascript/extra.js
  mkdocs.yml
Labels: documentation, enhancement

#20507 Include arguments details in the `VisualAISearch` documentation
  docs/en/guides/similarity-search.md
  docs/en/macros/solutions-args.md
Labels: TODO, documentation, enhancement

#20516 Add checks for multi-GPU training
  tests/test_cuda.py
Labels: enhancement, devops

#20513 Use original `CLIP` module for `similarity_search`
  ultralytics/solutions/similarity_search.py
Labels: enhancement, dependencies, solutions

#20502 Fix DDP training
  ultralytics/engine/trainer.py
Labels: bug

#20499 `ultralytics 8.3.128` Fix ReID feature shape check and add tests
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/models/yolo/detect/predict.py
  ultralytics/trackers/bot_sort.py
  ultralytics/trackers/track.py
Labels: enhancement, track

#20519 Add instructions to enable TensorBoard
  docs/en/integrations/tensorboard.md
Labels: documentation

#20529 Scope getting `dla` from metadata
  ultralytics/nn/autobackend.py
Labels: enhancement, embedded, exports

#20548 Fix benchmark note in docs
  docs/en/guides/nvidia-jetson.md
  docs/en/guides/raspberry-pi.md
  docs/en/integrations/openvino.md
Labels: TODO, documentation

#20483 Update `check_yaml` to accept Path and str
  ultralytics/utils/checks.py
Labels: enhancement

#20531 Add `on_model_save` callback with Python example to Callbacks docs
  docs/en/usage/callbacks.md
Labels: documentation, enhancement

#20556 Potential fix for format.yml missing `permissions`
  .github/workflows/format.yml
Labels: enhancement, devops

#20448 Add ONNX CUDA CI
  tests/test_cuda.py
  tests/test_exports.py
  ultralytics/data/split.py
Labels: TODO, enhancement, devops, exports

#20466 `ultralytics 8.1.130` Faster `model.fuse()` operations
  ultralytics/__init__.py
  ultralytics/nn/autobackend.py
Labels: TODO, enhancement, detect

#20575 Allow image compression `>178.9M` pixels
  ultralytics/data/utils.py
Labels: bug, enhancement

#20581 Use `ultralytics-actions>=0.0.73`
  examples/YOLO-Series-ONNXRuntime-Rust/src/main.rs
  examples/YOLOv8-ONNXRuntime-Rust/src/cli.rs
  examples/YOLOv8-ONNXRuntime-Rust/src/lib.rs
  examples/YOLOv8-ONNXRuntime-Rust/src/main.rs
  examples/YOLOv8-ONNXRuntime-Rust/src/model.rs
  examples/YOLOv8-ONNXRuntime-Rust/src/ort_backend.rs
  examples/YOLOv8-ONNXRuntime-Rust/src/yolo_result.rs
Labels: documentation

#20553 Add YOLO11 Triton CPP Example
  examples/YOLO11-Triton-CPP/CMakeLists.txt
  examples/YOLO11-Triton-CPP/README.md
  examples/YOLO11-Triton-CPP/inference.cpp
  examples/YOLO11-Triton-CPP/inference.hpp
  examples/YOLO11-Triton-CPP/main.cpp
Labels: documentation, enhancement, detect

#20571 Exempt TODO PRs from stale
  .github/workflows/stale.yml
  examples/YOLO11-Triton-CPP/inference.cpp
  examples/YOLO11-Triton-CPP/inference.hpp
  examples/YOLO11-Triton-CPP/main.cpp
Labels: enhancement, devops

#20565 `ultralytics 8.3.131` Optimize `grayscale` model inference pipeline
  ultralytics/__init__.py
  ultralytics/data/build.py
  ultralytics/data/loaders.py
  ultralytics/engine/predictor.py
  ultralytics/utils/patches.py
  ultralytics/utils/plotting.py
Labels: enhancement, detect

#20574 New HomeObjects-3K dataset
  docs/en/datasets/detect/homeobjects-3k.md
  docs/en/datasets/detect/index.md
  docs/en/datasets/index.md
  mkdocs.yml
  ultralytics/cfg/datasets/HomeObjects-3K.yaml
  ultralytics/models/yolo/yoloe/predict.py
  ultralytics/models/yolo/yoloe/train_seg.py
  ultralytics/solutions/object_blurrer.py
  ultralytics/solutions/vision_eye.py
  ultralytics/utils/autodevice.py
  ultralytics/utils/callbacks/neptune.py
Labels: documentation, enhancement, detect

#20562 Add https://youtu.be/IYWQZvtOy_Q to docs
  docs/en/guides/preprocessing_annotated_data.md
Labels: documentation, enhancement

#20563 Update `YOLOv8` references to `Ultralytics YOLO` in docstrings
  examples/YOLOv8-Region-Counter/yolov8_region_counter.py
  ultralytics/data/dataset.py
  ultralytics/nn/modules/block.py
  ultralytics/nn/tasks.py
  ultralytics/utils/checks.py
  ultralytics/utils/metrics.py
Labels: documentation

#20582 Remove YOLOv10 from Raspberry Pi Benchmarks CI
  .github/workflows/ci.yml
Labels: TODO, devops, embedded

#20584 Scope getting `masks` from segmentation model
  ultralytics/solutions/instance_segmentation.py
  ultralytics/solutions/solutions.py
Labels: TODO, enhancement, segment, solutions, devops

#20585 Add object counting support for `OBB` task
  ultralytics/solutions/heatmap.py
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/solutions.py
Labels: enhancement, OBB, track

#20547 Add `kpt_shape` validation in Pose Trainer with clear error handling
  ultralytics/engine/trainer.py
  ultralytics/models/yolo/detect/train.py
  ultralytics/models/yolo/pose/train.py
  ultralytics/models/yolo/world/train_world.py
Labels: TODO, enhancement, pose

#20567 `ultralytics 8.3.32` Always transfer `Conv` layer pretrained weights
  ultralytics/__init__.py
  ultralytics/nn/tasks.py
Labels: TODO, enhancement

#20602 Use `boats.jpg` for obb `predict` with Python code example
  ultralytics/engine/model.py
Labels: enhancement, OBB

#20592 Update error hint to reference `coco8.yaml` instead of `dota8.yaml`
  ultralytics/utils/loss.py
Labels: documentation, OBB

#20438 Add NVIDIA Jetson Self-Hosted GitHub Runners
  .github/workflows/ci.yml
  tests/test_cuda.py
  ultralytics/utils/checks.py
Labels: TODO, devops, embedded, exports

#20606 Raise RuntimeError when no valid images exist
  ultralytics/__init__.py
  ultralytics/data/dataset.py
Labels: bug, enhancement

#20607 `ultralytics 8.3.133` Search relative YAML dataset paths in training
  ultralytics/data/utils.py
Labels: enhancement, detect

#20603 Fix pretrained weights loading for first convolution layer
  tests/test_cli.py
  ultralytics/nn/tasks.py
Labels: enhancement, detect

#20608 Pin `onnx>=1.12.0,<1.18.0` in pyproject.toml
  pyproject.toml
  ultralytics/engine/exporter.py
Labels: dependencies, fixed, exports

#20609 Temporarily disable Rockchip RKNN INT8 export support
  docs/en/integrations/rockchip-rknn.md
  docs/en/macros/export-table.md
  examples/tutorial.ipynb
  ultralytics/engine/exporter.py
Labels: TODO, documentation, embedded, exports

#20619 Remove emoji for `LOGGER.info` in `to_sql` method and `security-alarm` solution
  ultralytics/engine/results.py
  ultralytics/solutions/security_alarm.py
Labels: documentation, detect

#20623 Add timeout for Conda CI to early stop extended runs
  .github/workflows/ci.yml
Labels: TODO, enhancement, devops

#20632 Use `defaultdict` for classwise object counting
  ultralytics/solutions/heatmap.py
  ultralytics/solutions/object_counter.py
Labels: enhancement, solutions

#20633 Replace list-based state tracking with `defaultdict` in `AIGym`
  ultralytics/solutions/ai_gym.py
Labels: enhancement, solutions

#20637 Add tests for solutions CLI examples
  tests/test_cli.py
Labels: enhancement, solutions

#20634 Fix `grayscale` models tracking on videos
  ultralytics/data/build.py
  ultralytics/data/loaders.py
  ultralytics/trackers/byte_tracker.py
  ultralytics/trackers/utils/gmc.py
Labels: enhancement, track

#20636 Fix `copy_paste` for grayscale images
  ultralytics/data/augment.py
Labels: bug, enhancement

#20644 Cache `check_font` result
  ultralytics/utils/checks.py
Labels: enhancement

#20643 Fix `cv2.waitKey` in solutions for Docker tests
  ultralytics/cfg/__init__.py
Labels: TODO, enhancement, solutions

#20659 Add missing validation metrics in `pose.md`
  docs/en/tasks/pose.md
Labels: documentation, pose

#20661 YOLOE: reuse prompt when using `refer_image`
  ultralytics/models/yolo/model.py
Labels: enhancement, detect

#20664 Update benchmarks doc with NVIDIA Jetson AGX Orin Developer Kit (64GB)
  docs/en/guides/nvidia-jetson.md
Labels: TODO, documentation, embedded, exports

#20668 Potential fixes for Actions code scanning alerts
  .github/workflows/docs.yml
  .github/workflows/merge-main-into-prs.yml
  .github/workflows/publish.yml
Labels: enhancement, devops

#20665 Scope `opencv` for solutions in `__init__.py`
  ultralytics/cfg/__init__.py
Labels: enhancement, solutions

#20674 Fix invalid task information on warning
  ultralytics/cfg/__init__.py
Labels: enhancement, track

#20509 `ultralytics 8.3.136` Eliminate `seaborn` depencency
  pyproject.toml
  ultralytics/__init__.py
  ultralytics/utils/metrics.py
  ultralytics/utils/plotting.py
Labels: enhancement, dependencies

#20569 Use `onnxslim>=0.1.53` and simplify when `dynamic=True`
  .github/workflows/ci.yml
  tests/test_cuda.py
  tests/test_exports.py
  ultralytics/engine/exporter.py
Labels: enhancement, exports

#20480 `ultralytics 8.3.137` YOLO-World text features cache optimization
  ultralytics/__init__.py
  ultralytics/models/yolo/world/train.py
  ultralytics/models/yolo/world/train_world.py
  ultralytics/models/yolo/yoloe/train.py
  ultralytics/nn/tasks.py
  ultralytics/nn/text_model.py
Labels: TODO, enhancement, detect

#20456 Update events
  ultralytics/engine/exporter.py
  ultralytics/hub/utils.py
  ultralytics/utils/callbacks/hub.py
  ultralytics/utils/checks.py
  ultralytics/utils/torch_utils.py
Labels: TODO, enhancement, HUB, exports

#20654 Improve solutions coverage to `85%` and overall repo up by `+0.8%`
  tests/test_solutions.py
Labels: enhancement, segment, solutions

#20514 Updates split ops to use `maxsplit` arg
  docs/build_docs.py
  docs/en/guides/kfold-cross-validation.md
  ultralytics/cfg/__init__.py
  ultralytics/data/base.py
  ultralytics/data/loaders.py
  ultralytics/engine/exporter.py
  ultralytics/engine/trainer.py
  ultralytics/engine/validator.py
  ultralytics/hub/auth.py
  ultralytics/models/yolo/obb/val.py
  ultralytics/models/yolo/world/train.py
  ultralytics/models/yolo/yoloe/val.py
  ultralytics/solutions/streamlit_inference.py
  ultralytics/utils/__init__.py
  ultralytics/utils/checks.py
  ultralytics/utils/downloads.py
  ultralytics/utils/export.py
  ultralytics/utils/plotting.py
  ultralytics/utils/triton.py
Labels: bug, enhancement

#20685 Faster file suffix checks
  ultralytics/data/build.py
  ultralytics/engine/model.py
  ultralytics/utils/checks.py
  ultralytics/utils/downloads.py
Labels: enhancement

#16630 `ultralytics 8.3.138` Support non-square `imgsz` for Classify models
  ultralytics/__init__.py
  ultralytics/engine/predictor.py
  ultralytics/models/yolo/classify/predict.py
  ultralytics/solutions/similarity_search.py
Labels: TODO, enhancement, classify

#18116 Use `uv` in `check_requirements`
  ultralytics/utils/checks.py
Labels: enhancement, dependencies

#20690 Disable similarity search tests on RaspberryPI
  tests/test_solutions.py
Labels: enhancement, embedded

#20687 Fix YOLO11 TFJS inference error
  ultralytics/engine/exporter.py
Labels: bug, exports

#20546 `ultralytics 8.3.139` New `DataExportMixin` class for Metrics and Results exports
  docs/en/modes/val.md
  docs/en/reference/utils/__init__.md
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/engine/results.py
  ultralytics/utils/__init__.py
  ultralytics/utils/metrics.py
Labels: TODO, enhancement, detect, classify

#20693 Reorder integrations Docs
  docs/en/integrations/index.md
  mkdocs.yml
Labels: documentation

#20696 Enable ONNX tests for NVIDIA Jetson CIs
  tests/test_cuda.py
Labels: TODO, devops, embedded, exports

#20703 Add https://youtu.be/jMbvN6uCIos and https://youtu.be/JjQ-URE0LJE to docs
  docs/en/datasets/obb/dota-v2.md
  docs/en/guides/yolo-thread-safe-inference.md
Labels: documentation

#20706 Fix `to_df` method in `DataExportMixin`
  ultralytics/utils/__init__.py
Labels: enhancement, exports

#20701 Update Docstring for IMX benchmarks
  ultralytics/utils/benchmarks.py
Labels: TODO, documentation, enhancement, embedded

#20702 Adjust `to_sql` method for validation metrics
  tests/test_python.py
  ultralytics/utils/__init__.py
Labels: enhancement, exports

#20710 `ultralytics 8.3.140` Fix `uv` checks with `uv -V`
  docs/en/reference/utils/checks.md
  ultralytics/__init__.py
  ultralytics/utils/checks.py
Labels: enhancement, dependencies

#16390 Fix CUDA Error in YOLO Libtorch C++ Implementation
  examples/YOLOv8-LibTorch-CPP-Inference/main.cc
Labels: bug, devops

#20725 Clean up `TaskAlignedAssigner` module
  ultralytics/utils/tal.py
Labels: enhancement

#20714 Update `Autodevice` memory check by using percentage form
  tests/test_cuda.py
  ultralytics/utils/autodevice.py
  ultralytics/utils/torch_utils.py
Labels: enhancement, dependencies

#20704 Speed up semantic search test with 4 images for fast embedding
  tests/test_solutions.py
Labels: TODO, enhancement, devops

#20721 Eliminate `loss.detach()` temp return variable
  ultralytics/utils/loss.py
Labels: enhancement, classify

#20732 Add `HomeObjects-3K` notebook in docs
  docs/en/datasets/detect/homeobjects-3k.md
Labels: documentation, Notebook

#20715 Handle legacy `CenterCrop` in Classify prediction
  ultralytics/models/yolo/classify/predict.py
Labels: TODO, bug, classify

#20733 Simplify open-images-v7.yaml
  ultralytics/cfg/datasets/open-images-v7.yaml
Labels: documentation, enhancement

#20578 `ultralytics 8.3.141` Automatically detect RTDETR models
  ultralytics/__init__.py
  ultralytics/engine/model.py
  ultralytics/models/yolo/model.py
Labels: TODO, enhancement, detect

#20746 Remove `frozenset` from `ValueError` logs
  ultralytics/cfg/__init__.py
Labels: documentation, enhancement

#20753 Disable `setMouseCallback` where `imshow` not supported
  ultralytics/solutions/distance_calculation.py
Labels: enhancement

#20754 `ultralytics 8.3.142` Simplify `Annotator.box_label`
  ultralytics/__init__.py
  ultralytics/engine/results.py
  ultralytics/solutions/object_counter.py
  ultralytics/utils/plotting.py
Labels: enhancement, OBB, detect

#20760 Remove `is_obb` usage from `store_tracking_history`
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/solutions.py
Labels: enhancement, track, solutions

#20730 `ultralytics 8.3.143` Add Profiling for Solutions
  tests/test_solutions.py
  ultralytics/__init__.py
  ultralytics/solutions/object_cropper.py
  ultralytics/solutions/solutions.py
Labels: enhancement, solutions

#20780 AutoDevice: Add utilization criteria
  tests/test_cuda.py
  ultralytics/utils/autodevice.py
Labels: enhancement, dependencies

#20771 New chart-widget.js for charts PNG and CSV downloads
  docs/overrides/javascript/benchmark.js
  docs/overrides/javascript/chart-widget.js
  docs/overrides/stylesheets/style.css
  pyproject.toml
Labels: TODO, documentation, enhancement

#20790 Fix chart-widget.js initial positioning
  docs/overrides/javascript/chart-widget.js
Labels: documentation, enhancement

#20792 Simplify track check with `is_track` attribute
  docs/en/modes/track.md
  docs/en/usage/simple-utilities.md
  examples/YOLOv8-Action-Recognition/action_recognition.py
  examples/YOLOv8-Region-Counter/yolov8_region_counter.py
  examples/object_tracking.ipynb
  ultralytics/engine/results.py
  ultralytics/solutions/ai_gym.py
  ultralytics/solutions/heatmap.py
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/solutions.py
  ultralytics/trackers/README.md
Labels: documentation, enhancement, track

#20796 Add https://youtu.be/QkCsj2SvZc4 to docs
  docs/en/guides/model-deployment-options.md
  docs/en/guides/yolo-common-issues.md
Labels: documentation, enhancement

#20784 Simplify Solutions code
  ultralytics/engine/results.py
  ultralytics/solutions/ai_gym.py
  ultralytics/solutions/instance_segmentation.py
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/solutions.py
Labels: OBB, track, detect

#20257 `ultralytics 8.3.145` Support all export arguments for benchmark
  ultralytics/__init__.py
  ultralytics/engine/model.py
  ultralytics/utils/benchmarks.py
Labels: TODO, enhancement, exports

#20817 Docs - adding neural-magic deprecation notice
  docs/en/integrations/neural-magic.md
Labels: documentation

#20812 Update type hints and docstrings
  ultralytics/data/augment.py
  ultralytics/engine/model.py
  ultralytics/engine/validator.py
  ultralytics/models/yolo/classify/val.py
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/obb/val.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/models/yolo/segment/val.py
  ultralytics/utils/metrics.py
  ultralytics/utils/torch_utils.py
Labels: documentation, enhancement

#20829 Reuse existing `r_s` variable for intersection check
  ultralytics/solutions/object_counter.py
Labels: enhancement, track

#20821 Remove `save_crop` from validation arguments
  docs/en/macros/validation-args.md
Labels: documentation

#20814 Fix `NoneType` result when using ReID with CLI
  ultralytics/trackers/bot_sort.py
Labels: enhancement, track

#20819 Refactor benchmark checks to use format names instead of indices
  ultralytics/utils/benchmarks.py
Labels: TODO, enhancement, exports

#20837 Fix `uv` always installing to `--system` environment
  ultralytics/utils/__init__.py
  ultralytics/utils/checks.py
Labels: enhancement, dependencies, devops

#18453 Add guide for YOLOv7 ONNX inference
  docs/en/models/index.md
  docs/en/models/yolov7.md
Labels: TODO, documentation, enhancement, exports

#20731 OpenVINO docs update
  docs/en/integrations/openvino.md
Labels: TODO, documentation, enhancement, exports

#20855 Fix OBB predict example
  docs/en/tasks/obb.md
Labels: documentation, OBB

#18149 Prevent BatchNorm stats from being changed on model initialization from `yaml`
  ultralytics/nn/tasks.py
Labels: TODO

#20888 Update train method docstrings to reflect correct `batch` parameter
  ultralytics/engine/model.py
Labels: documentation
