Repository ultralytics/ultralytics, pull requests merged in 2025-01, with the labels that each got.

#18478 Add https://youtu.be/bjkt5OE_ANA and https://youtu.be/SyyCUvxw9BM to docs
  docs/en/guides/model-testing.md
  docs/en/solutions/index.md
Labels: documentation

#18479 Update page order for Ultralytics Solutions docs.
  mkdocs.yml
Labels: documentation

#18449 `ultralytics 8.3.57` Support `is_jetson()` and `is_raspberrypi()` in Docker images
  ultralytics/__init__.py
  ultralytics/utils/__init__.py
Labels: TODO, enhancement, devops, embedded

#18507 Add https://youtu.be/K69DUpSBNdA to docs
  docs/en/guides/object-counting.md
  docs/en/hub/models.md
Labels: documentation, exports

#18513 Update `yolov8` to `yolo11` in `tensorrt.md`
  docs/en/integrations/tensorrt.md
Labels: documentation, enhancement, exports

#18531 Add `multi_scale` training argument to docs
  docs/en/macros/train-args.md
Labels: documentation, enhancement

#18534 Create .dockerignore
  .dockerignore
Labels: enhancement, devops

#18327 `ultralytics 8.3.58` Use `uint8` type for TensorRT Profile
  ultralytics/__init__.py
  ultralytics/utils/benchmarks.py
Labels: enhancement, classify, exports

#18546 Add instructions to enable W&B logging
  docs/en/integrations/weights-biases.md
Labels: documentation, enhancement

#18567 Use uv for Dockerfile-jupyter
  docker/Dockerfile-jupyter
Labels: enhancement, devops, Notebook

#18565 Add retries to Docker pushes
  .github/workflows/docker.yaml
  docker/Dockerfile-jupyter
Labels: enhancement, devops

#18603 Update Benchmarks for NVIDIA DeepStream running on NVIDIA Jetson
  docs/en/guides/deepstream-nvidia-jetson.md
Labels: TODO, documentation, embedded, exports

#18580 Add benchmarks for Pi 4B/5
  docs/en/guides/coral-edge-tpu-on-raspberry-pi.md
Labels: documentation, enhancement, embedded

#18594 Update `package-seg.yaml`
  ultralytics/cfg/datasets/package-seg.yaml
Labels: documentation, segment

#18611 Verify dataset >= batch size on INT8 export calibration
  ultralytics/engine/exporter.py
Labels: enhancement, exports

#18579 Fix incorrect docstring for bbox_iou function
  ultralytics/utils/metrics.py
Labels: documentation

#18576 Include .jpg in mask converter
  ultralytics/data/converter.py
Labels: enhancement, segment

#18564 `ultralytics 8.3.59` Add ability to load any `torchvision` model as module
  docs/en/reference/nn/modules/block.md
  docs/en/reference/nn/modules/conv.md
  ultralytics/__init__.py
  ultralytics/cfg/models/11/yolo11-cls-resnet18.yaml
  ultralytics/nn/modules/__init__.py
  ultralytics/nn/modules/block.py
  ultralytics/nn/modules/conv.py
  ultralytics/nn/tasks.py
Labels: enhancement, classify

#18622 Apply Ruff 0.9.0
  ultralytics/cfg/__init__.py
  ultralytics/data/augment.py
  ultralytics/data/converter.py
  ultralytics/data/dataset.py
  ultralytics/data/utils.py
  ultralytics/engine/exporter.py
  ultralytics/engine/predictor.py
  ultralytics/engine/trainer.py
  ultralytics/engine/tuner.py
  ultralytics/models/fastsam/predict.py
  ultralytics/models/sam/modules/encoders.py
  ultralytics/models/sam/predict.py
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/obb/val.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/models/yolo/segment/val.py
  ultralytics/solutions/security_alarm.py
  ultralytics/utils/callbacks/hub.py
  ultralytics/utils/callbacks/mlflow.py
  ultralytics/utils/checks.py
  ultralytics/utils/dist.py
  ultralytics/utils/metrics.py
Labels: documentation

#18575 Add new Colab Notebooks badges to Docs
  docs/en/datasets/detect/brain-tumor.md
  docs/en/datasets/detect/medical-pills.md
  docs/en/datasets/segment/carparts-seg.md
  docs/en/datasets/segment/package-seg.md
  docs/en/guides/heatmaps.md
  docs/en/guides/object-counting.md
  docs/en/guides/sahi-tiled-inference.md
  docs/en/guides/trackzone.md
  docs/en/guides/workouts-monitoring.md
Labels: TODO, documentation, enhancement, Notebook

#18624 Apply `ruff==0.9.0` formatting
  ultralytics/cfg/__init__.py
  ultralytics/data/utils.py
  ultralytics/engine/results.py
  ultralytics/models/sam/model.py
  ultralytics/models/sam/modules/utils.py
  ultralytics/models/utils/loss.py
  ultralytics/solutions/streamlit_inference.py
  ultralytics/utils/__init__.py
  ultralytics/utils/callbacks/hub.py
  ultralytics/utils/checks.py
  ultralytics/utils/downloads.py
  ultralytics/utils/loss.py
Labels: enhancement, devops

#18645 Update `val.md`
  docs/en/modes/val.md
Labels: documentation

#18346 Update issue templates with better instructions
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: documentation, enhancement

#18650 Dockerfile FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime
  docker/Dockerfile
Labels: dependencies, devops

#18621 Add warning for `task=classify` with `mode=track`
  ultralytics/cfg/__init__.py
Labels: enhancement, track, classify

#18654 Add `mobile-sam` auto-annotation to segmentation datasets docs
  docs/en/datasets/segment/index.md
  docs/en/macros/sam-auto-annotate.md
Labels: documentation, enhancement, segment

#18649 `ultralytics 8.3.60` Fix CoreML Segment inference
  ultralytics/__init__.py
  ultralytics/nn/autobackend.py
Labels: bug, segment

#18665 Fix broken examples in SAM Predictor docstrings
  ultralytics/models/sam/predict.py
Labels: documentation, enhancement

#18666 `ultralytics 8.3.61` Restore Python 3.8 compatibility
  .github/workflows/ci.yaml
  ultralytics/__init__.py
  ultralytics/models/sam/model.py
  ultralytics/models/sam/modules/utils.py
  ultralytics/models/utils/loss.py
  ultralytics/solutions/streamlit_inference.py
  ultralytics/utils/__init__.py
Labels: enhancement, dependencies

#18668 Consistent workflow file suffix *.yml
  .github/workflows/ci.yml
  .github/workflows/docker.yml
Labels: enhancement, devops

#18671 `ci.yml` and `docker.yml` rename
  .github/workflows/format.yml
  .github/workflows/links.yml
  README.md
  README.zh-CN.md
  docs/en/datasets/explorer/explorer.md
  docs/en/help/CI.md
  docs/en/hub/index.md
  docs/en/index.md
  examples/heatmaps.ipynb
  examples/hub.ipynb
  examples/object_counting.ipynb
  examples/object_tracking.ipynb
  examples/tutorial.ipynb
Labels: documentation, devops

#18689 Fix MNN example missing BGR to RGB conversion
  docs/en/integrations/mnn.md
Labels: documentation, exports

#18651 Remove unused dict values in `items()` with `values()`
  ultralytics/engine/tuner.py
Labels: enhancement

#18695 Update 2024 to 2025
  docs/en/guides/coral-edge-tpu-on-raspberry-pi.md
  docs/mkdocs_github_authors.yaml
  mkdocs.yml
Labels: documentation

#18697 Fix random dataloader freezes
  ultralytics/data/build.py
Labels: bug, fixed

#18701 `ultralytics 8.3.62` Fix non-deterministic transforms with `albumentations>=1.4.21`
  ultralytics/__init__.py
  ultralytics/data/augment.py
Labels: bug, enhancement

#18712 Update `8.3.82` with `8.2.82` in `sam-2.md`
  docs/en/models/sam-2.md
Labels: documentation

#18717 Simplify `thop` imports
  ultralytics/data/utils.py
  ultralytics/engine/results.py
  ultralytics/nn/modules/block.py
  ultralytics/nn/tasks.py
  ultralytics/utils/torch_utils.py
Labels: enhancement, dependencies

#18641 Fix automatic optimizer LR with DDP training
  ultralytics/engine/trainer.py
Labels: bug, devops

#18719 Update HUB alt text
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/workflows/format.yml
  CONTRIBUTING.md
  docs/en/help/code-of-conduct.md
  docs/en/help/contributing.md
  docs/en/help/index.md
  docs/en/help/minimum-reproducible-example.md
  docs/en/hub/index.md
  mkdocs.yml
Labels: documentation, HUB

#18738 Fix sudo 2
  ultralytics/utils/checks.py
Labels: bug, fixed

#18746 Fixed wrong GPU comment in docker-quickstart
  docs/en/guides/docker-quickstart.md
Labels: documentation

#18742 Moved IMX under Deployment section
  docs/en/integrations/index.md
Labels: documentation, embedded

#18757 Fix YOLOv3 pre-trained weights and examples
  docs/en/models/yolov3.md
  docs/mkdocs_github_authors.yaml
Labels: documentation, detect

#18743 Add https://youtu.be/zCupPHqSLTI to docs
  docs/en/guides/model-monitoring-and-maintenance.md
Labels: documentation

#18756 Fix link redirects
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/workflows/format.yml
Labels: documentation, devops

#18761 New `is_runpod()` function
  docs/en/reference/utils/__init__.md
  ultralytics/utils/__init__.py
Labels: TODO, enhancement, devops

#18680 `ultralytics 8.3.64` new `torchvision.ops` access in model YAMLs
  docs/en/models/yolov8.md
  ultralytics/__init__.py
  ultralytics/nn/modules/block.py
  ultralytics/nn/tasks.py
Labels: TODO, enhancement, detect

#18783 Pin `numpy` 1.23.5 for JetPack 4 on NVIDIA Jetson Nano
  pyproject.toml
  ultralytics/nn/autobackend.py
Labels: TODO, dependencies, embedded, exports

#18785 Use frozenset()
  ultralytics/cfg/__init__.py
  ultralytics/nn/tasks.py
  ultralytics/trackers/utils/matching.py
  ultralytics/utils/__init__.py
  ultralytics/utils/instance.py
Labels: enhancement, devops

#18763 Adopt `macos-15` GitHub CI runners
  .github/workflows/ci.yml
Labels: devops

#18786 Update convert_plaintext_links_to_html
  docs/build_docs.py
Labels: documentation, enhancement

#16308 `ultralytics 8.3.65` Rockchip RKNN Integration for Ultralytics YOLO models
  .gitignore
  docs/en/integrations/index.md
  docs/en/integrations/rockchip-rknn.md
  docs/en/macros/export-table.md
  docs/en/reference/utils/checks.md
  docs/mkdocs_github_authors.yaml
  examples/YOLOv8-Region-Counter/yolov8_region_counter.py
  mkdocs.yml
  tests/test_exports.py
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/engine/model.py
  ultralytics/engine/predictor.py
  ultralytics/engine/results.py
  ultralytics/engine/trainer.py
  ultralytics/engine/tuner.py
  ultralytics/engine/validator.py
  ultralytics/models/yolo/classify/predict.py
  ultralytics/models/yolo/classify/train.py
  ultralytics/models/yolo/classify/val.py
  ultralytics/models/yolo/obb/predict.py
  ultralytics/models/yolo/obb/train.py
  ultralytics/models/yolo/obb/val.py
  ultralytics/models/yolo/pose/predict.py
  ultralytics/models/yolo/pose/train.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/models/yolo/segment/predict.py
  ultralytics/models/yolo/segment/train.py
  ultralytics/models/yolo/segment/val.py
  ultralytics/nn/autobackend.py
  ultralytics/nn/tasks.py
  ultralytics/solutions/ai_gym.py
  ultralytics/solutions/heatmap.py
  ultralytics/solutions/parking_management.py
  ultralytics/solutions/solutions.py
  ultralytics/utils/__init__.py
  ultralytics/utils/benchmarks.py
  ultralytics/utils/checks.py
  ultralytics/utils/downloads.py
  ultralytics/utils/loss.py
  ultralytics/utils/tuner.py
Labels: TODO, enhancement, embedded, exports

#18787 Update thumbnail for Rockchip RKNN integration page
  docs/en/integrations/rockchip-rknn.md
Labels: TODO, documentation, embedded

#18790 Cleanup TorchVision related functions
  ultralytics/cfg/models/11/yolo11-cls-resnet18.yaml
  ultralytics/nn/modules/block.py
  ultralytics/nn/modules/conv.py
  ultralytics/nn/tasks.py
Labels: enhancement, dependencies

#18813 Fix IMX onnx model path
  ultralytics/engine/exporter.py
Labels: bug, exports

#18801 New Seeedstudio reCamera Docs page
  docs/en/integrations/index.md
  docs/en/integrations/seeedstudio-recamera.md
  mkdocs.yml
Labels: documentation, embedded, exports

#18824 Add https://youtu.be/8gePl_Zcs5c to docs
  docs/en/datasets/detect/medical-pills.md
Labels: documentation, enhancement

#18823 Fix missing IMX500 export decorator
  ultralytics/engine/exporter.py
Labels: enhancement, embedded, exports

#18827 Fix spelling
  docs/en/guides/kfold-cross-validation.md
  docs/en/guides/raspberry-pi.md
  docs/en/guides/triton-inference-server.md
  docs/en/integrations/ibm-watsonx.md
  docs/en/integrations/tensorrt.md
  docs/en/models/mobile-sam.md
Labels: documentation

#18840 Fix dataset category indexes check
  ultralytics/data/utils.py
Labels: bug, enhancement

#18762 Ubuntu ARM GitHub CI runners
  .github/workflows/ci.yml
  tests/test_exports.py
  ultralytics/utils/benchmarks.py
Labels: enhancement, devops

#18842 Fix automatic optimizer LR with DDP training
  ultralytics/engine/trainer.py
Labels: bug, enhancement, devops

#18831 Update inference.cpp [bug in case of cudaEnable = false]
  examples/YOLOv8-ONNXRuntime-CPP/inference.cpp
Labels: bug, detect

#18841 RKNN export clean up
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: enhancement, exports

#18837 Move `task=classify` with `mode=track` warning to tracker `on_predict_start`
  ultralytics/cfg/__init__.py
  ultralytics/trackers/track.py
Labels: track, classify

#18846 Use TQDM class
  ultralytics/data/split_dota.py
  ultralytics/utils/__init__.py
Labels: enhancement

#18847 Fix Albumentations ImageCompression `quality_range` arg
  ultralytics/data/augment.py
Labels: enhancement

#18848 `ultralytics 8.3.66` add Rockchip RKNN export in `tutorial.ipynb`
  examples/tutorial.ipynb
  ultralytics/__init__.py
Labels: embedded, exports, Notebook

#18850 Update HUB Shared Inference API limits
  docs/en/hub/inference-api.md
Labels: documentation, HUB

#18854 Add `YOLO_TQDM_RICH` environment variable
  ultralytics/utils/__init__.py
Labels: enhancement

#18484 `ultralytics 8.3.67` NMS Export for Detect, Segment, Pose and OBB YOLO models
  docs/en/macros/export-table.md
  docs/en/reference/engine/exporter.md
  tests/test_exports.py
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/engine/results.py
  ultralytics/models/nas/val.py
  ultralytics/models/yolo/detect/predict.py
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/obb/predict.py
  ultralytics/models/yolo/obb/val.py
  ultralytics/models/yolo/pose/predict.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/models/yolo/segment/predict.py
  ultralytics/models/yolo/segment/val.py
  ultralytics/nn/autobackend.py
  ultralytics/utils/ops.py
Labels: TODO, enhancement, OBB, segment, detect, pose, exports

#18878 Simplify chart legend
  docs/en/modes/benchmark.md
  docs/overrides/javascript/benchmark.js
Labels: enhancement

#18884 Add EfficientDet to model comparisons
  docs/overrides/javascript/benchmark.js
Labels: documentation, enhancement

#18886 Add Javascript active models argument
  docs/overrides/javascript/benchmark.js
Labels: documentation, enhancement

#18887 Minify fallback on docs build
  docs/build_docs.py
Labels: documentation, enhancement, devops

#18890 Fix benchmark.js
  docs/overrides/javascript/benchmark.js
Labels: enhancement, devops

#18880 Fix export test matrices to exclude `nms` from Classify models
  docs/overrides/javascript/benchmark.js
  tests/test_exports.py
  ultralytics/engine/exporter.py
Labels: bug, exports

#18889 Fix Python Version Recommendation in AzureML Quickstart
  docs/en/guides/azureml-quickstart.md
Labels: documentation, dependencies

#18898 Fix TFLite error and OpenVINO int8 error at imgsz=32
  docs/en/guides/azureml-quickstart.md
  docs/mkdocs_github_authors.yaml
  tests/test_exports.py
  ultralytics/engine/exporter.py
Labels: enhancement, detect, exports

#18894 `ultralytics 8.3.68` Benchmarking model path fix
  ultralytics/__init__.py
  ultralytics/utils/benchmarks.py
Labels: bug, enhancement, exports

#18902 Fix YOLOv3 table
  docs/en/models/yolov3.md
Labels: documentation

#18905 Add Docs models JS charts
  docs/en/models/rtdetr.md
  docs/en/models/yolo11.md
  docs/en/models/yolov10.md
  docs/en/models/yolov5.md
  docs/en/models/yolov6.md
  docs/en/models/yolov7.md
  docs/en/models/yolov8.md
  docs/en/models/yolov9.md
  docs/model_data.py
  docs/overrides/javascript/benchmark.js
Labels: documentation, enhancement

#18910 Simplify build_docs.py
  docs/build_docs.py
Labels: documentation, devops

#18912 Fix `AutoBatch` when working with RT-DETR models
  ultralytics/models/utils/ops.py
  ultralytics/utils/torch_utils.py
Labels: bug, enhancement

#18911 Add `PP-YOLOE+` params and flops data
  docs/model_data.py
Labels: enhancement, detect

#18923 Temporarily disable Raspberry Pi CI due to maintenance
  .github/workflows/ci.yml
Labels: TODO, dependencies, devops, embedded

#18932 Fix Docs edit button links
  docs/build_docs.py
Labels: documentation, enhancement

#18917 Add imgsz check and improve logs for benchmarks
  ultralytics/utils/benchmarks.py
Labels: documentation, enhancement, exports

#18921 `ultralytics 8.3.69` New Results `to_sql()` method for SQL format
  .github/workflows/ci.yml
  docs/en/modes/predict.md
  ultralytics/__init__.py
  ultralytics/engine/results.py
  ultralytics/utils/benchmarks.py
Labels: enhancement, exports

#18935 Update torchvision compatibility table for `torch 2.6`
  ultralytics/utils/checks.py
Labels: enhancement, dependencies

#18936 Add https://youtu.be/yMR7BgwHQ3g to docs
  docs/en/datasets/index.md
  docs/en/help/contributing.md
Labels: documentation

#18740 Add support for single `export` format `benchmark`
  .github/workflows/ci.yml
  docs/en/modes/benchmark.md
  ultralytics/engine/model.py
  ultralytics/utils/benchmarks.py
Labels: TODO, enhancement, exports

#18942 mkdocs-ultralytics-plugin>=0.1.16
  mkdocs.yml
  pyproject.toml
Labels: documentation, enhancement

#18943 Pin `numpy<=2.1.1` to resolve failing --slow CI
  pyproject.toml
Labels: dependencies, devops

#18930 Add DLA specific core usage
  ultralytics/nn/autobackend.py
Labels: TODO, enhancement, devops, embedded

#18940 Minor Docs edits
  docs/en/index.md
Labels: TODO, documentation

#18945 Eliminate `numpy<2.0.0` pin for OpenVINO on macOS
  docs/mkdocs_github_authors.yaml
  pyproject.toml
Labels: enhancement, dependencies

#18852 `ultralytics 8.3.70` add `data` argument to Sony IMX500 export
  docs/en/integrations/openvino.md
  docs/en/integrations/sony-imx500.md
  docs/en/macros/export-args.md
  docs/en/macros/export-table.md
  examples/tutorial.ipynb
  ultralytics/__init__.py
Labels: TODO, documentation, exports

#18948 Add Lychee to CI Summary
  .github/workflows/links.yml
Labels: enhancement, devops

#18954 Update branch of `picamera2` in Sony IMX500 Doc
  docs/en/integrations/sony-imx500.md
Labels: TODO, documentation, embedded

#18959 Add https://youtu.be/SMSJvjUG1ko to docs
  docs/en/guides/trackzone.md
Labels: documentation, track

#18957 Enhance clarity in `results.to_` function examples.
  ultralytics/engine/results.py
Labels: documentation

#18953 Clarify relative path usage for `path` in dataset `yaml`
  docs/en/datasets/detect/index.md
  docs/en/datasets/pose/index.md
  docs/en/datasets/segment/index.md
Labels: documentation, detect, pose
