Repository ultralytics/ultralytics, pull requests merged in 2025-06, with the labels that each got.

#20834 `ultralytics 8.3.147` Confusion Matrix export to CSV, XML, HTML, JSON, and SQL formats
  docs/en/modes/val.md
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/models/yolo/classify/val.py
  ultralytics/models/yolo/detect/val.py
  ultralytics/utils/__init__.py
  ultralytics/utils/metrics.py
Labels: TODO, enhancement, research, detect, devops

#20904 Handle `numpy._core` error while loading cache
  ultralytics/data/dataset.py
  ultralytics/nn/tasks.py
Labels: bug, enhancement

#20905 `ultralytics 8.3.148` update `onnxslim>=0.1.56` dependency
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
Labels: dependencies, exports

#20912 Enable `normalize` and `decimals` support for confusion matrix export
  ultralytics/utils/metrics.py
Labels: documentation, enhancement

#20911 Fix YOLOv7 ONNX/TensorRT inference guide
  docs/en/models/yolov7.md
Labels: documentation, exports

#20884 Add `yolo11n` model support for `IMX` format in export table
  docs/en/macros/export-table.md
  examples/tutorial.ipynb
Labels: documentation, exports

#20926 Fix cancel upload bug in `parking annotator`
  ultralytics/solutions/parking_management.py
Labels: bug, solutions

#20931 Use `pytorch-cpu` for Conda CI tests
  .github/workflows/ci.yml
Labels: dependencies, devops

#20923 `ultralytics 8.3.150` Set default `conf=0.01` for OBB validation
  ultralytics/__init__.py
  ultralytics/engine/validator.py
  ultralytics/models/fastsam/val.py
  ultralytics/models/yolo/classify/val.py
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/obb/val.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/models/yolo/segment/val.py
  ultralytics/utils/benchmarks.py
Labels: enhancement, OBB

#20940 Update google_cloud_quickstart_tutorial.md
  docs/en/yolov5/environments/google_cloud_quickstart_tutorial.md
Labels: documentation

#20945 Increase the "age" of the tracklet even if there are no detections
  ultralytics/trackers/track.py
Labels: enhancement, track

#20952 `ultralytics 8.3.151` Add `decimals` argument to Metrics
  ultralytics/__init__.py
  ultralytics/utils/metrics.py
Labels: documentation, enhancement

#20966 Fix incorrect task when loading saved checkpoint
  ultralytics/engine/model.py
  ultralytics/nn/tasks.py
Labels: bug, enhancement

#20960 Clear memory if VRAM usage is high before validation.
  ultralytics/engine/trainer.py
Labels: TODO, bug, enhancement

#20972 Optimize ConfusionMatrix process_batch performance
  ultralytics/utils/metrics.py
Labels: enhancement, detect

#20949 Add custom example for classification augmentation
  docs/en/guides/yolo-data-augmentation.md
  docs/en/tasks/classify.md
Labels: TODO, documentation, classify

#20986 Update `trackers` README.md
  ultralytics/trackers/README.md
Labels: documentation, enhancement, track

#20991 Update Rockchip RKNN Doc with COCO128 Benchmarks
  docs/en/integrations/rockchip-rknn.md
Labels: TODO, documentation, embedded

#21006 Fix COCO128 typo in `rockchip-rknn.md`
  docs/en/integrations/rockchip-rknn.md
Labels: documentation, embedded

#20995 Fix incorrect category index in `metrics.summary`
  ultralytics/utils/metrics.py
Labels: TODO, documentation, enhancement

#20877 `ultralytics 8.3.153` OpenVINO COCO128 benchmarks
  docs/en/integrations/openvino.md
  ultralytics/__init__.py
Labels: TODO, documentation, enhancement, detect

#21032 Add top-k filter buttons with search bar in `similarity-search`
  ultralytics/solutions/templates/similarity-search.html
Labels: enhancement

#21022 Remove unnecessary `.cpu()` call and add `@lru_cache`
  ultralytics/solutions/ai_gym.py
  ultralytics/solutions/solutions.py
Labels: enhancement, pose, solutions

#21019 Avoid overriding `imgsz` for dynamic models
  ultralytics/engine/predictor.py
Labels: enhancement, detect

#21053 Docs: Correct batch parameter type to reflect float support
  docs/en/macros/train-args.md
Labels: documentation

#21052 Add https://youtu.be/zplKRlX3sLg to docs
  docs/en/guides/similarity-search.md
Labels: documentation, enhancement

#21057 Add argument and return type annotations to `Solutions`
  ultralytics/solutions/ai_gym.py
  ultralytics/solutions/analytics.py
  ultralytics/solutions/config.py
  ultralytics/solutions/distance_calculation.py
  ultralytics/solutions/heatmap.py
  ultralytics/solutions/instance_segmentation.py
  ultralytics/solutions/object_blurrer.py
  ultralytics/solutions/object_counter.py
  ultralytics/solutions/object_cropper.py
  ultralytics/solutions/parking_management.py
  ultralytics/solutions/queue_management.py
  ultralytics/solutions/region_counter.py
  ultralytics/solutions/security_alarm.py
  ultralytics/solutions/similarity_search.py
  ultralytics/solutions/solutions.py
  ultralytics/solutions/speed_estimation.py
  ultralytics/solutions/streamlit_inference.py
  ultralytics/solutions/trackzone.py
  ultralytics/solutions/vision_eye.py
Labels: documentation, solutions

#21051 `ultralytics 8.3.155` Fix YOLO-World `set_classes()` error after prediction
  ultralytics/__init__.py
  ultralytics/nn/tasks.py
Labels: bug, enhancement

#20891 Fix: Cache optimization for auto-batch training
  ultralytics/engine/exporter.py
  ultralytics/models/yolo/detect/train.py
  ultralytics/utils/patches.py
Labels: TODO, bug, enhancement, detect

#21086 Fix fast-sam.md links
  docs/en/models/fast-sam.md
  docs/en/reference/engine/exporter.md
  docs/en/reference/utils/patches.md
Labels: documentation

#21076 Update classification custom example
  docs/en/tasks/classify.md
Labels: documentation, classify

#21095 Enable `verify_labels` for `GroundingDataset`
  ultralytics/data/dataset.py
Labels: bug, enhancement

#20471 Update `macOS` runners and pin `OpenVINO>=2025.2.0` for `macos-15`
  .github/workflows/ci.yml
  ultralytics/engine/exporter.py
Labels: enhancement, devops

#21120 Remove the unnecessary conditional check
  ultralytics/models/yolo/pose/predict.py
  ultralytics/models/yolo/pose/val.py
Labels: pose, python

#17020 `ultralytics 8.3.157` Add `faster-coco-eval` package for COCO/LVIS evaluation
  .github/workflows/ci.yml
  docker/Dockerfile
  pyproject.toml
  tests/test_integrations.py
  ultralytics/__init__.py
  ultralytics/cfg/datasets/Objects365.yaml
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/models/yolo/segment/val.py
  ultralytics/utils/callbacks/comet.py
Labels: TODO, documentation, dependencies, detect

#21058 Improve model list order in `Streamlit` solution
  ultralytics/solutions/streamlit_inference.py
Labels: TODO, bug, solutions

#21047 Fix count display check for `show_in=False` and `show_out=False`
  ultralytics/solutions/object_counter.py
Labels: enhancement, detect

#21148 Update 301 redirects
  .github/workflows/format.yml
  README.md
  README.zh-CN.md
  docs/en/datasets/explorer/explorer.md
  docs/en/datasets/track/index.md
  docs/en/guides/similarity-search.md
  docs/en/guides/yolo-data-augmentation.md
  docs/en/index.md
  docs/en/integrations/albumentations.md
  docs/en/integrations/amazon-sagemaker.md
  docs/en/integrations/google-colab.md
  docs/en/integrations/ibm-watsonx.md
  docs/en/integrations/neural-magic.md
  docs/en/integrations/torchscript.md
  docs/en/modes/track.md
  docs/en/modes/train.md
  docs/en/yolov5/index.md
  docs/en/yolov5/tutorials/multi_gpu_training.md
  docs/en/yolov5/tutorials/neural_magic_pruning_quantization.md
  examples/YOLOv8-Action-Recognition/README.md
  examples/YOLOv8-LibTorch-CPP-Inference/README.md
  ultralytics/cfg/models/README.md
  ultralytics/trackers/README.md
Labels: documentation

#21210 YOLOE: Fix `generate_text_embeddings` for DDP training
  ultralytics/models/yolo/world/train.py
  ultralytics/models/yolo/yoloe/train.py
Labels: TODO, enhancement, python

#21221 Remove unnecessary `lxml` dependency
  ultralytics/utils/__init__.py
Labels: dependencies, exports, python

#21215 Fix the expected count for `final_mixed_train_no_coco_segm` in `GroundingDataset`
  ultralytics/data/dataset.py
Labels: enhancement, python

#21208 Add deprecation warning to `ultralytics/examples`
  examples/README.md
Labels: documentation, enhancement

#21226 Fix: Move YOLO label file writing outside annotation loop in `visdrone2yolo` function
  ultralytics/cfg/datasets/VisDrone.yaml
Labels: bug, enhancement, python

#21227 Update Sony IMX Doc with COCO128 Benchmarks
  docs/en/integrations/sony-imx500.md
Labels: documentation, embedded

#21229 Fix COCO128 capitalization in Sony IMX Doc
  docs/en/integrations/sony-imx500.md
Labels: documentation

#21238 Pin `paddlepaddle==3.0.0` for ARM64
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: dependencies, exports, python

#21236 Add `summary` method in `val.md`
  docs/en/modes/predict.md
  docs/en/modes/val.md
  ultralytics/engine/results.py
  ultralytics/utils/metrics.py
Labels: documentation

#21091 `ultralytics 8.3.161` Eliminate `../datasets/` in data yaml files for better `datasets_dir` compatibility
  docs/en/datasets/detect/index.md
  docs/en/datasets/obb/index.md
  docs/en/datasets/pose/index.md
  docs/en/datasets/segment/index.md
  docs/en/models/yolo-world.md
  docs/en/models/yoloe.md
  docs/en/usage/simple-utilities.md
  docs/en/yolov5/tutorials/train_custom_data.md
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/cfg/datasets/Argoverse.yaml
  ultralytics/cfg/datasets/DOTAv1.5.yaml
  ultralytics/cfg/datasets/DOTAv1.yaml
  ultralytics/cfg/datasets/GlobalWheat2020.yaml
  ultralytics/cfg/datasets/HomeObjects-3K.yaml
  ultralytics/cfg/datasets/ImageNet.yaml
  ultralytics/cfg/datasets/Objects365.yaml
  ultralytics/cfg/datasets/SKU-110K.yaml
  ultralytics/cfg/datasets/VOC.yaml
  ultralytics/cfg/datasets/VisDrone.yaml
  ultralytics/cfg/datasets/african-wildlife.yaml
  ultralytics/cfg/datasets/brain-tumor.yaml
  ultralytics/cfg/datasets/carparts-seg.yaml
  ultralytics/cfg/datasets/coco-pose.yaml
  ultralytics/cfg/datasets/coco.yaml
  ultralytics/cfg/datasets/coco128-seg.yaml
  ultralytics/cfg/datasets/coco128.yaml
  ultralytics/cfg/datasets/coco8-grayscale.yaml
  ultralytics/cfg/datasets/coco8-multispectral.yaml
  ultralytics/cfg/datasets/coco8-pose.yaml
  ultralytics/cfg/datasets/coco8-seg.yaml
  ultralytics/cfg/datasets/coco8.yaml
  ultralytics/cfg/datasets/crack-seg.yaml
  ultralytics/cfg/datasets/dog-pose.yaml
  ultralytics/cfg/datasets/dota8-multispectral.yaml
  ultralytics/cfg/datasets/dota8.yaml
  ultralytics/cfg/datasets/hand-keypoints.yaml
  ultralytics/cfg/datasets/lvis.yaml
  ultralytics/cfg/datasets/medical-pills.yaml
  ultralytics/cfg/datasets/open-images-v7.yaml
  ultralytics/cfg/datasets/package-seg.yaml
  ultralytics/cfg/datasets/signature.yaml
  ultralytics/cfg/datasets/tiger-pose.yaml
  ultralytics/cfg/datasets/xView.yaml
  ultralytics/data/converter.py
  ultralytics/data/split.py
  ultralytics/models/yolo/world/train_world.py
Labels: TODO, documentation, enhancement
