Repository ultralytics/ultralytics, pull requests merged in 2025-10, with the labels that each got.

#22268 docs: 📝 Update link to Segment Anything GitHub in SAM documentation
  docs/en/models/sam.md
Labels: documentation

#22290 Apply 3-sigma iterative rejection to Tune scatterplots
  ultralytics/utils/plotting.py
Labels: enhancement, python

#22292 Retry Slow CI tests once
  .github/workflows/ci.yml
Labels: devops

#22286 `ultralytics 8.3.205` Reset checkpoint arguments after training
  ultralytics/__init__.py
  ultralytics/engine/model.py
Labels: bug, python

#22300 `ultralytics 8.3.206` Support dynamic batch and image size with CoreML export
  docs/en/macros/export-table.md
  tests/test_exports.py
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: documentation, exports, python

#22310 `ultralytics 8.3.207` Apple MLProgram NMS models 80-class pad workaround
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
Labels: enhancement, exports, python
