Repository ultralytics/ultralytics, pull requests merged in 2025-08, with the labels that each got.

#21555 Fix simple-utilities.md documentation regarding OBB
  docs/en/usage/simple-utilities.md
Labels: documentation, OBB

#21563 `ultralytics 8.3.172` unify downloads progress TQDM
  docs/mkdocs_github_authors.yaml
  ultralytics/__init__.py
  ultralytics/utils/downloads.py
Labels: enhancement, dependencies, python

#21565 Bump `mkdocs-ultralytics-plugin>=0.1.26`
  pyproject.toml
Labels: documentation, dependencies

#21549 `ultralytics 8.3.173` Fix ClearML logging for `metrics` and `val` categories
  ultralytics/__init__.py
  ultralytics/utils/callbacks/clearml.py
Labels: bug, enhancement, python

#21578 Remove libmamba from Conda CI
  .github/workflows/ci.yml
Labels: dependencies, devops

#21577 `ultralytics 8.3.174` Streamlined Conda package CI
  .github/workflows/ci.yml
  ultralytics/__init__.py
Labels: enhancement, devops

#21483 Add `classes` and total `counts` in solutions `Logging`
  ultralytics/solutions/object_cropper.py
  ultralytics/solutions/solutions.py
Labels: enhancement, solutions, python

#21489 Add `queue-management` notebook in docs
  docs/en/guides/queue-management.md
Labels: documentation, Notebook

#21583 Update Google Colab notebooks
  examples/heatmaps.ipynb
  examples/hub.ipynb
  examples/object_counting.ipynb
  examples/object_tracking.ipynb
  examples/tutorial.ipynb
  ultralytics/utils/__init__.py
Labels: documentation, Notebook

#21605 `ultralytics 8.3.175` YOLOE `is_fused()` check prior to setting classes
  ultralytics/__init__.py
  ultralytics/models/yolo/model.py
Labels: enhancement, detect, python

#21608 YOLOE: Scope prompt embedding fuse to export process
  ultralytics/engine/exporter.py
  ultralytics/models/yolo/model.py
  ultralytics/nn/tasks.py
Labels: enhancement, exports, python

#21616 Fix missing imports in `sahi-tiled-inference` guide
  docs/en/guides/sahi-tiled-inference.md
Labels: documentation, Notebook

#21631 Add MNN matrix export tests to --slow CI
  docs/en/reference/utils/callbacks/comet.md
  docs/mkdocs_github_authors.yaml
  tests/test_exports.py
Labels: devops, exports, python

#21573 Add missing `dynamic=True` for `torchscript` exports
  docs/en/integrations/torchscript.md
  docs/en/macros/export-table.md
  examples/tutorial.ipynb
  tests/test_exports.py
  ultralytics/engine/exporter.py
Labels: enhancement, exports, python

#21648 Install NCNN with '--no-deps'
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: documentation, embedded, exports

#21649 Combine Dockerfile RUN commands
  docker/Dockerfile
  docker/Dockerfile-arm64
  docker/Dockerfile-conda
  docker/Dockerfile-cpu
  docker/Dockerfile-jetson-jetpack4
  docker/Dockerfile-jetson-jetpack5
  docker/Dockerfile-jetson-jetpack6
  docker/Dockerfile-jupyter
  docker/Dockerfile-python
  docker/Dockerfile-runner
Labels: devops, embedded, exports

#21661 `ultralytics 8.3.178` new lighter `Dockerfile-python` images
  .github/workflows/docker.yml
  docker/Dockerfile
  docker/Dockerfile-jetson-jetpack4
  docker/Dockerfile-jetson-jetpack5
  docker/Dockerfile-jetson-jetpack6
  docker/Dockerfile-python
  docker/Dockerfile-python-export
  docker/Dockerfile-runner
  ultralytics/__init__.py
Labels: devops, exports

#21665 Use apt-get clean in Dockerfiles
  docker/Dockerfile
  docker/Dockerfile-arm64
  docker/Dockerfile-jupyter
  docker/Dockerfile-python
  docker/Dockerfile-python-export
  docker/Dockerfile-runner
Labels: enhancement, devops, python

#21667 YOLOE: Simplify `set_classes` and support text prompt CLI usage
  ultralytics/cfg/__init__.py
  ultralytics/models/yolo/model.py
Labels: bug, enhancement, segment, detect, python

#21671 chore: remove `click` version lock as 8.2.2 was yanked
  pyproject.toml
Labels: dependencies, python

#21675 FROM pytorch/pytorch:2.8.0-cuda12.8-cudnn9-runtime
  .github/workflows/docker.yml
  docker/Dockerfile
  docker/Dockerfile-export
  docker/Dockerfile-runner
Labels: dependencies, devops

#21680 `ultralytics 8.3.179` Pin `tensorflow<=2.19.0` for exports
  .github/workflows/ci.yml
  pyproject.toml
  ultralytics/__init__.py
Labels: dependencies, exports

#21683 Fix CI.md table
  docs/en/help/CI.md
Labels: documentation

#21688 Add https://youtu.be/hfSK3Mk5P0I to docs
  docs/en/integrations/comet.md
Labels: documentation, enhancement

#21700 Fix SAM `Predictor` example in docs
  docs/en/models/sam.md
  ultralytics/models/sam/predict.py
Labels: documentation, python

#21670 YOLOE: Fix `device` selection and support `half` inference for visual prompt
  ultralytics/models/yolo/model.py
  ultralytics/models/yolo/yoloe/predict.py
  ultralytics/nn/modules/block.py
Labels: bug, segment, python

#21726 Support inference on SAM models without `high_res_features`
  ultralytics/models/sam/modules/decoders.py
  ultralytics/models/sam/predict.py
Labels: enhancement, segment, python

#21737 Fix argument type for `imgsz` and update `rect` description in docs
  docs/en/macros/train-args.md
Labels: documentation

#21743 Support flexible `imgsz` for SAM2 tracking
  ultralytics/models/sam/modules/sam.py
  ultralytics/models/sam/predict.py
Labels: bug, enhancement, python

#21745 Fix YOLOE prompt-free validation example in docs
  docs/en/models/yoloe.md
  ultralytics/models/yolo/yoloe/val.py
Labels: documentation, segment

#21682 Enable GitHub GPU runner CI
  .github/workflows/ci.yml
  tests/test_cuda.py
Labels: enhancement, devops

#21747 `ultralytics 8.3.183` New NDJSON dataset format support
  docs/en/datasets/detect/index.md
  docs/en/datasets/obb/index.md
  docs/en/datasets/pose/index.md
  docs/en/datasets/segment/index.md
  docs/mkdocs_github_authors.yaml
  tests/test_python.py
  ultralytics/__init__.py
  ultralytics/data/converter.py
  ultralytics/engine/trainer.py
Labels: enhancement, python

#21773 Update metrics.py from numpy to floats
  ultralytics/utils/metrics.py
Labels: enhancement, python

#21764 `ultralytics 8.3.184` New SystemLogger class
  docs/en/reference/utils/logger.md
  ultralytics/__init__.py
  ultralytics/utils/callbacks/platform.py
  ultralytics/utils/logger.py
Labels: enhancement, python

#21776 `uv pip install` GPU CI requirements
  .github/workflows/ci.yml
Labels: dependencies, devops

#21789 Fix TQDM Rich bars to 10 width
  ultralytics/__init__.py
  ultralytics/utils/__init__.py
Labels: enhancement, python

#21793 Use `!uv pip install` in jupyter notebooks
  docs/en/datasets/explorer/explorer.md
  examples/heatmaps.ipynb
  examples/hub.ipynb
  examples/object_counting.ipynb
  examples/object_tracking.ipynb
  examples/tutorial.ipynb
Labels: documentation, Notebook

#21798 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/docker.yml
  README.md
  README.zh-CN.md
  docs/README.md
  docs/en/guides/ros-quickstart.md
  docs/en/integrations/sony-imx500.md
  docs/en/quickstart.md
  docs/en/tasks/classify.md
  docs/mkdocs_github_authors.yaml
  examples/heatmaps.ipynb
  examples/hub.ipynb
  examples/object_counting.ipynb
  examples/object_tracking.ipynb
  examples/tutorial.ipynb
Labels: documentation, devops

#21799 Update TQDM download.py units to "files"
  ultralytics/utils/downloads.py
Labels: enhancement, python

#21807 Only pin memory on CUDA systems
  ultralytics/data/build.py
  ultralytics/data/utils.py
Labels: enhancement, python

#21805 Fix `region` visualization in `zone-counting` solution
  ultralytics/solutions/region_counter.py
Labels: bug, solutions

#21802 Fix `coreml` export `device` bug on `macOS` and `linux`
  ultralytics/engine/exporter.py
Labels: bug, exports

#21790 `ultralytics 8.3.186` Zero-dependency TQDM progress bars
  .github/workflows/docs.yml
  docs/build_docs.py
  docs/en/quickstart.md
  docs/en/reference/utils/__init__.md
  docs/en/reference/utils/tqdm.md
  mkdocs.yml
  pyproject.toml
  ultralytics/__init__.py
  ultralytics/cfg/datasets/Argoverse.yaml
  ultralytics/cfg/datasets/Objects365.yaml
  ultralytics/cfg/datasets/SKU-110K.yaml
  ultralytics/cfg/datasets/VOC.yaml
  ultralytics/cfg/datasets/VisDrone.yaml
  ultralytics/cfg/datasets/xView.yaml
  ultralytics/utils/__init__.py
  ultralytics/utils/logger.py
  ultralytics/utils/tqdm.py
Labels: enhancement, python

#21815 Add OBB angle limitation note to Docs
  docs/en/tasks/obb.md
Labels: documentation, OBB

#21816 Update banners redirect to https://www.ultralytics.com/events/yolovision
  README.md
  README.zh-CN.md
  docs/en/datasets/explorer/explorer.md
  docs/en/index.md
Labels: documentation

#21811 Update `mkdocs-ultralytics-plugin` for `beautifulsoup4>=4.13.5`
  pyproject.toml
Labels: documentation, dependencies, devops

#21818 Add `plt_settings` decorator to `plot_tune_results` for `agg` backend
  ultralytics/utils/plotting.py
Labels: bug, enhancement, devops, python

#21825 Update typo in `mobile-sam.md`
  docs/en/models/mobile-sam.md
Labels: documentation

#21784 Display `instances` count on `bars` in `labels.jpg`
  ultralytics/utils/plotting.py
Labels: enhancement, python

#21232 `ultralytics 8.3.187` SAM2: Add `SAM2DynamicInteractivePredictor` support few-shot inference
  docs/en/models/sam-2.md
  docs/en/reference/models/sam/predict.md
  docs/mkdocs_github_authors.yaml
  ultralytics/__init__.py
  ultralytics/models/sam/__init__.py
  ultralytics/models/sam/modules/sam.py
  ultralytics/models/sam/predict.py
Labels: enhancement, segment, python

#21835 Update typo in `sam-2.md`
  docs/en/models/sam-2.md
Labels: documentation

#21842 Serve Docs automatically during development
  docs/build_docs.py
  docs/mkdocs_github_authors.yaml
Labels: documentation, devops

#21843 Add downloads.py buffer size
  ultralytics/utils/downloads.py
Labels: enhancement, python

#21820 refactor: ♻️ enhance polars configuration for better benchmark data display
  ultralytics/utils/benchmarks.py
Labels: enhancement, python

#21837 Add `file_name` field to `predictions.json` for better image-annotation alignment
  ultralytics/models/rtdetr/val.py
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/obb/val.py
  ultralytics/models/yolo/segment/val.py
Labels: enhancement, detect, python

#21758 Fix TensorFlow export with `onnx>=1.18.0`
  pyproject.toml
  ultralytics/engine/exporter.py
Labels: dependencies, exports, python

#21848 Add support of serving docs automatically for `Linux`
  docs/build_docs.py
Labels: documentation, python

#21849 Fix `TQDM` progress bars when working with empty sequence
  ultralytics/utils/tqdm.py
Labels: bug, python

#21850 `ultralytics 8.3.188` Faster downloads via a single `request`
  ultralytics/__init__.py
  ultralytics/utils/downloads.py
Labels: enhancement, python

#21844 `ultralytics 8.3.189` 3x faster inplace `model.fuse()`
  ultralytics/__init__.py
  ultralytics/utils/torch_utils.py
Labels: enhancement, python

#21861 Add `coremltools>=8.0` check to Autobackend
  ultralytics/nn/autobackend.py
Labels: dependencies, exports, python

#21868 Update `TQDM` progress bar to display remaining time
  ultralytics/utils/tqdm.py
Labels: enhancement, python

#21871 Fix prediction logging info for `obb`
  ultralytics/engine/results.py
Labels: bug, OBB, python

#21876 Scope `requests` imports
  ultralytics/hub/__init__.py
  ultralytics/hub/auth.py
  ultralytics/hub/google/__init__.py
  ultralytics/hub/session.py
  ultralytics/hub/utils.py
  ultralytics/utils/callbacks/platform.py
  ultralytics/utils/checks.py
  ultralytics/utils/downloads.py
  ultralytics/utils/logger.py
Labels: enhancement, python

#21879 Target CI to all PR branches
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/format.yml
Labels: devops

#21877 Eliminate duplicate ops indexing
  ultralytics/utils/ops.py
Labels: enhancement, python

#21883 `MACOS14` check
  ultralytics/utils/__init__.py
Labels: enhancement, python

#21886 Faster online check using DNS resolution
  ultralytics/utils/__init__.py
Labels: enhancement, python

#21862 `ultralytics 8.3.190` Autobackend `torch`-native NMS
  docs/en/reference/utils/nms.md
  docs/en/reference/utils/ops.md
  examples/YOLOv8-Segmentation-ONNXRuntime-Python/main.py
  mkdocs.yml
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/engine/validator.py
  ultralytics/models/yolo/detect/predict.py
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/obb/val.py
  ultralytics/nn/autobackend.py
  ultralytics/utils/nms.py
  ultralytics/utils/ops.py
  ultralytics/utils/tal.py
  ultralytics/utils/tqdm.py
Labels: enhancement, dependencies, python

#21889 Update mkdocs.yml to `ignore_init_summary`
  mkdocs.yml
Labels: documentation
