Repository ultralytics/ultralytics, pull requests merged in 2025-02, with the labels that each got.

#18964 Add note on failing RKNN inference on select Rockchip hardware
  docs/en/integrations/rockchip-rknn.md
Labels: TODO, documentation, enhancement, embedded

#19068 Add `not_in_nav` section to mkdocs.yml
  mkdocs.yml
Labels: documentation

#19067 `ultralytics 8.3.71` require explicit `torch.nn` usage
  .github/workflows/docs.yml
  docs/build_docs.py
  pyproject.toml
  ultralytics/__init__.py
  ultralytics/cfg/models/v6/yolov6.yaml
  ultralytics/engine/model.py
  ultralytics/models/sam/modules/sam.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/nn/autobackend.py
  ultralytics/nn/tasks.py
Labels: documentation, dependencies

#19073 Resolve warnings
  ultralytics/engine/exporter.py
  ultralytics/nn/tasks.py
Labels: documentation, enhancement

#19086 Add https://youtu.be/C4mc40YKm-g and notebook badge in docs
  docs/en/datasets/segment/crack-seg.md
Labels: documentation, segment, Notebook

#18952 Add Export Arguments tables to all Export docs
  docs/en/integrations/coreml.md
  docs/en/integrations/edge-tpu.md
  docs/en/integrations/mnn.md
  docs/en/integrations/ncnn.md
  docs/en/integrations/onnx.md
  docs/en/integrations/openvino.md
  docs/en/integrations/paddlepaddle.md
  docs/en/integrations/rockchip-rknn.md
  docs/en/integrations/sony-imx500.md
  docs/en/integrations/tensorrt.md
  docs/en/integrations/tf-graphdef.md
  docs/en/integrations/tf-savedmodel.md
  docs/en/integrations/tfjs.md
  docs/en/integrations/tflite.md
  docs/en/integrations/torchscript.md
  docs/en/macros/export-args.md
Labels: TODO, documentation, exports

#19083 Fix missing nc attribute error on NMS export
  ultralytics/engine/exporter.py
Labels: bug, exports

#19085 Replace `beautifulsoup4` pin with `mkdocs-ultralytics-plugin>=0.1.17`
  .github/workflows/docs.yml
  pyproject.toml
Labels: documentation, dependencies

#19078 `ultralytics 8.3.72` Fix NVIDIA Jetson DLA core support for DLA inference
  .github/workflows/ci.yml
  docs/en/guides/nvidia-jetson.md
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: TODO, enhancement, exports

#19103 Remove `beautifulsoup4<=4.12.3` pin
  pyproject.toml
Labels: dependencies

#19098 Update JetPack 5 `torch` and `torchvision` packages
  docker/Dockerfile-jetson-jetpack5
  docs/en/guides/nvidia-jetson.md
Labels: TODO, documentation, dependencies, embedded

#19081 Minor `Results.to_sql` cleanup
  ultralytics/engine/results.py
  ultralytics/utils/checks.py
Labels: enhancement, OBB, detect

#19115 Add https://youtu.be/im7xBCnPURg to docs
  docs/en/datasets/segment/package-seg.md
Labels: documentation, enhancement, segment

#19114 `ultralytics 8.3.73` GitHub Container Registry Images at `ghcr.io`
  .github/workflows/ci.yml
  .github/workflows/docker.yml
  ultralytics/__init__.py
Labels: enhancement, devops

#19125 Fix docker.yml
  .github/workflows/docker.yml
Labels: dependencies, devops

#19124 Fix missing data warning and undefined variables
  ultralytics/utils/benchmarks.py
Labels: enhancement, fixed, detect

#19128 Fix missing data.yaml error on int8 export
  ultralytics/utils/benchmarks.py
Labels: bug, exports

#19146 Return PIL image if `pil=True`
  ultralytics/engine/results.py
Labels: documentation, enhancement

#19138 Unset CUBLAS_WORKSPACE_CONFIG for non-deterministic training and inference
  docs/en/reference/utils/torch_utils.md
  ultralytics/engine/model.py
  ultralytics/engine/trainer.py
  ultralytics/utils/__init__.py
  ultralytics/utils/torch_utils.py
Labels: enhancement

#19144 `ultralytics 8.3.74` Fix Ray Tune callback error
  ultralytics/__init__.py
  ultralytics/utils/callbacks/raytune.py
Labels: enhancement, dependencies

#19156 Auto-annotate and SAM docs update
  docs/en/macros/sam-auto-annotate.md
  docs/en/models/sam-2.md
Labels: documentation

#19177 Switch to `perf_counter()` for latency measurement
  ultralytics/utils/ops.py
Labels: enhancement, devops

#19206 Force protobuf>=5 for SavedModel export
  ultralytics/engine/exporter.py
Labels: dependencies, exports

#19216 Fix Docker QEMU issues while building JetPack 6 Dockerfile
  .github/workflows/docker.yml
Labels: TODO, devops, embedded

#19203 Fix `bus.jpg` path in `predict.md`
  docs/en/modes/predict.md
Labels: documentation, enhancement

#19211 Update NMS description on export-args.md
  docs/en/macros/export-args.md
Labels: documentation, exports

#19215 Add NMS related args to export-table.md
  docs/en/macros/export-table.md
Labels: documentation, exports

#19160 Add Solutions CLI usage in `quickstart.md`
  docs/en/quickstart.md
Labels: documentation, solutions

#19154 Fix `edgetpu` and `tfjs` exports for `arm64` Linux
  ultralytics/engine/exporter.py
Labels: TODO, embedded, exports

#19218 Fix windows async np.save bug
  ultralytics/data/utils.py
Labels: bug, enhancement

#19169 Fix `print()` for ConfusionMatrix for Classify task
  ultralytics/utils/metrics.py
Labels: bug, classify

#19164 Fix updating of best epoch during early stopping
  ultralytics/utils/torch_utils.py
Labels: bug, enhancement

#19224 Initialize `model_name` attribute
  ultralytics/engine/model.py
Labels: enhancement, fixed

#19227 Update results.boxes docs: boxes.id may be None
  ultralytics/engine/results.py
Labels: documentation, track

#19254 Fix bytes to GB conversion for logged VRAM usage
  ultralytics/engine/trainer.py
Labels: enhancement

#19257 Use new "Issue Type" in templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: documentation, devops

#19265 Add https://youtu.be/im7xBCnPURg to docs
  docs/en/guides/security-alarm-system.md
Labels: documentation

#19173 Support CoreML NMS export for Segment, Pose and OBB
  docs/en/macros/export-table.md
  docs/en/reference/engine/exporter.md
  tests/test_exports.py
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
  ultralytics/utils/ops.py
Labels: OBB, segment, detect, pose, exports

#19276 Standardize `str` formatting in docs
  docs/en/guides/analytics.md
  docs/en/integrations/coreml.md
  docs/en/integrations/edge-tpu.md
  docs/en/integrations/mnn.md
  docs/en/integrations/ncnn.md
  docs/en/integrations/onnx.md
  docs/en/integrations/openvino.md
  docs/en/integrations/paddlepaddle.md
  docs/en/integrations/rockchip-rknn.md
  docs/en/integrations/sony-imx500.md
  docs/en/integrations/tensorrt.md
  docs/en/integrations/tf-graphdef.md
  docs/en/integrations/tf-savedmodel.md
  docs/en/integrations/tfjs.md
  docs/en/integrations/tflite.md
  docs/en/integrations/torchscript.md
  docs/en/macros/augmentation-args.md
  docs/en/macros/export-args.md
  docs/en/macros/sam-auto-annotate.md
  docs/en/macros/solutions-args.md
  docs/en/macros/track-args.md
  docs/en/macros/validation-args.md
Labels: TODO, documentation

#19275 Add detailed usage with demos to reCamera doc
  docs/en/integrations/seeedstudio-recamera.md
Labels: TODO, documentation, detect, embedded

#19282 Add examples showing how to use `result` for all tasks
  docs/en/tasks/detect.md
  docs/en/tasks/obb.md
  docs/en/tasks/pose.md
  docs/en/tasks/segment.md
Labels: documentation, OBB

#19273 Revert "Support CoreML NMS export for Segment, Pose and OBB"
  docs/en/macros/export-table.md
  docs/en/reference/engine/exporter.md
  tests/test_exports.py
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
  ultralytics/utils/ops.py
Labels: segment, detect, exports

#19278 Fix error with `torch` tensor input in `model.track()`
  ultralytics/trackers/track.py
Labels: OBB, track, detect

#19249 `ultralytics 8.3.76` fix `dynamic` batch inference with NMS export
  ultralytics/__init__.py
  ultralytics/engine/exporter.py
Labels: TODO, bug, enhancement, exports

#19304 Fix dynamic export with YOLO World
  ultralytics/engine/exporter.py
Labels: enhancement, exports

#19308 Revert "Fix dynamic export with YOLO World"
  ultralytics/engine/exporter.py
Labels: exports

#19314 Allow missing `thop` package
  ultralytics/nn/tasks.py
  ultralytics/utils/torch_utils.py
Labels: enhancement, dependencies

#19312 `ultralytics 8.3.77` faster YOLOv8-Segment ONNX Runtime example
  examples/YOLOv8-Segmentation-ONNXRuntime-Python/main.py
  ultralytics/__init__.py
Labels: enhancement, segment, exports

#19319 Remove unused parameters from `export_tflite`
  ultralytics/engine/exporter.py
Labels: enhancement, exports

#19322 Fix ONNX RuntimeError with dynamic WorldModel
  ultralytics/nn/tasks.py
Labels: enhancement, exports

#19328 Add YOLO12 model info
  docs/model_data.py
Labels: documentation, enhancement

#19331 Add https://youtu.be/BPYkGt3odNk to docs
  docs/en/guides/nvidia-jetson.md
Labels: documentation, embedded

#19329 Refactor with simplifications
  examples/YOLOv8-Segmentation-ONNXRuntime-Python/main.py
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
  ultralytics/utils/torch_utils.py
Labels: enhancement, exports

#19332 Fix YOLO12 cfg links
  docs/en/models/yolo12.md
Labels: documentation

#19334 Fix `mkdocs_github_authors.yaml` author LexBarou
  docs/mkdocs_github_authors.yaml
Labels: documentation

#19337 Fix keypoints data display in `pose.md`
  docs/en/tasks/pose.md
Labels: documentation, pose

#19333 Fix YOLO12 performance table
  docs/en/models/yolo12.md
Labels: documentation

#19351 Fix benchmark.js
  docs/overrides/javascript/benchmark.js
Labels: documentation

#19358 Add https://youtu.be/SMSJvjUG1ko to `yolo12.md`
  docs/en/models/yolo12.md
  docs/model_data.py
Labels: documentation, enhancement

#19365 Update model_data.py authors
  docs/model_data.py
Labels: documentation

#19349 Assign variable `dt` before reference in exception block
  ultralytics/engine/exporter.py
Labels: enhancement, exports

#19372 Use `chart.js@latest`
  docs/en/models/rtdetr.md
  docs/en/models/yolo11.md
  docs/en/models/yolov10.md
  docs/en/models/yolov5.md
  docs/en/models/yolov6.md
  docs/en/models/yolov7.md
  docs/en/models/yolov8.md
  docs/en/models/yolov9.md
  docs/en/modes/benchmark.md
Labels: documentation, dependencies

#19378 YOLOv3 paper URL update
  docs/en/index.md
Labels: documentation

#19381 Det models with `nc=1` when `single_cls=True`
  ultralytics/engine/trainer.py
Labels: enhancement, detect

#19408 Fixed Comet integration to use class map aligned index when trying to get class name
  ultralytics/utils/callbacks/comet.py
Labels: bug, enhancement

#19400 Simplify `auto_annotate` function
  ultralytics/data/annotator.py
Labels: enhancement, segment

#19402 Updates `imgToAnns` variable to `snake_case`
  ultralytics/data/converter.py
Labels: documentation, enhancement

#19395 Fix `Grad strides do not match bucket view strides` warning for YOLO12 DDP training
  ultralytics/nn/modules/block.py
Labels: bug, enhancement

#19401 Updates `scaleFill` argument to `snake_case`
  ultralytics/data/augment.py
  ultralytics/models/rtdetr/predict.py
  ultralytics/models/rtdetr/val.py
Labels: documentation, enhancement

#19418 Check environment in docker.yml
  .github/workflows/docker.yml
Labels: dependencies, devops

#19420 Disable Dockerfile tests temporarily
  .github/workflows/docker.yml
Labels: enhancement, dependencies, devops

#19311 `ultralytics 8.3.79` Fix shift in HSV augmentation
  ultralytics/__init__.py
  ultralytics/data/augment.py
Labels: bug, enhancement

#19421 Optimize Sony IMX500 doc
  docs/en/integrations/sony-imx500.md
Labels: TODO, documentation, embedded, exports

#19122 Constrain OpenVINO versions to `>=2024.0.0,<2025.0.0`
  pyproject.toml
  ultralytics/engine/exporter.py
  ultralytics/nn/autobackend.py
Labels: TODO, enhancement, dependencies, exports

#19376 New Docs sortable tables
  docs/en/guides/deepstream-nvidia-jetson.md
  docs/en/guides/nvidia-jetson.md
  docs/en/models/yolo-nas.md
  docs/en/models/yolo-world.md
  docs/en/models/yolo11.md
  docs/en/models/yolo12.md
  docs/en/models/yolov10.md
  docs/en/models/yolov5.md
  docs/en/models/yolov7.md
  docs/en/models/yolov8.md
  docs/en/models/yolov9.md
  docs/overrides/javascript/tablesort.js
  mkdocs.yml
Labels: documentation, enhancement

#19422 Fixing tflite export CI error
  .github/workflows/docker.yml
  docker/Dockerfile
Labels: dependencies, devops, exports

#19429 Fix rbox regularization
  ultralytics/utils/ops.py
Labels: bug, OBB

#19426 `ultralytics 8.3.80` Fix YOLO-NAS export
  ultralytics/__init__.py
  ultralytics/models/nas/model.py
Labels: enhancement, exports

#19306 Update Raspberry Pi 5 CIs with 16GB model
  .github/workflows/ci.yml
  tests/test_exports.py
Labels: TODO, devops, embedded

#19461 New: add `SAM` and `SAM-2` notebook in docs
  docs/en/models/sam-2.md
  docs/en/models/sam.md
Labels: documentation, Notebook

#19463 Add installation path to `yolo checks` output
  ultralytics/utils/checks.py
Labels: enhancement, devops

#19457 Clarify metadata instructions in Triton docs
  docs/en/guides/triton-inference-server.md
Labels: documentation

#19455 Fix Docs table number sorting
  docs/overrides/javascript/tablesort.js
Labels: documentation

#19439 Add examples for `plotting` reference
  ultralytics/cfg/__init__.py
  ultralytics/data/augment.py
  ultralytics/data/utils.py
  ultralytics/utils/plotting.py
Labels: documentation, enhancement

#19465 Update SAM 2 research paper links
  docs/en/models/sam-2.md
Labels: documentation

#19478 Clean up Raspberry Pi CI runners
  .github/workflows/ci.yml
Labels: TODO, devops, embedded

#19318 `ultralytics 8.3.81` Fix Metrics `on_plot` circular references
  ultralytics/__init__.py
  ultralytics/models/fastsam/val.py
  ultralytics/models/yolo/detect/val.py
  ultralytics/models/yolo/obb/val.py
  ultralytics/models/yolo/pose/val.py
  ultralytics/models/yolo/segment/val.py
  ultralytics/utils/metrics.py
Labels: bug, enhancement
